/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { isProgramError, type Address, type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM, type SolanaError } from '@solana/kit';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

/** Unauthorized: Assinatura de quem não é parte do acordo */
export const GIRO_ACORDOS_ERROR__UNAUTHORIZED = 0x1770; // 6000
/** InvalidStatus: Situação do acordo não permite esta ação */
export const GIRO_ACORDOS_ERROR__INVALID_STATUS = 0x1771; // 6001
/** InvalidTerms: Termos inválidos */
export const GIRO_ACORDOS_ERROR__INVALID_TERMS = 0x1772; // 6002
/** CapacityExceeded: Soma dos percentuais passaria de 100% ou a venda não cobre a parte de um acordo */
export const GIRO_ACORDOS_ERROR__CAPACITY_EXCEEDED = 0x1773; // 6003
/** TooManyAccounts: Acordos ou comissões demais nesta venda (v1) */
export const GIRO_ACORDOS_ERROR__TOO_MANY_ACCOUNTS = 0x1774; // 6004
/** AmountZero: Valor zero */
export const GIRO_ACORDOS_ERROR__AMOUNT_ZERO = 0x1775; // 6005
/** Overflow: Estouro aritmético */
export const GIRO_ACORDOS_ERROR__OVERFLOW = 0x1776; // 6006
/** ExceedsRemaining: Pagamento acima do restante */
export const GIRO_ACORDOS_ERROR__EXCEEDS_REMAINING = 0x1777; // 6007
/** MissingAgreement: Acordo ativo ausente ou conta que não é acordo deste programa */
export const GIRO_ACORDOS_ERROR__MISSING_AGREEMENT = 0x1778; // 6008
/** WrongOrder: Acordos fora da ordem de prioridade */
export const GIRO_ACORDOS_ERROR__WRONG_ORDER = 0x1779; // 6009
/** WrongMint: Token diferente do acordo */
export const GIRO_ACORDOS_ERROR__WRONG_MINT = 0x177a; // 6010
/** WrongSeller: Acordo de outro vendedor */
export const GIRO_ACORDOS_ERROR__WRONG_SELLER = 0x177b; // 6011
/** WrongSupplierAccount: Conta de destino não pertence ao fornecedor */
export const GIRO_ACORDOS_ERROR__WRONG_SUPPLIER_ACCOUNT = 0x177c; // 6012
/** DuplicateAgreement: Acordo repetido na venda */
export const GIRO_ACORDOS_ERROR__DUPLICATE_AGREEMENT = 0x177d; // 6013
/** ChangePending: Já existe um pedido de mudança aguardando decisão */
export const GIRO_ACORDOS_ERROR__CHANGE_PENDING = 0x177e; // 6014
/** NoPendingChange: Não há pedido de mudança */
export const GIRO_ACORDOS_ERROR__NO_PENDING_CHANGE = 0x177f; // 6015
/** AccountsMismatch: Número de contas não confere com a venda */
export const GIRO_ACORDOS_ERROR__ACCOUNTS_MISMATCH = 0x1780; // 6016
/** SaleLimit: Venda acima do teto configurado pelo vendedor */
export const GIRO_ACORDOS_ERROR__SALE_LIMIT = 0x1781; // 6017
/** InvalidUnit: Valor fora da menor fração (centavo) do token */
export const GIRO_ACORDOS_ERROR__INVALID_UNIT = 0x1782; // 6018

export type GiroAcordosError = typeof GIRO_ACORDOS_ERROR__ACCOUNTS_MISMATCH | typeof GIRO_ACORDOS_ERROR__AMOUNT_ZERO | typeof GIRO_ACORDOS_ERROR__CAPACITY_EXCEEDED | typeof GIRO_ACORDOS_ERROR__CHANGE_PENDING | typeof GIRO_ACORDOS_ERROR__DUPLICATE_AGREEMENT | typeof GIRO_ACORDOS_ERROR__EXCEEDS_REMAINING | typeof GIRO_ACORDOS_ERROR__INVALID_STATUS | typeof GIRO_ACORDOS_ERROR__INVALID_TERMS | typeof GIRO_ACORDOS_ERROR__INVALID_UNIT | typeof GIRO_ACORDOS_ERROR__MISSING_AGREEMENT | typeof GIRO_ACORDOS_ERROR__NO_PENDING_CHANGE | typeof GIRO_ACORDOS_ERROR__OVERFLOW | typeof GIRO_ACORDOS_ERROR__SALE_LIMIT | typeof GIRO_ACORDOS_ERROR__TOO_MANY_ACCOUNTS | typeof GIRO_ACORDOS_ERROR__UNAUTHORIZED | typeof GIRO_ACORDOS_ERROR__WRONG_MINT | typeof GIRO_ACORDOS_ERROR__WRONG_ORDER | typeof GIRO_ACORDOS_ERROR__WRONG_SELLER | typeof GIRO_ACORDOS_ERROR__WRONG_SUPPLIER_ACCOUNT;

let giroAcordosErrorMessages: Record<GiroAcordosError, string> | undefined;
if (process.env['NODE_ENV'] !== 'production') {
  giroAcordosErrorMessages = { [GIRO_ACORDOS_ERROR__ACCOUNTS_MISMATCH]: `Número de contas não confere com a venda`, [GIRO_ACORDOS_ERROR__AMOUNT_ZERO]: `Valor zero`, [GIRO_ACORDOS_ERROR__CAPACITY_EXCEEDED]: `Soma dos percentuais passaria de 100% ou a venda não cobre a parte de um acordo`, [GIRO_ACORDOS_ERROR__CHANGE_PENDING]: `Já existe um pedido de mudança aguardando decisão`, [GIRO_ACORDOS_ERROR__DUPLICATE_AGREEMENT]: `Acordo repetido na venda`, [GIRO_ACORDOS_ERROR__EXCEEDS_REMAINING]: `Pagamento acima do restante`, [GIRO_ACORDOS_ERROR__INVALID_STATUS]: `Situação do acordo não permite esta ação`, [GIRO_ACORDOS_ERROR__INVALID_TERMS]: `Termos inválidos`, [GIRO_ACORDOS_ERROR__INVALID_UNIT]: `Valor fora da menor fração (centavo) do token`, [GIRO_ACORDOS_ERROR__MISSING_AGREEMENT]: `Acordo ativo ausente ou conta que não é acordo deste programa`, [GIRO_ACORDOS_ERROR__NO_PENDING_CHANGE]: `Não há pedido de mudança`, [GIRO_ACORDOS_ERROR__OVERFLOW]: `Estouro aritmético`, [GIRO_ACORDOS_ERROR__SALE_LIMIT]: `Venda acima do teto configurado pelo vendedor`, [GIRO_ACORDOS_ERROR__TOO_MANY_ACCOUNTS]: `Acordos ou comissões demais nesta venda (v1)`, [GIRO_ACORDOS_ERROR__UNAUTHORIZED]: `Assinatura de quem não é parte do acordo`, [GIRO_ACORDOS_ERROR__WRONG_MINT]: `Token diferente do acordo`, [GIRO_ACORDOS_ERROR__WRONG_ORDER]: `Acordos fora da ordem de prioridade`, [GIRO_ACORDOS_ERROR__WRONG_SELLER]: `Acordo de outro vendedor`, [GIRO_ACORDOS_ERROR__WRONG_SUPPLIER_ACCOUNT]: `Conta de destino não pertence ao fornecedor` };
}

export function getGiroAcordosErrorMessage(code: GiroAcordosError): string {
  if (process.env['NODE_ENV'] !== 'production') {
    return (giroAcordosErrorMessages as Record<GiroAcordosError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isGiroAcordosError<TProgramErrorCode extends GiroAcordosError>(
    error: unknown,
    transactionMessage: { instructions: Record<number, { programAddress: Address }> },
    code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> & Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(error, transactionMessage, GIRO_ACORDOS_PROGRAM_ADDRESS, code);
}