import type {State} from './models.ts';
import {commitmentId,matches,searchDate} from './records.ts';
export interface HistoryRow {id:string;at:string;category:string;title:string;description:string;amount?:number;route?:string;commitmentId?:string}
export function financialHistory(state:State,query=''){
 const rows:HistoryRow[]=[];
 for(const s of state.sales.filter(s=>!s.demo)){rows.push({id:'sale:'+s.id,at:s.recordedAt??s.soldAt,category:'Venda',title:s.method==='cash'?'Venda em dinheiro':'Venda registrada',description:`${s.id} · Venda ${s.soldAt} (${s.soldAt.split('-').reverse().join('/')}) · ${s.participant??'Sem colaborador'} · ${s.paidAt?'Recebida':'A receber'}`,amount:s.amount,route:'receber/vendas/'+s.id});for(const [i,d] of (s.distribution??[]).entries())if(d.kind==='commission')rows.push({id:`participation:${s.id}:${i}`,at:s.settledAt??s.paidAt!,category:'Participação',title:'Participação de colaborador',description:`${d.recipient} · ${s.id} · ${d.mode==='simulated'?'Distribuição simulada':'Dinheiro destinado, ainda não confirma pagamento'}`,amount:d.amount,route:'equipe/'+d.recipientId+'/vendas'});}
 const labels:Record<string,string>={created:'Compromisso criado',submitted:'Proposta enviada',accepted:'Proposta aceita',refused:'Proposta recusada',activated:'Compromisso ativado',amortized:'Distribuição para compromisso',completed:'Compromisso concluído',renegotiation_requested:'Pedido de alteração',renegotiation_accepted:'Alteração aceita',renegotiation_refused:'Alteração recusada',renegotiation_closed:'Alteração cancelada',cash_paid:'Pagamento físico',draft_edited:'Rascunho editado',legacy_imported:'Histórico legado'};
 for(const c of state.commitments.filter(c=>!c.demo))for(const e of c.timeline??[])rows.push({id:e.id,at:e.at,category:'Compromisso',title:labels[e.type]??e.type,description:`${commitmentId(c)} · ${c.supplier} · ${e.actor==='seller'?'Titular':e.actor==='supplier'?'Outra parte':'Sistema'} · ${e.reason??''}${e.next?` · Condições: ${(e.next.original/100).toFixed(2)} / ${e.next.rateBps/100}% / ${e.next.due}${e.next.paymentMethod?' / '+e.next.paymentMethod:''}`:''}`,amount:e.amount,commitmentId:c.id,route:'compromissos'});
 for(const s of state.sales.filter(s=>!s.demo&&s.paidAt))rows.push({id:'received:'+s.id,at:s.settledAt??s.paidAt!,category:'Recebimento',title:'Venda recebida',description:`${s.id} · ${s.method==='cash'?'Dinheiro físico':'Digital simulado'} · Recebimento ${s.paidAt} (${s.paidAt!.split('-').reverse().join('/')})`,amount:s.amount,route:'receber/pagamentos/'+s.id});
 for(const p of state.accountPayments??[])rows.push({id:p.id,at:p.at,category:'Pagamento',title:p.useFreeBalance?'Pagamento com saldo disponível':'Pagamento de conta',description:`${p.name} · ${p.planId} · ${p.origin==='cash'?'Dinheiro físico confirmado':'Digital simulado'}`,amount:p.amount,route:'organizar/contas'});
 for(const p of state.accountPayments??[])if(p.remainingAfter===0)rows.push({id:'account-completed:'+p.id,at:p.at,category:'Pagamento',title:'Conta concluída',description:p.name+' · '+p.planId,route:'organizar/contas'});
 for(const w of state.dailyWages??[])rows.push({id:'daily:'+w.id,at:w.recordedAt??w.date,category:'Colaborador',title:'Dia trabalhado registrado',description:w.name+' · '+w.date,amount:w.amount,route:'equipe/'+w.memberId+'/historico'});
 for(const m of state.cashMovements??[])if(m.type==='ADJUSTMENT'&&m.origin==='additional_entry')rows.push({id:m.id,at:m.at,category:'Caixa',title:'Entrada adicional em dinheiro',description:m.description,amount:m.amount,route:'receber/caixa'});
 for(const e of state.planEvents??[])rows.push({id:'plan:'+e.id,at:e.at,category:'Planejamento',title:e.type==='reserved'?(e.saleId?'Reserva de venda':'Aporte manual'):e.type==='deleted'?'Cadastro arquivado / excluído':e.type==='created'?'Objetivo criado':'Objetivo alterado',description:`${e.name} · ${e.planId}${e.saleId?' · Venda '+e.saleId:''} · ${(e.before/100).toFixed(2)} → ${(e.after/100).toFixed(2)}`,amount:e.type==='reserved'?e.after-e.before:undefined,route:e.kind==='account'?'organizar/contas':'organizar/metas'});
 for(const e of state.planEvents??[])if(e.targetAfter&&e.type!=='deleted'&&e.before+(e.paidAfter??0)<e.targetAfter&&e.after+(e.paidAfter??0)===e.targetAfter)rows.push({id:'goal-completed:'+e.id,at:e.at,category:'Planejamento',title:e.kind==='account'?'Reserva da conta completa':'Meta concluída',description:e.name+' · '+e.planId,route:e.kind==='account'?'organizar/contas':'organizar/metas'});
 for(const p of state.cashPayments??[])rows.push({id:p.id,at:p.at,category:'Pagamento',title:'Pagamento em dinheiro',description:`${p.recipient} · ${state.commitments.find(c=>c.id===p.recipientId)?commitmentId(state.commitments.find(c=>c.id===p.recipientId)!):p.recipientId}`,amount:p.amount,route:p.kind==='commission'?'equipe/'+p.recipientId+'/historico':'compromissos',commitmentId:p.kind==='supplier'?p.recipientId:undefined});
 for(const p of state.dailyPayments??[]){const w=state.dailyWages?.find(w=>w.id===p.wageId);rows.push({id:p.id,at:state.cashMovements?.find(m=>m.id===p.cashMovementId)?.at??p.date,category:'Pagamento',title:'Pagamento de diária',description:`${w?.name??p.wageId} · ${p.id}`,amount:p.amount,route:w?`equipe/${w.memberId}/comprovantes/${w.id}/${p.id}`:undefined});}
 for(const s of state.cashSessions??[]){rows.push({id:'open:'+s.id,at:s.openedAt,category:'Caixa',title:'Abertura do caixa',description:`${s.id} · ${s.responsible??'Operador local'}`,amount:s.opening,route:'receber/caixa'});if(s.closedAt)rows.push({id:'close:'+s.id,at:s.closedAt,category:'Caixa',title:'Fechamento do caixa',description:`${s.id} · Esperado ${(s.closure!.expected/100).toFixed(2)} · Contado ${(s.closure!.counted/100).toFixed(2)} · Diferença ${(s.closure!.difference/100).toFixed(2)}`,amount:s.closure!.difference,route:'receber/caixa'});}
 for(const m of state.cashMovements??[])if(m.type==='MANUAL_OUTFLOW'&&!['daily_wage','account_payment'].includes(m.origin))rows.push({id:m.id,at:m.at,category:'Caixa',title:'Saída de caixa',description:m.description,amount:m.amount,route:'receber/caixa'});
 for(const e of state.memberEvents??[])rows.push({id:e.id,at:e.at,category:'Colaborador',title:({edited:'Colaborador editado',disabled:'Colaborador desativado',enabled:'Colaborador reativado',deleted:'Cadastro sem histórico excluído'})[e.type],description:`${e.name} · ${e.memberId}`,route:'equipe'});
 return rows.filter(r=>matches(query,r.id,r.title,r.category,r.description,searchDate(r.at),r.amount===undefined?'':(r.amount/100).toFixed(2))).sort((a,b)=>b.at.localeCompare(a.at));
}
