/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { fixEncoderSize, getAddressEncoder, getBytesEncoder, getProgramDerivedAddress, type Address, type ProgramDerivedAddress, type ReadonlyUint8Array } from '@solana/kit';

export type AgreementSeeds = {
seller: Address;
agreementKey: ReadonlyUint8Array;
};

export async function findAgreementPda(seeds: AgreementSeeds, config: { programAddress?: Address | undefined } = {}): Promise<ProgramDerivedAddress> {
  const { programAddress = 'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV' as Address<'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV'> } = config;
  return await getProgramDerivedAddress({ programAddress, seeds: [getBytesEncoder().encode(new Uint8Array([97, 103, 114, 101, 101, 109, 101, 110, 116])), getAddressEncoder().encode(seeds.seller), fixEncoderSize(getBytesEncoder(), 32).encode(seeds.agreementKey)]});
}