/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { fixEncoderSize, getAddressEncoder, getBytesEncoder, getProgramDerivedAddress, type Address, type ProgramDerivedAddress, type ReadonlyUint8Array } from '@solana/kit';

export type PaymentSeeds = {
agreement: Address;
nonce: ReadonlyUint8Array;
};

export async function findPaymentPda(seeds: PaymentSeeds, config: { programAddress?: Address | undefined } = {}): Promise<ProgramDerivedAddress> {
  const { programAddress = 'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV' as Address<'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV'> } = config;
  return await getProgramDerivedAddress({ programAddress, seeds: [getBytesEncoder().encode(new Uint8Array([99, 97, 115, 104])), getAddressEncoder().encode(seeds.agreement), fixEncoderSize(getBytesEncoder(), 16).encode(seeds.nonce)]});
}