/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const AGREEMENT_PROPOSED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([223, 233, 107, 85, 28, 89, 104, 9]);

export function getAgreementProposedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(AGREEMENT_PROPOSED_EVENT_DISCRIMINATOR); }

export type AgreementProposedEvent = { agreementKey: ReadonlyUint8Array;  };

export type AgreementProposedEventArgs = AgreementProposedEvent;

/** Gets the encoder for {@link AgreementProposedEventArgs} event data. */
export function getAgreementProposedEventEncoder(): FixedSizeEncoder<AgreementProposedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)]]), [getConstantEncoder(AGREEMENT_PROPOSED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link AgreementProposedEvent} event data. */
export function getAgreementProposedEventDecoder(): FixedSizeDecoder<AgreementProposedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)]]), [getConstantDecoder(AGREEMENT_PROPOSED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link AgreementProposedEvent} event data. */
export function getAgreementProposedEventCodec(): FixedSizeCodec<AgreementProposedEventArgs, AgreementProposedEvent> {
    return combineCodec(getAgreementProposedEventEncoder(), getAgreementProposedEventDecoder());
}

/** Parses the provided bytes into {@link AgreementProposedEvent} event data. */
export function parseAgreementProposedEvent(data: ReadonlyUint8Array | Uint8Array): AgreementProposedEvent {
    if (containsBytes(data, AGREEMENT_PROPOSED_EVENT_DISCRIMINATOR, 0)) { return getAgreementProposedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "AgreementProposedEvent" event discriminators.');
}