/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const AGREEMENT_REJECTED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([97, 58, 96, 83, 135, 37, 214, 211]);

export function getAgreementRejectedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(AGREEMENT_REJECTED_EVENT_DISCRIMINATOR); }

export type AgreementRejectedEvent = { agreementKey: ReadonlyUint8Array;  };

export type AgreementRejectedEventArgs = AgreementRejectedEvent;

/** Gets the encoder for {@link AgreementRejectedEventArgs} event data. */
export function getAgreementRejectedEventEncoder(): FixedSizeEncoder<AgreementRejectedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)]]), [getConstantEncoder(AGREEMENT_REJECTED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link AgreementRejectedEvent} event data. */
export function getAgreementRejectedEventDecoder(): FixedSizeDecoder<AgreementRejectedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)]]), [getConstantDecoder(AGREEMENT_REJECTED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link AgreementRejectedEvent} event data. */
export function getAgreementRejectedEventCodec(): FixedSizeCodec<AgreementRejectedEventArgs, AgreementRejectedEvent> {
    return combineCodec(getAgreementRejectedEventEncoder(), getAgreementRejectedEventDecoder());
}

/** Parses the provided bytes into {@link AgreementRejectedEvent} event data. */
export function parseAgreementRejectedEvent(data: ReadonlyUint8Array | Uint8Array): AgreementRejectedEvent {
    if (containsBytes(data, AGREEMENT_REJECTED_EVENT_DISCRIMINATOR, 0)) { return getAgreementRejectedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "AgreementRejectedEvent" event discriminators.');
}