/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const AGREEMENT_ACCEPTED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([179, 13, 67, 103, 171, 224, 35, 5]);

export function getAgreementAcceptedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(AGREEMENT_ACCEPTED_EVENT_DISCRIMINATOR); }

export type AgreementAcceptedEvent = { agreementKey: ReadonlyUint8Array;  };

export type AgreementAcceptedEventArgs = AgreementAcceptedEvent;

/** Gets the encoder for {@link AgreementAcceptedEventArgs} event data. */
export function getAgreementAcceptedEventEncoder(): FixedSizeEncoder<AgreementAcceptedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)]]), [getConstantEncoder(AGREEMENT_ACCEPTED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link AgreementAcceptedEvent} event data. */
export function getAgreementAcceptedEventDecoder(): FixedSizeDecoder<AgreementAcceptedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)]]), [getConstantDecoder(AGREEMENT_ACCEPTED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link AgreementAcceptedEvent} event data. */
export function getAgreementAcceptedEventCodec(): FixedSizeCodec<AgreementAcceptedEventArgs, AgreementAcceptedEvent> {
    return combineCodec(getAgreementAcceptedEventEncoder(), getAgreementAcceptedEventDecoder());
}

/** Parses the provided bytes into {@link AgreementAcceptedEvent} event data. */
export function parseAgreementAcceptedEvent(data: ReadonlyUint8Array | Uint8Array): AgreementAcceptedEvent {
    if (containsBytes(data, AGREEMENT_ACCEPTED_EVENT_DISCRIMINATOR, 0)) { return getAgreementAcceptedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "AgreementAcceptedEvent" event discriminators.');
}