/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getI64Decoder, getI64Encoder, getStructDecoder, getStructEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const AGREEMENT_COMPLETED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([213, 199, 79, 149, 251, 172, 90, 22]);

export function getAgreementCompletedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(AGREEMENT_COMPLETED_EVENT_DISCRIMINATOR); }

export type AgreementCompletedEvent = { agreementKey: ReadonlyUint8Array; completedTs: bigint;  };

export type AgreementCompletedEventArgs = { agreementKey: ReadonlyUint8Array; completedTs: number | bigint;  };

/** Gets the encoder for {@link AgreementCompletedEventArgs} event data. */
export function getAgreementCompletedEventEncoder(): FixedSizeEncoder<AgreementCompletedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['completedTs', getI64Encoder()]]), [getConstantEncoder(AGREEMENT_COMPLETED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link AgreementCompletedEvent} event data. */
export function getAgreementCompletedEventDecoder(): FixedSizeDecoder<AgreementCompletedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['completedTs', getI64Decoder()]]), [getConstantDecoder(AGREEMENT_COMPLETED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link AgreementCompletedEvent} event data. */
export function getAgreementCompletedEventCodec(): FixedSizeCodec<AgreementCompletedEventArgs, AgreementCompletedEvent> {
    return combineCodec(getAgreementCompletedEventEncoder(), getAgreementCompletedEventDecoder());
}

/** Parses the provided bytes into {@link AgreementCompletedEvent} event data. */
export function parseAgreementCompletedEvent(data: ReadonlyUint8Array | Uint8Array): AgreementCompletedEvent {
    if (containsBytes(data, AGREEMENT_COMPLETED_EVENT_DISCRIMINATOR, 0)) { return getAgreementCompletedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "AgreementCompletedEvent" event discriminators.');
}