/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBooleanDecoder, getBooleanEncoder, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, getU32Decoder, getU32Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const CHANGE_DECIDED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([9, 94, 117, 75, 139, 230, 208, 242]);

export function getChangeDecidedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(CHANGE_DECIDED_EVENT_DISCRIMINATOR); }

export type ChangeDecidedEvent = { agreementKey: ReadonlyUint8Array; accepted: boolean; version: number;  };

export type ChangeDecidedEventArgs = ChangeDecidedEvent;

/** Gets the encoder for {@link ChangeDecidedEventArgs} event data. */
export function getChangeDecidedEventEncoder(): FixedSizeEncoder<ChangeDecidedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['accepted', getBooleanEncoder()], ['version', getU32Encoder()]]), [getConstantEncoder(CHANGE_DECIDED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link ChangeDecidedEvent} event data. */
export function getChangeDecidedEventDecoder(): FixedSizeDecoder<ChangeDecidedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['accepted', getBooleanDecoder()], ['version', getU32Decoder()]]), [getConstantDecoder(CHANGE_DECIDED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link ChangeDecidedEvent} event data. */
export function getChangeDecidedEventCodec(): FixedSizeCodec<ChangeDecidedEventArgs, ChangeDecidedEvent> {
    return combineCodec(getChangeDecidedEventEncoder(), getChangeDecidedEventDecoder());
}

/** Parses the provided bytes into {@link ChangeDecidedEvent} event data. */
export function parseChangeDecidedEvent(data: ReadonlyUint8Array | Uint8Array): ChangeDecidedEvent {
    if (containsBytes(data, CHANGE_DECIDED_EVENT_DISCRIMINATOR, 0)) { return getChangeDecidedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "ChangeDecidedEvent" event discriminators.');
}