/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, getU32Decoder, getU32Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const CHANGE_PROPOSED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([170, 10, 10, 8, 244, 196, 146, 151]);

export function getChangeProposedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(CHANGE_PROPOSED_EVENT_DISCRIMINATOR); }

export type ChangeProposedEvent = { agreementKey: ReadonlyUint8Array; version: number;  };

export type ChangeProposedEventArgs = ChangeProposedEvent;

/** Gets the encoder for {@link ChangeProposedEventArgs} event data. */
export function getChangeProposedEventEncoder(): FixedSizeEncoder<ChangeProposedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['version', getU32Encoder()]]), [getConstantEncoder(CHANGE_PROPOSED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link ChangeProposedEvent} event data. */
export function getChangeProposedEventDecoder(): FixedSizeDecoder<ChangeProposedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['version', getU32Decoder()]]), [getConstantDecoder(CHANGE_PROPOSED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link ChangeProposedEvent} event data. */
export function getChangeProposedEventCodec(): FixedSizeCodec<ChangeProposedEventArgs, ChangeProposedEvent> {
    return combineCodec(getChangeProposedEventEncoder(), getChangeProposedEventDecoder());
}

/** Parses the provided bytes into {@link ChangeProposedEvent} event data. */
export function parseChangeProposedEvent(data: ReadonlyUint8Array | Uint8Array): ChangeProposedEvent {
    if (containsBytes(data, CHANGE_PROPOSED_EVENT_DISCRIMINATOR, 0)) { return getChangeProposedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "ChangeProposedEvent" event discriminators.');
}