/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const OFFCHAIN_PAYMENT_DISPUTED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([202, 199, 99, 146, 4, 117, 93, 187]);

export function getOffchainPaymentDisputedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(OFFCHAIN_PAYMENT_DISPUTED_EVENT_DISCRIMINATOR); }

export type OffchainPaymentDisputedEvent = { agreementKey: ReadonlyUint8Array; amount: bigint;  };

export type OffchainPaymentDisputedEventArgs = { agreementKey: ReadonlyUint8Array; amount: number | bigint;  };

/** Gets the encoder for {@link OffchainPaymentDisputedEventArgs} event data. */
export function getOffchainPaymentDisputedEventEncoder(): FixedSizeEncoder<OffchainPaymentDisputedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['amount', getU64Encoder()]]), [getConstantEncoder(OFFCHAIN_PAYMENT_DISPUTED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link OffchainPaymentDisputedEvent} event data. */
export function getOffchainPaymentDisputedEventDecoder(): FixedSizeDecoder<OffchainPaymentDisputedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['amount', getU64Decoder()]]), [getConstantDecoder(OFFCHAIN_PAYMENT_DISPUTED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link OffchainPaymentDisputedEvent} event data. */
export function getOffchainPaymentDisputedEventCodec(): FixedSizeCodec<OffchainPaymentDisputedEventArgs, OffchainPaymentDisputedEvent> {
    return combineCodec(getOffchainPaymentDisputedEventEncoder(), getOffchainPaymentDisputedEventDecoder());
}

/** Parses the provided bytes into {@link OffchainPaymentDisputedEvent} event data. */
export function parseOffchainPaymentDisputedEvent(data: ReadonlyUint8Array | Uint8Array): OffchainPaymentDisputedEvent {
    if (containsBytes(data, OFFCHAIN_PAYMENT_DISPUTED_EVENT_DISCRIMINATOR, 0)) { return getOffchainPaymentDisputedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "OffchainPaymentDisputedEvent" event discriminators.');
}