/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const OFFCHAIN_PAYMENT_RECORDED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([11, 18, 64, 2, 185, 100, 109, 189]);

export function getOffchainPaymentRecordedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(OFFCHAIN_PAYMENT_RECORDED_EVENT_DISCRIMINATOR); }

export type OffchainPaymentRecordedEvent = { agreementKey: ReadonlyUint8Array; amount: bigint;  };

export type OffchainPaymentRecordedEventArgs = { agreementKey: ReadonlyUint8Array; amount: number | bigint;  };

/** Gets the encoder for {@link OffchainPaymentRecordedEventArgs} event data. */
export function getOffchainPaymentRecordedEventEncoder(): FixedSizeEncoder<OffchainPaymentRecordedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['amount', getU64Encoder()]]), [getConstantEncoder(OFFCHAIN_PAYMENT_RECORDED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link OffchainPaymentRecordedEvent} event data. */
export function getOffchainPaymentRecordedEventDecoder(): FixedSizeDecoder<OffchainPaymentRecordedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['amount', getU64Decoder()]]), [getConstantDecoder(OFFCHAIN_PAYMENT_RECORDED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link OffchainPaymentRecordedEvent} event data. */
export function getOffchainPaymentRecordedEventCodec(): FixedSizeCodec<OffchainPaymentRecordedEventArgs, OffchainPaymentRecordedEvent> {
    return combineCodec(getOffchainPaymentRecordedEventEncoder(), getOffchainPaymentRecordedEventDecoder());
}

/** Parses the provided bytes into {@link OffchainPaymentRecordedEvent} event data. */
export function parseOffchainPaymentRecordedEvent(data: ReadonlyUint8Array | Uint8Array): OffchainPaymentRecordedEvent {
    if (containsBytes(data, OFFCHAIN_PAYMENT_RECORDED_EVENT_DISCRIMINATOR, 0)) { return getOffchainPaymentRecordedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "OffchainPaymentRecordedEvent" event discriminators.');
}