/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const OFFCHAIN_PAYMENT_CONFIRMED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([21, 16, 232, 14, 18, 169, 58, 95]);

export function getOffchainPaymentConfirmedEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(OFFCHAIN_PAYMENT_CONFIRMED_EVENT_DISCRIMINATOR); }

export type OffchainPaymentConfirmedEvent = { agreementKey: ReadonlyUint8Array; amount: bigint;  };

export type OffchainPaymentConfirmedEventArgs = { agreementKey: ReadonlyUint8Array; amount: number | bigint;  };

/** Gets the encoder for {@link OffchainPaymentConfirmedEventArgs} event data. */
export function getOffchainPaymentConfirmedEventEncoder(): FixedSizeEncoder<OffchainPaymentConfirmedEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['amount', getU64Encoder()]]), [getConstantEncoder(OFFCHAIN_PAYMENT_CONFIRMED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link OffchainPaymentConfirmedEvent} event data. */
export function getOffchainPaymentConfirmedEventDecoder(): FixedSizeDecoder<OffchainPaymentConfirmedEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['amount', getU64Decoder()]]), [getConstantDecoder(OFFCHAIN_PAYMENT_CONFIRMED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link OffchainPaymentConfirmedEvent} event data. */
export function getOffchainPaymentConfirmedEventCodec(): FixedSizeCodec<OffchainPaymentConfirmedEventArgs, OffchainPaymentConfirmedEvent> {
    return combineCodec(getOffchainPaymentConfirmedEventEncoder(), getOffchainPaymentConfirmedEventDecoder());
}

/** Parses the provided bytes into {@link OffchainPaymentConfirmedEvent} event data. */
export function parseOffchainPaymentConfirmedEvent(data: ReadonlyUint8Array | Uint8Array): OffchainPaymentConfirmedEvent {
    if (containsBytes(data, OFFCHAIN_PAYMENT_CONFIRMED_EVENT_DISCRIMINATOR, 0)) { return getOffchainPaymentConfirmedEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "OffchainPaymentConfirmedEvent" event discriminators.');
}