/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const PROPOSAL_CANCELLED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([253, 59, 104, 46, 129, 78, 9, 14]);

export function getProposalCancelledEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(PROPOSAL_CANCELLED_EVENT_DISCRIMINATOR); }

export type ProposalCancelledEvent = { agreementKey: ReadonlyUint8Array;  };

export type ProposalCancelledEventArgs = ProposalCancelledEvent;

/** Gets the encoder for {@link ProposalCancelledEventArgs} event data. */
export function getProposalCancelledEventEncoder(): FixedSizeEncoder<ProposalCancelledEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['agreementKey', fixEncoderSize(getBytesEncoder(), 32)]]), [getConstantEncoder(PROPOSAL_CANCELLED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link ProposalCancelledEvent} event data. */
export function getProposalCancelledEventDecoder(): FixedSizeDecoder<ProposalCancelledEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['agreementKey', fixDecoderSize(getBytesDecoder(), 32)]]), [getConstantDecoder(PROPOSAL_CANCELLED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link ProposalCancelledEvent} event data. */
export function getProposalCancelledEventCodec(): FixedSizeCodec<ProposalCancelledEventArgs, ProposalCancelledEvent> {
    return combineCodec(getProposalCancelledEventEncoder(), getProposalCancelledEventDecoder());
}

/** Parses the provided bytes into {@link ProposalCancelledEvent} event data. */
export function parseProposalCancelledEvent(data: ReadonlyUint8Array | Uint8Array): ProposalCancelledEvent {
    if (containsBytes(data, PROPOSAL_CANCELLED_EVENT_DISCRIMINATOR, 0)) { return getProposalCancelledEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "ProposalCancelledEvent" event discriminators.');
}