/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, containsBytes, fixEncoderSize, getAddressDecoder, getAddressEncoder, getBytesEncoder, getConstantDecoder, getConstantEncoder, getHiddenPrefixDecoder, getHiddenPrefixEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type ReadonlyUint8Array } from '@solana/kit';

export const SALE_SETTLED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([49, 60, 149, 181, 10, 243, 135, 56]);

export function getSaleSettledEventDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(SALE_SETTLED_EVENT_DISCRIMINATOR); }

export type SaleSettledEvent = { seller: Address; amount: bigint; toSeller: bigint;  };

export type SaleSettledEventArgs = { seller: Address; amount: number | bigint; toSeller: number | bigint;  };

/** Gets the encoder for {@link SaleSettledEventArgs} event data. */
export function getSaleSettledEventEncoder(): FixedSizeEncoder<SaleSettledEventArgs> {
    return getHiddenPrefixEncoder(getStructEncoder([['seller', getAddressEncoder()], ['amount', getU64Encoder()], ['toSeller', getU64Encoder()]]), [getConstantEncoder(SALE_SETTLED_EVENT_DISCRIMINATOR)]);
}

/** Gets the decoder for {@link SaleSettledEvent} event data. */
export function getSaleSettledEventDecoder(): FixedSizeDecoder<SaleSettledEvent> {
    return getHiddenPrefixDecoder(getStructDecoder([['seller', getAddressDecoder()], ['amount', getU64Decoder()], ['toSeller', getU64Decoder()]]), [getConstantDecoder(SALE_SETTLED_EVENT_DISCRIMINATOR)]);
}

/** Gets the codec for {@link SaleSettledEvent} event data. */
export function getSaleSettledEventCodec(): FixedSizeCodec<SaleSettledEventArgs, SaleSettledEvent> {
    return combineCodec(getSaleSettledEventEncoder(), getSaleSettledEventDecoder());
}

/** Parses the provided bytes into {@link SaleSettledEvent} event data. */
export function parseSaleSettledEvent(data: ReadonlyUint8Array | Uint8Array): SaleSettledEvent {
    if (containsBytes(data, SALE_SETTLED_EVENT_DISCRIMINATOR, 0)) { return getSaleSettledEventDecoder().decode(data); }
    throw new Error('The provided data does not match the "SaleSettledEvent" event discriminators.');
}