import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {State} from '../src/domain/models.ts';
import {createCommitment,createSale,receiveSale} from '../server/financial-service.ts';
import {decideAgreement,requestRenegotiation,decideRenegotiation,terms} from '../server/agreement-service.ts';
import {openCash,separateCash,payCash,outflowCash,closeCash} from '../server/cash-service.ts';
import {cashSummary,destinationStatus} from '../src/domain/cash.ts';
import {calculateDistribution,remaining,remainingToAllocate,summary,today,manualTrustSummary} from '../src/domain/finance.ts';
import {financialForecast} from '../src/domain/intelligence.ts';
import {memberSummary} from '../src/domain/team.ts';
import {createPlan} from '../server/planning-service.ts';
import {migrateState} from '../server/migration.ts';
function state(opening=10000):State{const s:State={schemaVersion:4,demo:false,sales:[],commitments:[],plans:[],members:[]};openCash(s,{opening});return s;}
function debt(s:State,original=10000,rateBps=2000){const c=createCommitment(s,{supplier:'João',debtAmount:original,rateBps,priority:1,due:today()});decideAgreement(s,{id:c.id,actor:'supplier',decision:'accept'});return c;}
function sale(s:State,amount=5000,method='cash',paidAt:string|null=today()){return createSale(s,{amount,method,soldAt:today(),paidAt});}
function supplierPayment(s:State,id:string,amount=1000,requestId=randomUUID()){return payCash(s,{kind:'supplier',recipientId:id,amount,requestId});}
function worker(s:State){s.members.push({id:'pedro',name:'Pedro',commissionBps:800,active:true});}
const commissionPayment=(s:State,amount:number)=>payCash(s,{kind:'commission',recipientId:'pedro',amount,requestId:randomUUID()});
test('caixa 01: abertura persiste saldo inicial e rejeita abertura simultânea',()=>{const s=state();assert.equal(cashSummary(s).expected,10000);assert.equal(s.cashMovements?.[0].type,'OPENING');assert.throws(()=>openCash(s,{opening:100}));assert.equal(s.cashSessions?.length,1);});
test('caixa 02: venda em dinheiro aumenta entradas e esperado uma única vez',()=>{const s=state();const v=sale(s);assert.equal(cashSummary(s).entries,5000);assert.equal(cashSummary(s).expected,15000);assert.equal(s.cashMovements?.filter(m=>m.reference===v.id).length,1);});
test('caixa 03: digital simulado não aumenta caixa físico e conserva baixa simulada',()=>{const s=state();const c=debt(s);sale(s,5000,'digital');assert.equal(cashSummary(s).expected,10000);assert.equal(cashSummary(s).entries,0);assert.equal(s.commitments[0].paid,1000);assert.equal(s.commitments[0].id,c.id);});
test('caixa 04: venda pendente entra no caixa somente no recebimento físico',()=>{const s=state();const v=sale(s,5000,'cash',null);assert.equal(cashSummary(s).entries,0);receiveSale(s,{id:v.id,paidAt:today()});assert.equal(cashSummary(s).entries,5000);assert.equal(cashSummary(s).expected,15000);assert.throws(()=>receiveSale(s,{id:v.id,paidAt:today()}));});
test('caixa 05: destinação física não é pagamento nem conclusão e limita novas destinações',()=>{const s=state();debt(s);sale(s);assert.equal(s.commitments[0].paid,0);assert.equal(s.commitments[0].cashPending,1000);assert.equal(remaining(s.commitments[0]),10000);sale(s,100000);assert.equal(s.commitments[0].cashPending,10000);assert.equal(remainingToAllocate(s.commitments[0]),0);assert.equal(s.commitments[0].status,'active');assert.equal(sale(s).distribution?.filter(e=>e.kind==='commitment').length,0);});
test('caixa 06: separado continua no caixa e mantém o comprometido pendente',()=>{const s=state();debt(s);sale(s);const before=cashSummary(s);separateCash(s,{destinationId:s.cashDestinations![0].id});assert.equal(destinationStatus(s.cashDestinations![0]),'SEPARADO');assert.equal(cashSummary(s).expected,before.expected);assert.equal(cashSummary(s).free,before.free);assert.equal(s.cashActions?.[0].confirmedBy,'local_operator');});
test('caixa 07: pagamento confirmado reduz caixa e dívida com valor, origem e operador',()=>{const s=state();const c=debt(s);sale(s);const p=supplierPayment(s,c.id);assert.equal(cashSummary(s).expected,14000);assert.equal(s.commitments[0].paid,1000);assert.equal(s.commitments[0].cashPending,0);assert.equal(summary(s).cashToSeparate,0);assert.equal(destinationStatus(s.cashDestinations![0]),'PAGO');assert.equal(p.origin,'cash');assert.equal(p.confirmedBy,'local_operator');assert.equal(s.cashMovements?.at(-1)?.reference,p.id);});
test('caixa 08: requisição duplicada e destinação já paga não podem gerar nova saída',()=>{const s=state();const c=debt(s);sale(s);const requestId=randomUUID();supplierPayment(s,c.id,1000,requestId);const before=structuredClone(s);assert.throws(()=>supplierPayment(s,c.id,1000,requestId));assert.throws(()=>supplierPayment(s,c.id,1));assert.deepEqual(s,before);});
test('caixa 09: fornecedor não pode receber mais que a pendência',()=>{const s=state();const c=debt(s);sale(s);const before=structuredClone(s);assert.throws(()=>supplierPayment(s,c.id,1001));assert.deepEqual(s,before);});
test('caixa 10: R$420 esperados menos R$170 pendentes resultam R$250 livres',()=>{const s=state(0);debt(s,17000,10000);sale(s,42000);assert.equal(cashSummary(s).expected,42000);assert.equal(cashSummary(s).committed,17000);assert.equal(cashSummary(s).free,25000);});
test('caixa 11: fechamento com contagem exata registra diferença zero',()=>{const s=state(42000);closeCash(s,{counted:42000});assert.equal(s.cashSessions![0].closure?.difference,0);});
test('caixa 12: fechamento com falta registra diferença negativa sem ajuste automático',()=>{const s=state(42000);closeCash(s,{counted:41500});assert.equal(s.cashSessions![0].closure?.difference,-500);assert.equal(s.cashMovements?.length,1);});
test('caixa 13: fechamento com sobra registra diferença positiva sem inventar venda',()=>{const s=state(42000);closeCash(s,{counted:42500});assert.equal(s.cashSessions![0].closure?.difference,500);assert.equal(s.sales.length,0);});
test('caixa 14: fechamento preserva vendas, comissões, acordos e pagamentos antigos',()=>{const s=state();worker(s);const c=debt(s);sale(s);supplierPayment(s,c.id);const before=structuredClone({sales:s.sales,commitments:s.commitments,payments:s.cashPayments,members:s.members});closeCash(s,{counted:cashSummary(s).expected});assert.deepEqual({sales:s.sales,commitments:s.commitments,payments:s.cashPayments,members:s.members},before);const closure=structuredClone(s.cashSessions![0]);assert.throws(()=>closeCash(s,{counted:0}));openCash(s,{opening:20000});outflowCash(s,{amount:100,description:'Retirada'});assert.deepEqual(s.cashSessions![0],closure);});
test('caixa 15: comissão gerada de Pedro é calculada pelas vendas recebidas',()=>{const s=state(0);worker(s);sale(s,105000);const r=memberSummary(s,'pedro');assert.equal(r.generated,8400);assert.equal(r.paid,0);assert.equal(r.receivable,8400);});
test('caixa 16: pagamento parcial de comissão reduz a receber sem mexer nas vendas',()=>{const s=state(0);worker(s);sale(s,100000);const before=structuredClone(s.sales);commissionPayment(s,4000);assert.equal(memberSummary(s,'pedro').paid,4000);assert.equal(memberSummary(s,'pedro').receivable,4000);assert.equal(cashSummary(s).expected,96000);assert.deepEqual(s.sales,before);});
test('caixa 17: pagamento total deixa comissão a receber em zero',()=>{const s=state(0);worker(s);sale(s,100000);commissionPayment(s,4000);commissionPayment(s,4000);assert.equal(memberSummary(s,'pedro').receivable,0);assert.equal(destinationStatus(s.cashDestinations![0]),'PAGO');assert.throws(()=>commissionPayment(s,1));});
test('caixa 18: comissão não pode ser paga acima do saldo a receber',()=>{const s=state();worker(s);sale(s);const before=structuredClone(s);assert.throws(()=>commissionPayment(s,401));assert.deepEqual(s,before);});
test('caixa 19: pagamento de comissão cria saída física com referência rastreável',()=>{const s=state();worker(s);const v=sale(s);const p=commissionPayment(s,400);assert.equal(s.cashMovements?.at(-1)?.type,'COMMISSION_PAYMENT');assert.equal(s.cashDestinations?.find(d=>d.id===p.allocations[0].destinationId)?.saleId,v.id);});
test('caixa 20: histórico da equipe explica cada venda e preserva porcentagem antiga',()=>{const s=state();worker(s);sale(s,10000);sale(s,20000);s.members[0].commissionBps=3000;sale(s,10000);const r=memberSummary(s,'pedro');assert.equal(r.generated,5400);assert.deepEqual(r.rows.map(r=>r.commission),[3000,1600,800]);assert.equal(r.rows.at(-1)?.sale.commissionBps,800);});
test('caixa 22: pagar não desconta duas vezes dívida, livre ou reserva pessoal',()=>{const s=state(0);const c=debt(s);sale(s);createPlan(s,{name:'Reserva contábil',target:10000,amount:1000,mode:'manual'});const global=summary(s);const physical=cashSummary(s).free;supplierPayment(s,c.id);assert.equal(s.commitments[0].paid,1000);assert.equal(remaining(s.commitments[0]),9000);assert.equal(summary(s).free,global.free);assert.equal(cashSummary(s).free,physical);assert.equal(cashSummary(s).free,4000);assert.equal(summary(s).free,3000);});
test('migração física reclassifica conclusão simulada sem perder vendas ou timeline',()=>{const old:State={schemaVersion:3,demo:false,members:[],plans:[],sales:[{id:'sale-old',amount:10000,soldAt:today(),paidAt:today(),method:'cash',participant:null,commissionBps:0,rules:['Regra antiga'],distribution:[{kind:'commitment',recipientId:'c',recipient:'João',amount:10000,rateBps:10000,mode:'to_separate',remainingAfter:0}]}],commitments:[{id:'c',supplier:'João',original:10000,paid:10000,rateBps:10000,priority:1,createdAt:today(),due:today(),status:'completed',completionSaleId:'sale-old',completedAt:today(),timeline:[{id:'old-event',type:'completed',at:today(),actor:'system'}]}]};const before=structuredClone(old);const m=migrateState(old);assert.equal(m.schemaVersion,4);assert.deepEqual(m.sales,before.sales);assert.equal(m.commitments[0].paid,0);assert.equal(m.commitments[0].cashPending,10000);assert.equal(m.commitments[0].status,'active');assert.equal(m.commitments[0].legacyCashReclassification?.completedAt,today());assert.deepEqual(m.commitments[0].timeline?.[0],before.commitments[0].timeline?.[0]);assert.equal(m.cashPayments?.length,0);assert.equal(manualTrustSummary(m).completed,0);assert.deepEqual(old,before);assert.deepEqual(migrateState(m),m);});
test('pagamento parcial de fornecedor mantém separado residual e consome origens em ordem',()=>{const s=state();const c=debt(s);const first=sale(s);const second=sale(s);separateCash(s,{destinationId:s.cashDestinations![0].id});const p=supplierPayment(s,c.id,500);const d=s.cashDestinations!.find(d=>d.saleId===first.id)!;assert.equal(d.paid,500);assert.equal(d.separated,500);assert.equal(destinationStatus(d),'SEPARADO');assert.equal(p.allocations.length,1);assert.equal(s.cashDestinations!.find(d=>d.saleId===second.id)?.paid,0);});
test('pagamento e saída exigem caixa aberto e não podem superar dinheiro disponível',()=>{const s=state(0);const c=debt(s);sale(s);closeCash(s,{counted:5000});assert.throws(()=>supplierPayment(s,c.id));openCash(s,{opening:500});assert.throws(()=>supplierPayment(s,c.id,1000));assert.throws(()=>outflowCash(s,{amount:100,description:'Retirada'}));});
test('livro fora de abertura é preservado sem dupla entrada ao contar saldo inicial',()=>{const s:State={schemaVersion:4,demo:false,sales:[],commitments:[],members:[],plans:[]};sale(s);assert.equal(s.cashMovements![0].sessionId,undefined);openCash(s,{opening:5000});assert.equal(cashSummary(s).expected,5000);assert.equal(cashSummary(s).entries,0);});
test('renegociação não pode apagar valores físicos já destinados',()=>{const s=state();const c=debt(s);sale(s);assert.throws(()=>requestRenegotiation(s,{id:c.id,actor:'seller',...terms(s.commitments[0]),original:999}));requestRenegotiation(s,{id:c.id,actor:'seller',...terms(s.commitments[0]),original:1500});sale(s);const active=s.commitments[0];assert.throws(()=>decideRenegotiation(s,{id:c.id,proposalId:active.renegotiations![0].id,actor:'supplier',decision:'accept'}));assert.equal(active.original,10000);});
test('conclusão física só aparece na confiança após confirmar último pagamento',()=>{const s=state();const c=debt(s,1000,10000);sale(s);assert.equal(manualTrustSummary(s).completed,0);supplierPayment(s,c.id,400);assert.equal(manualTrustSummary(s).completed,0);supplierPayment(s,c.id,600);assert.equal(manualTrustSummary(s).completed,1);assert.equal(manualTrustSummary(s).confirmed,1000);assert.equal(s.commitments[0].status,'completed');});
test('domínio puro também distingue dinheiro destinado de dívida paga',()=>{const s=state();const c=debt(s);const result=calculateDistribution({id:'pure',amount:5000,soldAt:today(),paidAt:today(),method:'cash',participant:null,commissionBps:0,rules:[],commitmentRules:[{commitmentId:c.id,supplier:c.supplier,rateBps:c.rateBps,priority:1,createdAt:c.createdAt}]},s.commitments);assert.equal(result.commitments[0].paid,0);assert.equal(result.commitments[0].cashPending,1000);assert.equal(result.entries[0].remainingAfter,10000);assert.equal(result.entries[0].allocationRemainingAfter,9000);assert.equal(s.commitments[0].cashPending,undefined);});
test('acordo com parcela digital simulada não ganha indicador de conclusão física integral',()=>{const s=state();const c=debt(s,1000,10000);sale(s,500,'digital');sale(s,500);supplierPayment(s,c.id,500);assert.equal(s.commitments[0].paid,1000);assert.equal(s.commitments[0].simulatedPaid,500);assert.equal(manualTrustSummary(s).completed,0);});
test('projeção não pede reservar novamente dinheiro já destinado no caixa',()=>{const s=state();const c=debt(s,1000,10000);sale(s);s.commitments[0].due='2099-01-01';const f=financialForecast(s)[0];assert.equal(f.remaining,1000);assert.equal(f.pendingCash,1000);assert.equal(f.toAllocate,0);assert.equal(f.neededBps,0);assert.equal(s.commitments[0].paid,0);assert.equal(s.commitments[0].id,c.id);});
test('saída manual identifica retirada, preserva terceiros e rejeita repetição do pedido',()=>{const s=state();const c=debt(s);sale(s);const original=structuredClone(s.sales);const requestId=randomUUID();outflowCash(s,{amount:1000,description:'Retirada do titular',requestId});assert.equal(cashSummary(s).expected,14000);assert.equal(s.commitments[0].paid,0);assert.equal(s.commitments[0].id,c.id);assert.deepEqual(s.sales,original);const before=structuredClone(s);assert.throws(()=>outflowCash(s,{amount:1000,description:'Retirada do titular',requestId}));assert.deepEqual(s,before);});
test('caixa não admite recebimento físico futuro como entrada efetiva',()=>{const s=state();assert.throws(()=>sale(s,5000,'cash','2099-01-01'));const pending=sale(s,5000,'cash',null);const before=structuredClone(s);assert.throws(()=>receiveSale(s,{id:pending.id,paidAt:'2099-01-01'}));assert.deepEqual(s,before);assert.equal(cashSummary(s).entries,0);});
test('comissão digital paga em dinheiro não pode consumir reserva física de outro destinatário',()=>{const s=state(0);debt(s,1000,10000);sale(s,1000);worker(s);sale(s,10000,'digital');const before=structuredClone(s);assert.throws(()=>commissionPayment(s,100));assert.deepEqual(s,before);});
