import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {State} from '../src/domain/models.ts';
import {allocation,calculateDistribution,summary,today,trustSummary} from '../src/domain/finance.ts';
import {createCommitment,createSale,receiveSale} from '../server/financial-service.ts';
import {decideAgreement} from '../server/agreement-service.ts';
import {migrateState} from '../server/migration.ts';
import {parseMoney,validDate} from '../src/domain/validation.ts';

import {confirmSuppliers} from './cash-fixture.ts';
const date=today();
function state(active=false):State{return {schemaVersion:2,demo:false,sales:[],plans:[],commitments:[],members:[{id:'pedro',name:'Pedro',commissionBps:800,active}]};}
function commitment(s:State,rest=10000,percent=2000,priority=1,supplier='Fornecedor João'){
 const c=createCommitment(s,{supplier,original:10000,remaining:rest,rateBps:percent,priority,due:'2099-12-31'});
 decideAgreement(s,{id:c.id,actor:'supplier',decision:'accept'});return c;
}
function sell(s:State,amount=5000,paidAt:string|null=date,method='cash'){
 return createSale(s,{amount,soldAt:date,paidAt,method});
}

test('venda sem compromisso fica integralmente livre',()=>{const s=state();const sale=sell(s);assert.deepEqual(sale.distribution?.map(e=>[e.kind,e.amount]),[['seller',5000]]);assert.equal(summary(s).free,5000);});
test('venda física destina percentual do bruto e só o pagamento confirmado reduz a dívida',()=>{const s=state();const c=commitment(s);sell(s);assert.equal(s.commitments[0].paid,0);assert.equal(s.commitments[0].cashPending,1000);confirmSuppliers(s);assert.equal(s.commitments.find(v=>v.id===c.id)?.paid,1000);assert.equal(summary(s).free,4000);});
test('venda com comissão registra percentual e valor de Pedro',()=>{const s=state(true);const sale=sell(s);assert.equal(sale.participant,'Pedro');assert.equal(sale.commissionBps,800);assert.equal(sale.distribution?.find(e=>e.kind==='commission')?.amount,400);assert.equal(summary(s).free,4600);});
test('exemplo R$50: João R$10, Pedro R$4 e Maria R$36',()=>{const s=state(true);commitment(s);const sale=sell(s);assert.deepEqual(sale.distribution?.map(e=>[e.recipient,e.amount]),[['Pedro',400],['Fornecedor João',1000],['Maria',3600]]);confirmSuppliers(s);assert.equal(s.commitments[0].original-s.commitments[0].paid,9000);assert.equal(summary(s).committed,1400);assert.equal(summary(s).free,3600);});
test('última amortização destina só R$3 quando o percentual calcularia R$10',()=>{const s=state();commitment(s,300);const sale=sell(s);assert.equal(sale.distribution?.find(e=>e.kind==='commitment')?.amount,300);confirmSuppliers(s);assert.equal(s.commitments[0].paid,10000);assert.equal(summary(s).free,4700);});
test('confirmação do último pagamento físico registra data e venda de origem',()=>{const s=state();commitment(s,300);const sale=sell(s);confirmSuppliers(s);assert.equal(s.commitments[0].status,'completed');assert.equal(s.commitments[0].completedAt,date);assert.equal(s.commitments[0].completionSaleId,sale.id);});
test('venda posterior à conclusão não desconta para o fornecedor',()=>{const s=state();commitment(s,300);sell(s);confirmSuppliers(s);const subsequent=sell(s);assert.equal(subsequent.distribution?.filter(e=>e.kind==='commitment').length,0);assert.equal(s.commitments[0].paid,10000);});
test('Pedro fora do turno não recebe comissão',()=>{const s=state(false);const sale=sell(s);assert.equal(sale.participant,null);assert.equal(sale.distribution?.filter(e=>e.kind==='commission').length,0);});
test('Pedro no turno recebe comissão e encerramento só afeta novas vendas',()=>{const s=state(true);const first=sell(s);s.members[0].active=false;const second=sell(s);assert.equal(first.distribution?.[0].amount,400);assert.equal(second.participant,null);assert.equal(summary(s).commission,400);});
test('venda pendente mantém Pedro ao receber depois do fim do turno',()=>{const s=state(true);const originalDate='2000-01-01';const c=commitment(s);c.createdAt=originalDate;const sale=createSale(s,{amount:5000,method:'cash',soldAt:originalDate,paidAt:null});assert.equal(summary(s).total,0);assert.equal(s.commitments[0].paid,0);s.members[0].active=false;receiveSale(s,{id:sale.id,paidAt:date});assert.equal(sale.participant,'Pedro');assert.equal(sale.distribution?.[0].amount,400);confirmSuppliers(s);assert.equal(s.commitments[0].paid,1000);assert.equal(summary(s).free,3600);assert.equal(sale.soldAt,originalDate);assert.equal(sale.paidAt,date);});
test('recebimento duplicado não amortiza novamente',()=>{const s=state();commitment(s);const sale=sell(s,5000,null);receiveSale(s,{id:sale.id,paidAt:date});assert.throws(()=>receiveSale(s,{id:sale.id,paidAt:date}),/já foi registrado/);confirmSuppliers(s);assert.equal(s.commitments[0].paid,1000);});
test('compromisso criado após venda pendente não altera suas regras',()=>{const s=state();const sale=sell(s,5000,null);commitment(s);receiveSale(s,{id:sale.id,paidAt:date});assert.equal(s.commitments[0].paid,0);assert.equal(sale.distribution?.at(-1)?.amount,5000);});
test('venda pendente não paga compromisso já concluído por outra venda',()=>{const s=state();commitment(s,300);const pending=sell(s,5000,null);sell(s);confirmSuppliers(s);receiveSale(s,{id:pending.id,paidAt:date});assert.equal(s.commitments[0].paid,10000);assert.equal(pending.distribution?.filter(e=>e.kind==='commitment').length,0);});
test('prioridade limita distribuição excedente sem dinheiro negativo',()=>{const s=state(true);const low=commitment(s,10000,8000,2,'B');assert.throws(()=>commitment(s,10000,8000,1,'A'),/168%/);const high={...structuredClone(low),id:'legacy-high',supplier:'A',priority:1};s.commitments.push(high);const sale:import('../src/domain/models.ts').Sale={id:'legacy-sale',amount:5000,soldAt:date,paidAt:date,method:'cash' as const,participant:'Pedro',commissionBps:800,rules:[],commitmentRules:s.commitments.map(c=>({commitmentId:c.id,supplier:c.supplier,rateBps:c.rateBps,priority:c.priority,createdAt:c.createdAt}))};const result=calculateDistribution(sale,s.commitments);s.commitments=result.commitments;Object.assign(sale,{distribution:result.entries});s.sales.push(sale);assert.deepEqual(sale.distribution?.map(e=>e.amount),[400,4000,600,0]);assert.equal(s.commitments.find(c=>c.id===high.id)?.cashPending,4000);assert.equal(s.commitments.find(c=>c.id===low.id)?.cashPending,600);assert.equal(sale.distribution?.reduce((a,e)=>a+e.amount,0),5000);});
test('planejamento é separado de obrigações e não amortiza dívida',()=>{const s=state();s.plans=[{id:'reserve',name:'Reserva pessoal',amount:1500}];commitment(s);sell(s);const totals=summary(s);assert.equal(totals.committed,1000);assert.equal(totals.planned,1500);assert.equal(totals.free,2500);confirmSuppliers(s);assert.equal(s.commitments[0].paid,1000);});
test('dinheiro físico calcula valor a separar, sem transferência',()=>{const s=state(true);commitment(s);const sale=sell(s);assert.ok(sale.distribution?.filter(e=>e.kind!=='seller').every(e=>e.mode==='to_separate'));assert.equal(summary(s).cashToSeparate,1400);});
test('digital usa o mesmo motor com distribuição marcada como simulada',()=>{const s=state(true);commitment(s);const sale=sell(s,5000,date,'digital');assert.ok(sale.distribution?.filter(e=>e.kind!=='seller').every(e=>e.mode==='simulated'));assert.equal(summary(s).free,3600);assert.equal(summary(s).cashTotal,0);});
test('GIRO Confiança só considera concluídos pelo motor, sem exemplos',()=>{const s=state();commitment(s);assert.equal(trustSummary(s).completed,0);sell(s,50000);confirmSuppliers(s);assert.equal(trustSummary(s).completed,1);commitment(s);assert.equal(trustSummary(s).completed,1);const completed=s.commitments.find(c=>c.status==='completed')!;completed.demo=true;assert.equal(trustSummary(s).completed,0);completed.demo=false;completed.status='cancelled';assert.equal(trustSummary(s).completed,0);});
test('indicadores de confiança contam prazo, fornecedores e recorrência',()=>{const s=state();const first=commitment(s,300);first.due='2000-01-01';sell(s);confirmSuppliers(s);const second=commitment(s,300,2000,1,' fornecedor JOÃO ');sell(s);confirmSuppliers(s);commitment(s,300,2000,1,'Fornecedor Ana');sell(s);confirmSuppliers(s);const trust=trustSummary(s);assert.deepEqual(trust,{completed:3,suppliers:2,liquidated:30000,onTime:2,recurring:1});});
test('cadastro de saldo já zerado não fabrica confiança',()=>{const s=state();const c=commitment(s,0);assert.equal(c.status,'completed');assert.equal(trustSummary(s).completed,0);});
test('compromisso cancelado não participa da distribuição',()=>{const s=state();commitment(s);s.commitments[0].status='cancelled';const sale=sell(s);assert.equal(sale.distribution?.at(-1)?.amount,5000);assert.equal(s.commitments[0].paid,0);});
test('migração preserva vendas e comissões sem amortização retroativa',()=>{const old=state();delete old.schemaVersion;old.demo=true;old.commitments=[{id:'joao',supplier:'João exemplo',original:60000,paid:22000,rateBps:2000,priority:1,createdAt:date,due:date,status:'accepted'}];old.sales=[{id:'old-real',amount:5000,soldAt:date,paidAt:date,method:'cash',participant:'Pedro',commissionBps:800,rules:['Turno de Pedro']},{id:'demo-sale',amount:85000,soldAt:date,paidAt:date,method:'cash',participant:null,commissionBps:0,rules:[]}];old.plans=[{id:'stock',name:'Estoque exemplo',amount:35000}];const migrated=migrateState(old);assert.equal(migrated.sales.length,2);assert.equal(migrated.commitments[0].paid,22000);assert.equal(migrated.sales[0].distribution?.[0].amount,400);assert.equal(summary(migrated).free,4600);assert.equal(trustSummary(migrated).completed,0);assert.deepEqual(migrateState(migrated),migrated);assert.equal(old.commitments[0].status,'accepted');});
test('validação rejeita datas inexistentes, restante e percentuais inválidos',()=>{const s=state();assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2026-13-01'),false);assert.throws(()=>createCommitment(s,{supplier:'João',original:100,remaining:200,rateBps:2000,priority:1,due:date}));assert.throws(()=>commitment(s,100,10001));assert.throws(()=>createSale(s,{amount:5000,soldAt:date,paidAt:date,method:'pix'}));assert.throws(()=>createCommitment(s,{supplier:'João',original:100,remaining:100,rateBps:2000,priority:1,due:date,status:'cancelled'}));assert.equal(s.sales.length,0);assert.equal(s.commitments.length,0);});
test('centavos são exatos e a sobra de arredondamento fica com o vendedor',()=>{const s=state(true);commitment(s);const sale=sell(s,101);assert.deepEqual(sale.distribution?.map(e=>e.amount),[8,20,73]);assert.equal(parseMoney('35,50'),3550);assert.equal(allocation(Number.MAX_SAFE_INTEGER,10000,Number.MAX_SAFE_INTEGER),Number.MAX_SAFE_INTEGER);});
test('conclusão fora de ordem usa a maior data dos pagamentos do acordo',()=>{const s=state();const c=commitment(s,2000);c.due='2090-01-01';sell(s,5000,'2099-01-01','digital');sell(s,5000,date,'digital');assert.equal(s.commitments[0].completedAt,'2099-01-01');assert.equal(trustSummary(s).onTime,0);});
