import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtemp,unlink,rmdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {today} from '../src/domain/finance.ts';
test('lacunas API: consulta por ID, mudança, recusa e aceite persistem sem sobrescrever termos',{timeout:30000},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'giro-lacunas-'));let child:ChildProcess|undefined;
 const start=async()=>{child=spawn(process.execPath,['--experimental-strip-types','server/index.ts'],{env:{...process.env,GIRO_DATA_DIR:directory,GIRO_PORT:'3016'},stdio:['ignore','pipe','pipe']});const running=child;await new Promise<void>((ok,fail)=>{const timer=setTimeout(()=>{running.kill();fail(Error('API não iniciou'));},8000);running.stdout?.once('data',()=>{clearTimeout(timer);ok();});running.once('error',e=>{clearTimeout(timer);fail(e);});});};
 const stop=async()=>{if(!child||child.exitCode!==null||child.signalCode!==null)return;const ended=new Promise<void>(ok=>child!.once('exit',()=>ok()));child.kill();await ended;};
 const call=async(path:string,input?:unknown)=>{const r=await fetch('http://127.0.0.1:3016/api/'+path,input===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});return {status:r.status,data:await r.json()};};
 try{await start();const contact=(await call('contacts',{name:'Ana',type:'collaborator'})).data.contacts[0];await call('invitations/send',{contactId:contact.id,debtAmount:10000,rateBps:1000,priority:1,due:today(),acknowledged:true});let s=(await call('state')).data;const i=s.invitations[0],c=s.commitments.find((c:{id:string})=>c.id===i.commitmentId);await call('invitations/decision',{token:i.token,decision:'accept',acknowledged:true});const consulted=await call('commitments/consult',{id:c.publicId});assert.equal(consulted.status,200);assert.equal('token' in consulted.data,false);assert.equal('sales' in consulted.data,false);const proposal={id:c.publicId,original:c.original,rateBps:c.rateBps,priority:c.priority,due:c.due,paymentMethod:'Dinheiro em duas parcelas',acknowledged:true,reason:'Condição proposta pela outra parte'};assert.equal((await call('commitments/request-change',proposal)).status,200);s=(await call('state')).data;let actual=s.commitments.find((n:{id:string})=>n.id===c.id);assert.equal(actual.paymentMethod,undefined);const before=structuredClone(s);assert.equal((await call('commitments/request-change',proposal)).status,400);assert.deepEqual((await call('state')).data,before);await call('renegotiations/decision',{id:c.id,proposalId:actual.renegotiations[0].id,actor:'seller',decision:'refuse'});assert.equal((await call('commitments/consult',{id:c.publicId})).data.changes[0].status,'refused');assert.equal((await call('commitments/request-change',{...proposal,paymentMethod:'Dinheiro à vista'})).status,200);s=(await call('state')).data;actual=s.commitments.find((n:{id:string})=>n.id===c.id);await call('renegotiations/decision',{id:c.id,proposalId:actual.renegotiations.at(-1).id,actor:'seller',decision:'accept'});const final=(await call('state')).data;await stop();await start();assert.deepEqual((await call('state')).data,final);const v=(await call('commitments/consult',{id:c.publicId})).data;assert.equal(v.currentTerms.paymentMethod,'Dinheiro à vista');assert.deepEqual(v.changes.map((r:{status:string})=>r.status),['refused','accepted']);assert.equal((await call('commitments/consult',{id:'COMP-inexistente'})).status,400);
 }finally{await stop();await unlink(join(directory,'giro.sqlite'));await rmdir(directory);}
});
