import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {Commitment,State} from '../src/domain/models.ts';
import {summary,today,trustSummary} from '../src/domain/finance.ts';
import {educationalSimulation} from '../src/domain/planning.ts';
import {financialForecast,shiftDate} from '../src/domain/intelligence.ts';
import {createCommitment,createSale,receiveSale} from '../server/financial-service.ts';
import {decideAgreement,decideRenegotiation,editDraft,requestRenegotiation,submitDraft,terms} from '../server/agreement-service.ts';
import {changePlan,createPlan,reserveSuggestion,updateSettings} from '../server/planning-service.ts';
import {migrateState} from '../server/migration.ts';
import {confirmSuppliers} from './cash-fixture.ts';
const date=today();
function state():State{return {schemaVersion:3,demo:false,sales:[],plans:[],commitments:[],members:[],settings:{minimumWeeklyFree:0}};}
function agreement(s:State,extra:Record<string,unknown>={},accept=true){const c=createCommitment(s,{supplier:'João',debtAmount:60000,rateBps:3000,priority:1,due:shiftDate(date,5),...extra});if(accept)decideAgreement(s,{id:c.id,actor:'supplier',decision:'accept'});return c;}
function sale(s:State,amount=5000,paidAt:string|null=date){return createSale(s,{amount,method:'cash',soldAt:date,paidAt});}
function history(s:State,amount=20000){for(let i=0;i<7;i++)s.sales.push({id:'income-'+i,amount,method:'cash',soldAt:shiftDate(date,-i),paidAt:shiftDate(date,-i),participant:null,commissionBps:0,rules:[],demo:false});}
function plan(s:State,extra:Record<string,unknown>={}){return createPlan(s,{name:'Novo estoque',target:100000,amount:0,mode:'manual',...extra});}
function proposal(s:State,c:Commitment,extra:Record<string,unknown>={}){requestRenegotiation(s,{id:c.id,actor:'seller',...terms(c),rateBps:5000,reason:'Ajustar ao ritmo de vendas',...extra});return c.renegotiations!.at(-1)!;}

test('dívida nova precisa apenas do valor e começa com original igual ao restante',()=>{const s=state();const c=agreement(s,{},false);assert.equal(c.original,60000);assert.equal(c.paid,0);assert.equal(c.original-c.paid,60000);assert.equal(c.status,'awaiting_acceptance');});
test('dívida de R$600 com R$150 já pagos deixa R$450 restantes',()=>{const s=state();const c=agreement(s,{alreadyPaid:15000},false);assert.equal(c.original,60000);assert.equal(c.paid,15000);assert.equal(c.original-c.paid,45000);});
for(const [bps,destination] of [[1000,800],[2000,1600],[3000,2400]])test(`simulação educativa de ${bps/100}% não grava venda nem muda o estado`,()=>{const s=state();agreement(s);const before=structuredClone(s);assert.deepEqual(educationalSimulation(8000,bps),{destination,available:8000-destination});assert.deepEqual(s,before);});
test('simulação educativa também respeita a dívida restante',()=>assert.deepEqual(educationalSimulation(5000,2000,300),{destination:300,available:4700}));
test('criação de caixinha preserva meta, reservado, prioridade, data e regra',()=>{const s=state();sale(s,50000);const p=plan(s,{amount:30000,priority:2,targetDate:date,mode:'suggested',rateBps:1000});assert.equal(p.target,100000);assert.equal(p.amount,30000);assert.equal(p.priority,2);assert.equal(p.mode,'suggested');assert.equal(p.status,'active');assert.equal(s.commitments.length,0);});
test('caixinha pode ser editada sem gerar compromisso',()=>{const s=state();sale(s,50000);const p=plan(s);changePlan(s,{id:p.id,action:'edit',name:'Reserva',target:50000,amount:20000,priority:3,targetDate:null,mode:'suggested',rateBps:2000});assert.equal(p.name,'Reserva');assert.equal(p.amount,20000);assert.equal(p.rateBps,2000);assert.equal(s.commitments.length,0);});
test('pausa mantém reservado e interrompe novas sugestões',()=>{const s=state();sale(s,50000);const p=plan(s,{amount:10000,mode:'suggested',rateBps:1000});changePlan(s,{id:p.id,action:'pause'});assert.equal(p.status,'paused');assert.equal(summary(s).planned,10000);assert.deepEqual(sale(s).planningSuggestions,[]);changePlan(s,{id:p.id,action:'resume'});assert.equal(sale(s).planningSuggestions?.length,1);});
test('excluir caixinha libera saldo pessoal sem modificar receita ou acordo',()=>{const s=state();agreement(s);sale(s,50000);const p=plan(s,{amount:10000});const before=structuredClone(s.commitments);const free=summary(s).free;changePlan(s,{id:p.id,action:'delete'});assert.equal(s.plans.length,0);assert.deepEqual(s.commitments,before);assert.equal(summary(s).free,free+10000);});
test('planejamento pessoal não vira dívida ou regra obrigatória',()=>{const s=state();const p=plan(s,{mode:'suggested',rateBps:1000});const received=sale(s);assert.equal(p.amount,0);assert.equal(summary(s).committed,0);assert.equal(summary(s).free,5000);assert.equal(received.planningSuggestions?.[0].amount,500);assert.equal(s.commitments.length,0);});
test('sugestão só reserva após confirmação e não pode ser confirmada duas vezes',()=>{const s=state();const p=plan(s,{mode:'suggested',rateBps:1000});const received=sale(s);reserveSuggestion(s,{planId:p.id,saleId:received.id});assert.equal(p.amount,500);assert.equal(summary(s).planned,500);assert.equal(summary(s).free,4500);assert.throws(()=>reserveSuggestion(s,{planId:p.id,saleId:received.id}));});
test('confirmação de sugestões respeita meta e saldo livre atual',()=>{const s=state();const p=plan(s,{target:300,mode:'suggested',rateBps:2000});const first=sale(s);const second=sale(s);reserveSuggestion(s,{planId:p.id,saleId:first.id});assert.equal(p.amount,300);assert.equal(p.status,'completed');assert.throws(()=>reserveSuggestion(s,{planId:p.id,saleId:second.id}));assert.equal(summary(s).planned,300);});
test('reservas legadas acima do saldo ficam explícitas sem livre negativo',()=>{const s=state();sale(s,1000);const p=plan(s);p.amount=30000;const total=summary(s);assert.equal(total.plannedRequested,30000);assert.equal(total.planned,1000);assert.equal(total.free,0);});
test('projeção: R$200/dia por 5 dias estima R$1000',()=>{const s=state();agreement(s);history(s);const [f]=financialForecast(s,date);assert.equal(f.averageDaily,20000);assert.equal(f.projectedRevenue,100000);assert.equal(f.currentAllocation,30000);assert.equal(f.shortfall,30000);});
test('projeção exclui demonstrações, vendas pendentes e recebimentos futuros',()=>{const s=state();agreement(s);history(s);s.sales.push({id:'demo',amount:999999,method:'cash',soldAt:date,paidAt:date,participant:null,commissionBps:0,rules:[],demo:true},{id:'pending',amount:999999,method:'cash',soldAt:date,paidAt:null,participant:null,commissionBps:0,rules:[]},{id:'future',amount:999999,method:'cash',soldAt:date,paidAt:shiftDate(date,1),participant:null,commissionBps:0,rules:[]});assert.equal(financialForecast(s,date)[0].recentRevenue,140000);});
test('dias sem vendas entram no denominador e a projeção não altera o estado',()=>{const s=state();agreement(s);sale(s,7000);const before=structuredClone(s);assert.equal(financialForecast(s,date)[0].averageDaily,1000);assert.deepEqual(s,before);});
test('compromisso em risco identifica falta de R$300 e sugere 60%',()=>{const s=state();agreement(s);history(s);const [f]=financialForecast(s,date);assert.equal(f.classification,'RISCO DE NÃO QUITAÇÃO');assert.equal(f.neededBps,6000);assert.equal(f.feasible,true);});
test('percentual necessário maior que 100% indica impossibilidade',()=>{const s=state();agreement(s,{debtAmount:120000});history(s);const [f]=financialForecast(s,date);assert.equal(f.neededBps,12000);assert.equal(f.feasible,false);});
test('mínimo semanal é preservado proporcionalmente na sugestão',()=>{const s=state();agreement(s,{debtAmount:80000});history(s);updateSettings(s,{minimumWeeklyFree:42000});const [f]=financialForecast(s,date);assert.equal(f.minimumPreserved,30000);assert.equal(f.availableCapacity,70000);assert.equal(f.feasible,false);assert.equal(s.commitments[0].rateBps,3000);});
test('caixinhas sugeridas e outras dívidas prioritárias reduzem capacidade',()=>{const s=state();const c=agreement(s,{supplier:'A',priority:1,debtAmount:20000});agreement(s,{supplier:'B',priority:2,debtAmount:50000});plan(s,{mode:'suggested',rateBps:1000});history(s);const f=financialForecast(s,date).find(f=>f.id!==c.id)!;assert.equal(f.otherObligations,20000);assert.equal(f.plannedBuffer,10000);assert.equal(f.availableCapacity,70000);});
test('sem receita recente sinaliza atenção sem percentual inventado',()=>{const s=state();agreement(s);const [f]=financialForecast(s,date);assert.equal(f.noHistory,true);assert.equal(f.neededBps,null);assert.equal(f.classification,'ATENÇÃO');});
test('classificações determinísticas em dia, atenção e risco vencido',()=>{const s=state();const c=agreement(s,{rateBps:6000});history(s);assert.equal(financialForecast(s,date)[0].classification,'EM DIA');c.rateBps=5000;assert.equal(financialForecast(s,date)[0].classification,'ATENÇÃO');c.due=date;assert.equal(financialForecast(s,date)[0].classification,'RISCO DE NÃO QUITAÇÃO');});
test('aguardando aceite não recebe amortização nem aparece nas projeções',()=>{const s=state();const c=agreement(s,{},false);const received=sale(s);assert.equal(c.paid,0);assert.equal(received.commitmentRules?.length,0);assert.equal(financialForecast(s,date).length,0);});
test('aceite do fornecedor completa os dois lados e ativa o compromisso',()=>{const s=state();const c=agreement(s,{},false);assert.ok(c.sellerAcceptedAt);assert.equal(c.supplierAcceptedAt,undefined);decideAgreement(s,{id:c.id,actor:'supplier',decision:'accept'});assert.equal(c.status,'active');assert.ok(c.supplierAcceptedAt);sale(s);confirmSuppliers(s);assert.equal(s.commitments[0].paid,1500);});
test('uma parte não consegue aceitar por si nem editar compromisso ativo',()=>{const s=state();const c=agreement(s,{},false);assert.throws(()=>decideAgreement(s,{id:c.id,actor:'seller',decision:'accept'}));decideAgreement(s,{id:c.id,actor:'supplier',decision:'accept'});const before=structuredClone(c);assert.throws(()=>editDraft(s,{id:c.id,actor:'seller',...terms(c),rateBps:9000}));assert.deepEqual(c,before);});
test('rascunho pode ser editado e enviado; proposta recusada fica cancelada',()=>{const s=state();const c=agreement(s,{status:'draft'},false);assert.equal(c.status,'draft');editDraft(s,{id:c.id,actor:'seller',...terms(c),rateBps:2000});submitDraft(s,{id:c.id,actor:'seller'});assert.equal(c.status,'awaiting_acceptance');decideAgreement(s,{id:c.id,actor:'supplier',decision:'refuse'});assert.equal(c.status,'cancelled');assert.equal(sale(s).commitmentRules?.length,0);});
test('solicitar renegociação não altera o acordo vigente',()=>{const s=state();const c=agreement(s);const before=terms(c);const r=proposal(s,c);assert.equal(r.status,'pending');assert.deepEqual(terms(c),before);assert.equal(r.sellerAcceptedAt!==undefined,true);assert.equal(r.supplierAcceptedAt,undefined);assert.equal(c.timeline?.at(-1)?.type,'renegotiation_requested');});
test('renegociação recusada mantém regra anterior e histórico',()=>{const s=state();const c=agreement(s);const r=proposal(s,c);decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'supplier',decision:'refuse'});assert.equal(c.rateBps,3000);assert.equal(r.status,'refused');assert.equal(c.timeline?.at(-1)?.type,'renegotiation_refused');});
test('renegociação aceita muda somente após consentimento da outra parte',()=>{const s=state();const c=agreement(s);const r=proposal(s,c);assert.throws(()=>decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'seller',decision:'accept'}));decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'supplier',decision:'accept'});assert.equal(c.rateBps,5000);assert.equal(c.version,2);assert.ok(r.sellerAcceptedAt);assert.ok(r.supplierAcceptedAt);assert.equal(c.timeline?.at(-1)?.previous?.rateBps,3000);assert.equal(c.timeline?.at(-1)?.next?.rateBps,5000);});
test('fornecedor também pode propor e vendedor decidir',()=>{const s=state();const c=agreement(s);const r=proposal(s,c,{actor:'supplier'});decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'seller',decision:'accept'});assert.equal(c.rateBps,5000);assert.ok(r.sellerAcceptedAt);assert.ok(r.supplierAcceptedAt);});
test('regra anterior permanece em vendas pendentes após renegociação',()=>{const s=state();const c=agreement(s,{rateBps:2000});const pending=sale(s,5000,null);const r=proposal(s,c,{rateBps:6000});decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'supplier',decision:'accept'});receiveSale(s,{id:pending.id,paidAt:date});assert.equal(pending.distribution?.find(e=>e.kind==='commitment')?.amount,1000);const next=sale(s);assert.equal(next.distribution?.find(e=>e.kind==='commitment')?.amount,3000);assert.equal(pending.commitmentRules?.[0].version,1);assert.equal(next.commitmentRules?.[0].version,2);});
test('histórico preserva prazo original e confiança usa o acordo vigente',()=>{const s=state();const c=agreement(s,{due:shiftDate(date,-1),rateBps:2000});const oldDue=c.due;const r=proposal(s,c,{due:shiftDate(date,5),rateBps:10000});decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'supplier',decision:'accept'});sale(s,60000);confirmSuppliers(s);const completed=s.commitments[0];assert.equal(completed.status,'completed');assert.equal(completed.originalDue,oldDue);assert.equal(completed.finalDue,shiftDate(date,5));assert.equal(completed.completionTerms?.due,shiftDate(date,5));assert.equal(trustSummary(s).completed,1);assert.equal(trustSummary(s).onTime,1);assert.equal(completed.timeline?.at(-1)?.type,'completed');assert.ok(completed.timeline?.some(e=>e.type==='renegotiation_accepted'));assert.throws(()=>requestRenegotiation(s,{id:c.id,actor:'seller',...terms(completed),rateBps:5000}));assert.equal(trustSummary(s).completed,1);});
test('saldo que muda entre pedido e aceite impede renegociação que fabricaria quitação',()=>{const s=state();const c=agreement(s);const r=proposal(s,c,{original:5000});sale(s,20000);confirmSuppliers(s);const active=s.commitments[0];assert.equal(active.paid,6000);assert.throws(()=>decideRenegotiation(s,{id:c.id,proposalId:r.id,actor:'supplier',decision:'accept'}));assert.equal(active.rateBps,3000);});
test('migração da Fase 2 preserva saldo e históricos sem inventar aceites',()=>{const s=state();const c=agreement(s);sale(s);confirmSuppliers(s);s.schemaVersion=2;const source=s.commitments[0];delete source.timeline;delete source.sellerAcceptedAt;delete source.supplierAcceptedAt;delete source.legacyAcceptance;const result=migrateState(s);assert.equal(result.schemaVersion,4);assert.equal(result.commitments[0].paid,1500);assert.equal(result.commitments[0].status,'active');assert.equal(result.commitments[0].supplierAcceptedAt,undefined);assert.equal(result.commitments[0].legacyAcceptance,true);assert.equal(result.commitments[0].timeline?.at(-1)?.type,'legacy_imported');assert.equal(result.commitments[0].timeline?.[0].type,'amortized');assert.deepEqual(migrateState(result),result);assert.equal(c.original,60000);});
test('quitação encerra proposta pendente sem fingir aceite ou recusa',()=>{const s=state();const c=agreement(s);proposal(s,c);sale(s,200000);confirmSuppliers(s);const completed=s.commitments[0];assert.equal(completed.status,'completed');assert.equal(completed.renegotiations?.[0].status,'obsolete');assert.equal(completed.renegotiations?.[0].supplierAcceptedAt,undefined);assert.equal(completed.rateBps,3000);assert.ok(completed.timeline?.some(e=>e.type==='renegotiation_closed'));assert.equal(trustSummary(s).completed,1);});
