/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export const CashStatus = { 0: 'Pending', 1: 'Confirmed', 2: 'Disputed', Pending: 0, Confirmed: 1, Disputed: 2 } as const;

export type CashStatus = (typeof CashStatus)[Exclude<keyof typeof CashStatus, number>];

export type CashStatusArgs = CashStatus;

export function getCashStatusEncoder(): FixedSizeEncoder<CashStatusArgs> {
    return getEnumEncoder(CashStatus);
}

export function getCashStatusDecoder(): FixedSizeDecoder<CashStatus> {
    return getEnumDecoder(CashStatus as Omit<typeof CashStatus, number>);
}

export function getCashStatusCodec(): FixedSizeCodec<CashStatusArgs, CashStatus> {
    return combineCodec(getCashStatusEncoder(), getCashStatusDecoder());
}