/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getAddressDecoder, getAddressEncoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';
import { getTermsDecoder, getTermsEncoder, type Terms, type TermsArgs } from './index.ts';

export type PendingChange = { terms: Terms; proposer: Address; reservedBps: number;  };

export type PendingChangeArgs = { terms: TermsArgs; proposer: Address; reservedBps: number;  };

export function getPendingChangeEncoder(): FixedSizeEncoder<PendingChangeArgs> {
    return getStructEncoder([['terms', getTermsEncoder()], ['proposer', getAddressEncoder()], ['reservedBps', getU16Encoder()]]);
}

export function getPendingChangeDecoder(): FixedSizeDecoder<PendingChange> {
    return getStructDecoder([['terms', getTermsDecoder()], ['proposer', getAddressDecoder()], ['reservedBps', getU16Decoder()]]);
}

export function getPendingChangeCodec(): FixedSizeCodec<PendingChangeArgs, PendingChange> {
    return combineCodec(getPendingChangeEncoder(), getPendingChangeDecoder());
}