/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export const Status = { 0: 'Proposed', 1: 'Active', 2: 'Completed', 3: 'Rejected', 4: 'Cancelled', Proposed: 0, Active: 1, Completed: 2, Rejected: 3, Cancelled: 4 } as const;

export type Status = (typeof Status)[Exclude<keyof typeof Status, number>];

export type StatusArgs = Status;

export function getStatusEncoder(): FixedSizeEncoder<StatusArgs> {
    return getEnumEncoder(Status);
}

export function getStatusDecoder(): FixedSizeDecoder<Status> {
    return getEnumDecoder(Status as Omit<typeof Status, number>);
}

export function getStatusCodec(): FixedSizeCodec<StatusArgs, Status> {
    return combineCodec(getStatusEncoder(), getStatusDecoder());
}