/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getI64Decoder, getI64Encoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, getU64Decoder, getU64Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export type Terms = { 
/** Valor total do acordo, em centavos (BRL-T tem 2 casas: 1 unidade = 1 centavo). */
original: bigint; rateBps: number; priority: number; dueTs: bigint;  };

export type TermsArgs = { 
/** Valor total do acordo, em centavos (BRL-T tem 2 casas: 1 unidade = 1 centavo). */
original: number | bigint; rateBps: number; priority: number; dueTs: number | bigint;  };

export function getTermsEncoder(): FixedSizeEncoder<TermsArgs> {
    return getStructEncoder([['original', getU64Encoder()], ['rateBps', getU16Encoder()], ['priority', getU16Encoder()], ['dueTs', getI64Encoder()]]);
}

export function getTermsDecoder(): FixedSizeDecoder<Terms> {
    return getStructDecoder([['original', getU64Decoder()], ['rateBps', getU16Decoder()], ['priority', getU16Decoder()], ['dueTs', getI64Decoder()]]);
}

export function getTermsCodec(): FixedSizeCodec<TermsArgs, Terms> {
    return combineCodec(getTermsEncoder(), getTermsDecoder());
}