import {randomUUID} from 'node:crypto';
import type {State} from '../src/domain/models.ts';
import {today} from '../src/domain/finance.ts';
import {cashSummary} from '../src/domain/cash.ts';
import {validDate,requireAmount} from '../src/domain/validation.ts';
import {inputRecord} from './input.ts';
export function scheduleDaily(state:State,value:unknown){const v=inputRecord(value),m=state.members.find(m=>m.id===v.memberId&&m.compensation==='daily'&&!m.demo&&!m.disabledAt);if(!m?.dailyAmount)throw Error('Colaborador por diária não encontrado.');if(!validDate(v.date)||v.date<=today())throw Error('Informe uma data futura.');if(state.dailySchedules?.some(s=>s.memberId===m.id&&s.date===v.date&&s.status!=='cancelled')||state.dailyWages?.some(w=>w.memberId===m.id&&w.date===v.date))throw Error('Período já registrado.');(state.dailySchedules??=[]).push({id:randomUUID(),memberId:m.id,name:m.name,date:v.date,amount:m.dailyAmount,status:'scheduled'});}
export function registerDaily(state:State,value:unknown){const v=inputRecord(value),m=state.members.find(m=>m.id===v.memberId&&m.compensation==='daily'&&!m.demo&&!m.disabledAt);if(!m?.dailyAmount)throw Error('Colaborador por diária não encontrado.');if(!validDate(v.date)||v.date>today())throw Error('Informe o dia trabalhado, sem data futura.');if(v.acknowledged!==true)throw Error('Confirme o dia efetivamente trabalhado.');if(state.dailyWages?.some(w=>w.memberId===m.id&&w.date===v.date))throw Error('Diária já registrada para esta pessoa neste dia.');const schedule=state.dailySchedules?.find(s=>s.memberId===m.id&&s.date===v.date&&s.status==='scheduled');const wage={id:randomUUID(),memberId:m.id,name:m.name,date:v.date,amount:schedule?.amount??m.dailyAmount,paid:0,recordedAt:new Date().toISOString()};(state.dailyWages??=[]).push(wage);if(schedule){schedule.status='generated';schedule.wageId=wage.id;}state.demo=false;}
export function payDaily(state:State,value:unknown){const v=inputRecord(value),w=state.dailyWages?.find(w=>w.id===v.id);if(!w)throw Error('Diária não encontrada.');requireAmount(v.amount);if(v.acknowledged!==true)throw Error('Confirme a entrega real do dinheiro.');if(typeof v.requestId!=='string'||! /^[a-f0-9-]{36}$/.test(v.requestId))throw Error('Identificador inválido.');if(state.cashMovements?.some(m=>m.reference===v.requestId))throw Error('Pagamento já registrado.');const c=cashSummary(state);if(!c.session||c.session.date!==today())throw Error('Abra o caixa de hoje antes de pagar.');if(v.amount>w.amount-w.paid||v.amount>c.free+(w.amount-w.paid))throw Error('Valor supera a diária pendente ou o caixa disponível após outros destinos.');const movementId=randomUUID();(state.cashMovements??=[]).push({id:movementId,type:'MANUAL_OUTFLOW',amount:v.amount,at:new Date().toISOString(),origin:'daily_wage',sessionId:c.session.id,reference:v.requestId,description:`Diária de ${w.name} — ${w.date}`,confirmedBy:'local_operator'});(state.dailyPayments??=[]).push({id:randomUUID(),wageId:w.id,amount:v.amount,date:today(),requestId:v.requestId,cashMovementId:movementId});w.paid+=v.amount;}
