/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertAccountExists, assertAccountsExist, combineCodec, decodeAccount, fetchEncodedAccount, fetchEncodedAccounts, fixDecoderSize, fixEncoderSize, getAddressDecoder, getAddressEncoder, getBytesDecoder, getBytesEncoder, getI64Decoder, getI64Encoder, getOptionDecoder, getOptionEncoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, getU32Decoder, getU32Encoder, getU64Decoder, getU64Encoder, getU8Decoder, getU8Encoder, transformEncoder, type Account, type Address, type Codec, type Decoder, type EncodedAccount, type Encoder, type FetchAccountConfig, type FetchAccountsConfig, type MaybeAccount, type MaybeEncodedAccount, type Option, type OptionOrNullable, type ReadonlyUint8Array } from '@solana/kit';
import { getPendingChangeDecoder, getPendingChangeEncoder, getStatusDecoder, getStatusEncoder, type PendingChange, type PendingChangeArgs, type Status, type StatusArgs } from '../types/index.ts';

export const AGREEMENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([83, 212, 5, 110, 225, 249, 197, 84]);

export function getAgreementDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(AGREEMENT_DISCRIMINATOR); }

export type Agreement = { discriminator: ReadonlyUint8Array; seller: Address; supplier: Address; mint: Address; agreementKey: ReadonlyUint8Array; original: bigint; paid: bigint; rateBps: number; priority: number; dueTs: bigint; status: Status; version: number; seq: bigint; createdTs: bigint; completedTs: bigint; pendingChange: Option<PendingChange>; bump: number;  };

export type AgreementArgs = { seller: Address; supplier: Address; mint: Address; agreementKey: ReadonlyUint8Array; original: number | bigint; paid: number | bigint; rateBps: number; priority: number; dueTs: number | bigint; status: StatusArgs; version: number; seq: number | bigint; createdTs: number | bigint; completedTs: number | bigint; pendingChange: OptionOrNullable<PendingChangeArgs>; bump: number;  };

/** Gets the encoder for {@link AgreementArgs} account data. */
export function getAgreementEncoder(): Encoder<AgreementArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['seller', getAddressEncoder()], ['supplier', getAddressEncoder()], ['mint', getAddressEncoder()], ['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['original', getU64Encoder()], ['paid', getU64Encoder()], ['rateBps', getU16Encoder()], ['priority', getU16Encoder()], ['dueTs', getI64Encoder()], ['status', getStatusEncoder()], ['version', getU32Encoder()], ['seq', getU64Encoder()], ['createdTs', getI64Encoder()], ['completedTs', getI64Encoder()], ['pendingChange', getOptionEncoder(getPendingChangeEncoder())], ['bump', getU8Encoder()]]), (value) => ({ ...value, discriminator: AGREEMENT_DISCRIMINATOR }));
}

/** Gets the decoder for {@link Agreement} account data. */
export function getAgreementDecoder(): Decoder<Agreement> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['seller', getAddressDecoder()], ['supplier', getAddressDecoder()], ['mint', getAddressDecoder()], ['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['original', getU64Decoder()], ['paid', getU64Decoder()], ['rateBps', getU16Decoder()], ['priority', getU16Decoder()], ['dueTs', getI64Decoder()], ['status', getStatusDecoder()], ['version', getU32Decoder()], ['seq', getU64Decoder()], ['createdTs', getI64Decoder()], ['completedTs', getI64Decoder()], ['pendingChange', getOptionDecoder(getPendingChangeDecoder())], ['bump', getU8Decoder()]]);
}

/** Gets the codec for {@link Agreement} account data. */
export function getAgreementCodec(): Codec<AgreementArgs, Agreement> {
    return combineCodec(getAgreementEncoder(), getAgreementDecoder());
}

export function decodeAgreement<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress>): Account<Agreement, TAddress>;
export function decodeAgreement<TAddress extends string = string>(encodedAccount: MaybeEncodedAccount<TAddress>): MaybeAccount<Agreement, TAddress>;
export function decodeAgreement<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>): Account<Agreement, TAddress> | MaybeAccount<Agreement, TAddress> {
  return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getAgreementDecoder());
}

export async function fetchAgreement<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Agreement, TAddress>> {
  const maybeAccount = await fetchMaybeAgreement(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAgreement<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Agreement, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAgreement(maybeAccount);
}

export async function fetchAllAgreement(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Agreement>[]> {
  const maybeAccounts = await fetchAllMaybeAgreement(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAgreement(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Agreement>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAgreement(maybeAccount));
}