/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertAccountExists, assertAccountsExist, combineCodec, decodeAccount, fetchEncodedAccount, fetchEncodedAccounts, fixDecoderSize, fixEncoderSize, getAddressDecoder, getAddressEncoder, getBytesDecoder, getBytesEncoder, getI64Decoder, getI64Encoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, getU8Decoder, getU8Encoder, transformEncoder, type Account, type Address, type EncodedAccount, type FetchAccountConfig, type FetchAccountsConfig, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type MaybeAccount, type MaybeEncodedAccount, type ReadonlyUint8Array } from '@solana/kit';
import { getCashStatusDecoder, getCashStatusEncoder, type CashStatus, type CashStatusArgs } from '../types/index.ts';

export const OFFCHAIN_PAYMENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([73, 126, 52, 187, 102, 57, 86, 23]);

export function getOffchainPaymentDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(OFFCHAIN_PAYMENT_DISCRIMINATOR); }

export type OffchainPayment = { discriminator: ReadonlyUint8Array; agreement: Address; nonce: ReadonlyUint8Array; amount: bigint; paidTs: bigint; status: CashStatus; decidedTs: bigint; bump: number;  };

export type OffchainPaymentArgs = { agreement: Address; nonce: ReadonlyUint8Array; amount: number | bigint; paidTs: number | bigint; status: CashStatusArgs; decidedTs: number | bigint; bump: number;  };

/** Gets the encoder for {@link OffchainPaymentArgs} account data. */
export function getOffchainPaymentEncoder(): FixedSizeEncoder<OffchainPaymentArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['agreement', getAddressEncoder()], ['nonce', fixEncoderSize(getBytesEncoder(), 16)], ['amount', getU64Encoder()], ['paidTs', getI64Encoder()], ['status', getCashStatusEncoder()], ['decidedTs', getI64Encoder()], ['bump', getU8Encoder()]]), (value) => ({ ...value, discriminator: OFFCHAIN_PAYMENT_DISCRIMINATOR }));
}

/** Gets the decoder for {@link OffchainPayment} account data. */
export function getOffchainPaymentDecoder(): FixedSizeDecoder<OffchainPayment> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['agreement', getAddressDecoder()], ['nonce', fixDecoderSize(getBytesDecoder(), 16)], ['amount', getU64Decoder()], ['paidTs', getI64Decoder()], ['status', getCashStatusDecoder()], ['decidedTs', getI64Decoder()], ['bump', getU8Decoder()]]);
}

/** Gets the codec for {@link OffchainPayment} account data. */
export function getOffchainPaymentCodec(): FixedSizeCodec<OffchainPaymentArgs, OffchainPayment> {
    return combineCodec(getOffchainPaymentEncoder(), getOffchainPaymentDecoder());
}

export function decodeOffchainPayment<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress>): Account<OffchainPayment, TAddress>;
export function decodeOffchainPayment<TAddress extends string = string>(encodedAccount: MaybeEncodedAccount<TAddress>): MaybeAccount<OffchainPayment, TAddress>;
export function decodeOffchainPayment<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>): Account<OffchainPayment, TAddress> | MaybeAccount<OffchainPayment, TAddress> {
  return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getOffchainPaymentDecoder());
}

export async function fetchOffchainPayment<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<OffchainPayment, TAddress>> {
  const maybeAccount = await fetchMaybeOffchainPayment(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOffchainPayment<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<OffchainPayment, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOffchainPayment(maybeAccount);
}

export async function fetchAllOffchainPayment(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<OffchainPayment>[]> {
  const maybeAccounts = await fetchAllMaybeOffchainPayment(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOffchainPayment(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<OffchainPayment>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeOffchainPayment(maybeAccount));
}

export function getOffchainPaymentSize(): number {
  return 82;
}