/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertAccountExists, assertAccountsExist, combineCodec, decodeAccount, fetchEncodedAccount, fetchEncodedAccounts, fixDecoderSize, fixEncoderSize, getAddressDecoder, getAddressEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, getU64Decoder, getU64Encoder, getU8Decoder, getU8Encoder, transformEncoder, type Account, type Address, type EncodedAccount, type FetchAccountConfig, type FetchAccountsConfig, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type MaybeAccount, type MaybeEncodedAccount, type ReadonlyUint8Array } from '@solana/kit';

export const SELLER_STATE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([250, 183, 151, 30, 213, 8, 45, 179]);

export function getSellerStateDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(SELLER_STATE_DISCRIMINATOR); }

export type SellerState = { discriminator: ReadonlyUint8Array; seller: Address; 
/** Soma dos % propostos + ativos (+ aumentos pendentes). Nunca > 10000. */
committedBps: number; activeCount: number; nextSeq: bigint; 
/** Menor fração das divisões (unidades do token). BRZ: 100 = 1 centavo. */
unit: bigint; 
/** Teto por venda (unidades do token); 0 = sem teto. */
maxSale: bigint; bump: number;  };

export type SellerStateArgs = { seller: Address; 
/** Soma dos % propostos + ativos (+ aumentos pendentes). Nunca > 10000. */
committedBps: number; activeCount: number; nextSeq: number | bigint; 
/** Menor fração das divisões (unidades do token). BRZ: 100 = 1 centavo. */
unit: number | bigint; 
/** Teto por venda (unidades do token); 0 = sem teto. */
maxSale: number | bigint; bump: number;  };

/** Gets the encoder for {@link SellerStateArgs} account data. */
export function getSellerStateEncoder(): FixedSizeEncoder<SellerStateArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['seller', getAddressEncoder()], ['committedBps', getU16Encoder()], ['activeCount', getU8Encoder()], ['nextSeq', getU64Encoder()], ['unit', getU64Encoder()], ['maxSale', getU64Encoder()], ['bump', getU8Encoder()]]), (value) => ({ ...value, discriminator: SELLER_STATE_DISCRIMINATOR }));
}

/** Gets the decoder for {@link SellerState} account data. */
export function getSellerStateDecoder(): FixedSizeDecoder<SellerState> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['seller', getAddressDecoder()], ['committedBps', getU16Decoder()], ['activeCount', getU8Decoder()], ['nextSeq', getU64Decoder()], ['unit', getU64Decoder()], ['maxSale', getU64Decoder()], ['bump', getU8Decoder()]]);
}

/** Gets the codec for {@link SellerState} account data. */
export function getSellerStateCodec(): FixedSizeCodec<SellerStateArgs, SellerState> {
    return combineCodec(getSellerStateEncoder(), getSellerStateDecoder());
}

export function decodeSellerState<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress>): Account<SellerState, TAddress>;
export function decodeSellerState<TAddress extends string = string>(encodedAccount: MaybeEncodedAccount<TAddress>): MaybeAccount<SellerState, TAddress>;
export function decodeSellerState<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>): Account<SellerState, TAddress> | MaybeAccount<SellerState, TAddress> {
  return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getSellerStateDecoder());
}

export async function fetchSellerState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<SellerState, TAddress>> {
  const maybeAccount = await fetchMaybeSellerState(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeSellerState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<SellerState, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeSellerState(maybeAccount);
}

export async function fetchAllSellerState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<SellerState>[]> {
  const maybeAccounts = await fetchAllMaybeSellerState(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeSellerState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<SellerState>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeSellerState(maybeAccount));
}

export function getSellerStateSize(): number {
  return 68;
}