/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, getAddressFromResolvedInstructionAccount, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { findSellerStatePda } from '../pdas/index.ts';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const CANCEL_PROPOSAL_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([106, 74, 128, 146, 19, 65, 39, 23]);

export function getCancelProposalDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(CANCEL_PROPOSAL_DISCRIMINATOR); }

export type CancelProposalInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSeller extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSeller extends string ? ReadonlySignerAccount<TAccountSeller> & AccountSignerMeta<TAccountSeller> : TAccountSeller, TAccountAgreement extends string ? WritableAccount<TAccountAgreement> : TAccountAgreement, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, ...TRemainingAccounts]>;

export type CancelProposalInstructionData = { discriminator: ReadonlyUint8Array;  };

export type CancelProposalInstructionDataArgs = {  };

export function getCancelProposalInstructionDataEncoder(): FixedSizeEncoder<CancelProposalInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), (value) => ({ ...value, discriminator: CANCEL_PROPOSAL_DISCRIMINATOR }));
}

export function getCancelProposalInstructionDataDecoder(): FixedSizeDecoder<CancelProposalInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getCancelProposalInstructionDataCodec(): FixedSizeCodec<CancelProposalInstructionDataArgs, CancelProposalInstructionData> {
    return combineCodec(getCancelProposalInstructionDataEncoder(), getCancelProposalInstructionDataDecoder());
}

export type CancelProposalAsyncInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
agreement: TAccountAgreement;
sellerState?: TAccountSellerState;
}

export async function getCancelProposalInstructionAsync<TAccountSeller extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: CancelProposalAsyncInput<TAccountSeller, TAccountAgreement, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): Promise<CancelProposalInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: false }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Resolve default values.
if (!accounts.sellerState.value) {
accounts.sellerState.value = await findSellerStatePda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value) }, { programAddress });
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState)], data: getCancelProposalInstructionDataEncoder().encode({}), programAddress } as CancelProposalInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type CancelProposalInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
agreement: TAccountAgreement;
sellerState: TAccountSellerState;
}

export function getCancelProposalInstruction<TAccountSeller extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: CancelProposalInput<TAccountSeller, TAccountAgreement, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): CancelProposalInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: false }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;




return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState)], data: getCancelProposalInstructionDataEncoder().encode({}), programAddress } as CancelProposalInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type ParsedCancelProposalInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
seller: TAccountMetas[0];
agreement: TAccountMetas[1];
sellerState: TAccountMetas[2];
};
data: CancelProposalInstructionData; };

export function parseCancelProposalInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedCancelProposalInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 3 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { seller: getNextAccount(), agreement: getNextAccount(), sellerState: getNextAccount() }, data: getCancelProposalInstructionDataDecoder().decode(instruction.data) };
}