/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBooleanDecoder, getBooleanEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const DECIDE_CHANGE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([207, 31, 49, 246, 157, 164, 88, 95]);

export function getDecideChangeDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(DECIDE_CHANGE_DISCRIMINATOR); }

export type DecideChangeInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSigner extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSigner extends string ? ReadonlySignerAccount<TAccountSigner> & AccountSignerMeta<TAccountSigner> : TAccountSigner, TAccountAgreement extends string ? WritableAccount<TAccountAgreement> : TAccountAgreement, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, ...TRemainingAccounts]>;

export type DecideChangeInstructionData = { discriminator: ReadonlyUint8Array; accept: boolean;  };

export type DecideChangeInstructionDataArgs = { accept: boolean;  };

export function getDecideChangeInstructionDataEncoder(): FixedSizeEncoder<DecideChangeInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['accept', getBooleanEncoder()]]), (value) => ({ ...value, discriminator: DECIDE_CHANGE_DISCRIMINATOR }));
}

export function getDecideChangeInstructionDataDecoder(): FixedSizeDecoder<DecideChangeInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['accept', getBooleanDecoder()]]);
}

export function getDecideChangeInstructionDataCodec(): FixedSizeCodec<DecideChangeInstructionDataArgs, DecideChangeInstructionData> {
    return combineCodec(getDecideChangeInstructionDataEncoder(), getDecideChangeInstructionDataDecoder());
}

export type DecideChangeInput<TAccountSigner extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  /** Vendedor ou fornecedor (conferido na instrução). */
signer: TAccountSigner;
agreement: TAccountAgreement;
sellerState: TAccountSellerState;
accept: DecideChangeInstructionDataArgs["accept"];
}

export function getDecideChangeInstruction<TAccountSigner extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: DecideChangeInput<TAccountSigner, TAccountAgreement, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): DecideChangeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSigner, InstructionAccountInputAddress<TAccountSigner>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { signer: { value: input.signer ?? null, isSigner: true, isWritable: false }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




return Object.freeze({ accounts: [getAccountMeta("signer", accounts.signer), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState)], data: getDecideChangeInstructionDataEncoder().encode(args as DecideChangeInstructionDataArgs), programAddress } as DecideChangeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSigner, InstructionAccountInputAddress<TAccountSigner>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type ParsedDecideChangeInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
/** Vendedor ou fornecedor (conferido na instrução). */
signer: TAccountMetas[0];
agreement: TAccountMetas[1];
sellerState: TAccountMetas[2];
};
data: DecideChangeInstructionData; };

export function parseDecideChangeInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedDecideChangeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 3 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { signer: getNextAccount(), agreement: getNextAccount(), sellerState: getNextAccount() }, data: getDecideChangeInstructionDataDecoder().decode(instruction.data) };
}