/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const DISPUTE_OFFCHAIN_PAYMENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([191, 176, 2, 7, 135, 5, 138, 147]);

export function getDisputeOffchainPaymentDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(DISPUTE_OFFCHAIN_PAYMENT_DISCRIMINATOR); }

export type DisputeOffchainPaymentInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSupplier extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TAccountPayment extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSupplier extends string ? ReadonlySignerAccount<TAccountSupplier> & AccountSignerMeta<TAccountSupplier> : TAccountSupplier, TAccountAgreement extends string ? WritableAccount<TAccountAgreement> : TAccountAgreement, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, TAccountPayment extends string ? WritableAccount<TAccountPayment> : TAccountPayment, ...TRemainingAccounts]>;

export type DisputeOffchainPaymentInstructionData = { discriminator: ReadonlyUint8Array;  };

export type DisputeOffchainPaymentInstructionDataArgs = {  };

export function getDisputeOffchainPaymentInstructionDataEncoder(): FixedSizeEncoder<DisputeOffchainPaymentInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), (value) => ({ ...value, discriminator: DISPUTE_OFFCHAIN_PAYMENT_DISCRIMINATOR }));
}

export function getDisputeOffchainPaymentInstructionDataDecoder(): FixedSizeDecoder<DisputeOffchainPaymentInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getDisputeOffchainPaymentInstructionDataCodec(): FixedSizeCodec<DisputeOffchainPaymentInstructionDataArgs, DisputeOffchainPaymentInstructionData> {
    return combineCodec(getDisputeOffchainPaymentInstructionDataEncoder(), getDisputeOffchainPaymentInstructionDataDecoder());
}

export type DisputeOffchainPaymentInput<TAccountSupplier extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountPayment extends InstructionAccountInput = InstructionAccountInput> =  {
  supplier: TAccountSupplier;
agreement: TAccountAgreement;
sellerState: TAccountSellerState;
payment: TAccountPayment;
}

export function getDisputeOffchainPaymentInstruction<TAccountSupplier extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountPayment extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: DisputeOffchainPaymentInput<TAccountSupplier, TAccountAgreement, TAccountSellerState, TAccountPayment>, config?: { programAddress?: TProgramAddress } ): DisputeOffchainPaymentInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountPayment, InstructionAccountInputAddress<TAccountPayment>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { supplier: { value: input.supplier ?? null, isSigner: true, isWritable: false }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, payment: { value: input.payment ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;




return Object.freeze({ accounts: [getAccountMeta("supplier", accounts.supplier), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("payment", accounts.payment)], data: getDisputeOffchainPaymentInstructionDataEncoder().encode({}), programAddress } as DisputeOffchainPaymentInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountPayment, InstructionAccountInputAddress<TAccountPayment>>>);
}

export type ParsedDisputeOffchainPaymentInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
supplier: TAccountMetas[0];
agreement: TAccountMetas[1];
sellerState: TAccountMetas[2];
payment: TAccountMetas[3];
};
data: DisputeOffchainPaymentInstructionData; };

export function parseDisputeOffchainPaymentInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedDisputeOffchainPaymentInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 4 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { supplier: getNextAccount(), agreement: getNextAccount(), sellerState: getNextAccount(), payment: getNextAccount() }, data: getDisputeOffchainPaymentInstructionDataDecoder().decode(instruction.data) };
}