/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getI64Decoder, getI64Encoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, getAddressFromResolvedInstructionAccount, getNonNullResolvedInstructionInput, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { findAgreementPda, findSellerStatePda } from '../pdas/index.ts';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';
import { getTermsDecoder, getTermsEncoder, type Terms, type TermsArgs } from '../types/index.ts';

export const PROPOSE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([93, 253, 82, 168, 118, 33, 102, 90]);

export function getProposeDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(PROPOSE_DISCRIMINATOR); }

export type ProposeInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSeller extends string | AccountMeta<string> = string, TAccountSupplier extends string | AccountMeta<string> = string, TAccountMint extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSeller extends string ? WritableSignerAccount<TAccountSeller> & AccountSignerMeta<TAccountSeller> : TAccountSeller, TAccountSupplier extends string ? ReadonlyAccount<TAccountSupplier> : TAccountSupplier, TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, TAccountAgreement extends string ? WritableAccount<TAccountAgreement> : TAccountAgreement, TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram, ...TRemainingAccounts]>;

export type ProposeInstructionData = { discriminator: ReadonlyUint8Array; agreementKey: ReadonlyUint8Array; terms: Terms; paidBefore: bigint; createdTs: bigint;  };

export type ProposeInstructionDataArgs = { agreementKey: ReadonlyUint8Array; terms: TermsArgs; paidBefore: number | bigint; createdTs: number | bigint;  };

export function getProposeInstructionDataEncoder(): FixedSizeEncoder<ProposeInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['agreementKey', fixEncoderSize(getBytesEncoder(), 32)], ['terms', getTermsEncoder()], ['paidBefore', getU64Encoder()], ['createdTs', getI64Encoder()]]), (value) => ({ ...value, discriminator: PROPOSE_DISCRIMINATOR }));
}

export function getProposeInstructionDataDecoder(): FixedSizeDecoder<ProposeInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['agreementKey', fixDecoderSize(getBytesDecoder(), 32)], ['terms', getTermsDecoder()], ['paidBefore', getU64Decoder()], ['createdTs', getI64Decoder()]]);
}

export function getProposeInstructionDataCodec(): FixedSizeCodec<ProposeInstructionDataArgs, ProposeInstructionData> {
    return combineCodec(getProposeInstructionDataEncoder(), getProposeInstructionDataDecoder());
}

export type ProposeAsyncInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountSupplier extends InstructionAccountInput = InstructionAccountInput, TAccountMint extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
supplier: TAccountSupplier;
mint: TAccountMint;
sellerState?: TAccountSellerState;
agreement?: TAccountAgreement;
systemProgram?: TAccountSystemProgram;
agreementKey: ProposeInstructionDataArgs["agreementKey"];
terms: ProposeInstructionDataArgs["terms"];
paidBefore: ProposeInstructionDataArgs["paidBefore"];
createdTs: ProposeInstructionDataArgs["createdTs"];
}

export async function getProposeInstructionAsync<TAccountSeller extends InstructionSignerInput, TAccountSupplier extends InstructionAccountInput, TAccountMint extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountAgreement extends InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: ProposeAsyncInput<TAccountSeller, TAccountSupplier, TAccountMint, TAccountSellerState, TAccountAgreement, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): Promise<ProposeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: true }, supplier: { value: input.supplier ?? null, isSigner: false, isWritable: false }, mint: { value: input.mint ?? null, isSigner: false, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.sellerState.value) {
accounts.sellerState.value = await findSellerStatePda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value) }, { programAddress });
}
if (!accounts.agreement.value) {
accounts.agreement.value = await findAgreementPda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value), agreementKey: getNonNullResolvedInstructionInput("agreementKey", args.agreementKey) }, { programAddress });
}
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("supplier", accounts.supplier), getAccountMeta("mint", accounts.mint), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("agreement", accounts.agreement), getAccountMeta("systemProgram", accounts.systemProgram)], data: getProposeInstructionDataEncoder().encode(args as ProposeInstructionDataArgs), programAddress } as ProposeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>);
}

export type ProposeInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountSupplier extends InstructionAccountInput = InstructionAccountInput, TAccountMint extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
supplier: TAccountSupplier;
mint: TAccountMint;
sellerState: TAccountSellerState;
agreement: TAccountAgreement;
systemProgram?: TAccountSystemProgram;
agreementKey: ProposeInstructionDataArgs["agreementKey"];
terms: ProposeInstructionDataArgs["terms"];
paidBefore: ProposeInstructionDataArgs["paidBefore"];
createdTs: ProposeInstructionDataArgs["createdTs"];
}

export function getProposeInstruction<TAccountSeller extends InstructionSignerInput, TAccountSupplier extends InstructionAccountInput, TAccountMint extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountAgreement extends InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: ProposeInput<TAccountSeller, TAccountSupplier, TAccountMint, TAccountSellerState, TAccountAgreement, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): ProposeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: true }, supplier: { value: input.supplier ?? null, isSigner: false, isWritable: false }, mint: { value: input.mint ?? null, isSigner: false, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("supplier", accounts.supplier), getAccountMeta("mint", accounts.mint), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("agreement", accounts.agreement), getAccountMeta("systemProgram", accounts.systemProgram)], data: getProposeInstructionDataEncoder().encode(args as ProposeInstructionDataArgs), programAddress } as ProposeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>);
}

export type ParsedProposeInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
seller: TAccountMetas[0];
supplier: TAccountMetas[1];
mint: TAccountMetas[2];
sellerState: TAccountMetas[3];
agreement: TAccountMetas[4];
systemProgram: TAccountMetas[5];
};
data: ProposeInstructionData; };

export function parseProposeInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedProposeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 6 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { seller: getNextAccount(), supplier: getNextAccount(), mint: getNextAccount(), sellerState: getNextAccount(), agreement: getNextAccount(), systemProgram: getNextAccount() }, data: getProposeInstructionDataDecoder().decode(instruction.data) };
}