/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';
import { getTermsDecoder, getTermsEncoder, type Terms, type TermsArgs } from '../types/index.ts';

export const PROPOSE_CHANGE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([167, 211, 18, 222, 93, 215, 74, 159]);

export function getProposeChangeDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(PROPOSE_CHANGE_DISCRIMINATOR); }

export type ProposeChangeInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSigner extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSigner extends string ? ReadonlySignerAccount<TAccountSigner> & AccountSignerMeta<TAccountSigner> : TAccountSigner, TAccountAgreement extends string ? WritableAccount<TAccountAgreement> : TAccountAgreement, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, ...TRemainingAccounts]>;

export type ProposeChangeInstructionData = { discriminator: ReadonlyUint8Array; terms: Terms;  };

export type ProposeChangeInstructionDataArgs = { terms: TermsArgs;  };

export function getProposeChangeInstructionDataEncoder(): FixedSizeEncoder<ProposeChangeInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['terms', getTermsEncoder()]]), (value) => ({ ...value, discriminator: PROPOSE_CHANGE_DISCRIMINATOR }));
}

export function getProposeChangeInstructionDataDecoder(): FixedSizeDecoder<ProposeChangeInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['terms', getTermsDecoder()]]);
}

export function getProposeChangeInstructionDataCodec(): FixedSizeCodec<ProposeChangeInstructionDataArgs, ProposeChangeInstructionData> {
    return combineCodec(getProposeChangeInstructionDataEncoder(), getProposeChangeInstructionDataDecoder());
}

export type ProposeChangeInput<TAccountSigner extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  /** Vendedor ou fornecedor (conferido na instrução). */
signer: TAccountSigner;
agreement: TAccountAgreement;
sellerState: TAccountSellerState;
terms: ProposeChangeInstructionDataArgs["terms"];
}

export function getProposeChangeInstruction<TAccountSigner extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: ProposeChangeInput<TAccountSigner, TAccountAgreement, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): ProposeChangeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSigner, InstructionAccountInputAddress<TAccountSigner>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { signer: { value: input.signer ?? null, isSigner: true, isWritable: false }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




return Object.freeze({ accounts: [getAccountMeta("signer", accounts.signer), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState)], data: getProposeChangeInstructionDataEncoder().encode(args as ProposeChangeInstructionDataArgs), programAddress } as ProposeChangeInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSigner, InstructionAccountInputAddress<TAccountSigner>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type ParsedProposeChangeInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
/** Vendedor ou fornecedor (conferido na instrução). */
signer: TAccountMetas[0];
agreement: TAccountMetas[1];
sellerState: TAccountMetas[2];
};
data: ProposeChangeInstructionData; };

export function parseProposeChangeInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedProposeChangeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 3 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { signer: getNextAccount(), agreement: getNextAccount(), sellerState: getNextAccount() }, data: getProposeChangeInstructionDataDecoder().decode(instruction.data) };
}