/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, getAddressFromResolvedInstructionAccount, getNonNullResolvedInstructionInput, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { findPaymentPda, findSellerStatePda } from '../pdas/index.ts';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const RECORD_OFFCHAIN_PAYMENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([151, 174, 235, 117, 235, 215, 96, 213]);

export function getRecordOffchainPaymentDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(RECORD_OFFCHAIN_PAYMENT_DISCRIMINATOR); }

export type RecordOffchainPaymentInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSeller extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TAccountPayment extends string | AccountMeta<string> = string, TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSeller extends string ? WritableSignerAccount<TAccountSeller> & AccountSignerMeta<TAccountSeller> : TAccountSeller, TAccountAgreement extends string ? ReadonlyAccount<TAccountAgreement> : TAccountAgreement, TAccountSellerState extends string ? ReadonlyAccount<TAccountSellerState> : TAccountSellerState, TAccountPayment extends string ? WritableAccount<TAccountPayment> : TAccountPayment, TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram, ...TRemainingAccounts]>;

export type RecordOffchainPaymentInstructionData = { discriminator: ReadonlyUint8Array; amount: bigint; nonce: ReadonlyUint8Array;  };

export type RecordOffchainPaymentInstructionDataArgs = { amount: number | bigint; nonce: ReadonlyUint8Array;  };

export function getRecordOffchainPaymentInstructionDataEncoder(): FixedSizeEncoder<RecordOffchainPaymentInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['amount', getU64Encoder()], ['nonce', fixEncoderSize(getBytesEncoder(), 16)]]), (value) => ({ ...value, discriminator: RECORD_OFFCHAIN_PAYMENT_DISCRIMINATOR }));
}

export function getRecordOffchainPaymentInstructionDataDecoder(): FixedSizeDecoder<RecordOffchainPaymentInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['amount', getU64Decoder()], ['nonce', fixDecoderSize(getBytesDecoder(), 16)]]);
}

export function getRecordOffchainPaymentInstructionDataCodec(): FixedSizeCodec<RecordOffchainPaymentInstructionDataArgs, RecordOffchainPaymentInstructionData> {
    return combineCodec(getRecordOffchainPaymentInstructionDataEncoder(), getRecordOffchainPaymentInstructionDataDecoder());
}

export type RecordOffchainPaymentAsyncInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountPayment extends InstructionAccountInput = InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
agreement: TAccountAgreement;
sellerState?: TAccountSellerState;
payment?: TAccountPayment;
systemProgram?: TAccountSystemProgram;
amount: RecordOffchainPaymentInstructionDataArgs["amount"];
nonce: RecordOffchainPaymentInstructionDataArgs["nonce"];
}

export async function getRecordOffchainPaymentInstructionAsync<TAccountSeller extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountPayment extends InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: RecordOffchainPaymentAsyncInput<TAccountSeller, TAccountAgreement, TAccountSellerState, TAccountPayment, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): Promise<RecordOffchainPaymentInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountPayment, InstructionAccountInputAddress<TAccountPayment>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: true }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: false }, payment: { value: input.payment ?? null, isSigner: false, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.sellerState.value) {
accounts.sellerState.value = await findSellerStatePda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value) }, { programAddress });
}
if (!accounts.payment.value) {
accounts.payment.value = await findPaymentPda({ agreement: getAddressFromResolvedInstructionAccount("agreement", accounts.agreement.value), nonce: getNonNullResolvedInstructionInput("nonce", args.nonce) }, { programAddress });
}
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("payment", accounts.payment), getAccountMeta("systemProgram", accounts.systemProgram)], data: getRecordOffchainPaymentInstructionDataEncoder().encode(args as RecordOffchainPaymentInstructionDataArgs), programAddress } as RecordOffchainPaymentInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountPayment, InstructionAccountInputAddress<TAccountPayment>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>);
}

export type RecordOffchainPaymentInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountPayment extends InstructionAccountInput = InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
agreement: TAccountAgreement;
sellerState: TAccountSellerState;
payment: TAccountPayment;
systemProgram?: TAccountSystemProgram;
amount: RecordOffchainPaymentInstructionDataArgs["amount"];
nonce: RecordOffchainPaymentInstructionDataArgs["nonce"];
}

export function getRecordOffchainPaymentInstruction<TAccountSeller extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountPayment extends InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: RecordOffchainPaymentInput<TAccountSeller, TAccountAgreement, TAccountSellerState, TAccountPayment, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): RecordOffchainPaymentInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountPayment, InstructionAccountInputAddress<TAccountPayment>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: true }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: false }, payment: { value: input.payment ?? null, isSigner: false, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("payment", accounts.payment), getAccountMeta("systemProgram", accounts.systemProgram)], data: getRecordOffchainPaymentInstructionDataEncoder().encode(args as RecordOffchainPaymentInstructionDataArgs), programAddress } as RecordOffchainPaymentInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountPayment, InstructionAccountInputAddress<TAccountPayment>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>);
}

export type ParsedRecordOffchainPaymentInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
seller: TAccountMetas[0];
agreement: TAccountMetas[1];
sellerState: TAccountMetas[2];
payment: TAccountMetas[3];
systemProgram: TAccountMetas[4];
};
data: RecordOffchainPaymentInstructionData; };

export function parseRecordOffchainPaymentInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedRecordOffchainPaymentInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 5 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { seller: getNextAccount(), agreement: getNextAccount(), sellerState: getNextAccount(), payment: getNextAccount(), systemProgram: getNextAccount() }, data: getRecordOffchainPaymentInstructionDataDecoder().decode(instruction.data) };
}