/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, getAddressFromResolvedInstructionAccount, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { findSellerStatePda } from '../pdas/index.ts';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const REGISTER_SELLER_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([9, 50, 144, 162, 206, 176, 154, 111]);

export function getRegisterSellerDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(REGISTER_SELLER_DISCRIMINATOR); }

export type RegisterSellerInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSeller extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSeller extends string ? WritableSignerAccount<TAccountSeller> & AccountSignerMeta<TAccountSeller> : TAccountSeller, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram, ...TRemainingAccounts]>;

export type RegisterSellerInstructionData = { discriminator: ReadonlyUint8Array; unit: bigint; maxSale: bigint;  };

export type RegisterSellerInstructionDataArgs = { unit: number | bigint; maxSale: number | bigint;  };

export function getRegisterSellerInstructionDataEncoder(): FixedSizeEncoder<RegisterSellerInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['unit', getU64Encoder()], ['maxSale', getU64Encoder()]]), (value) => ({ ...value, discriminator: REGISTER_SELLER_DISCRIMINATOR }));
}

export function getRegisterSellerInstructionDataDecoder(): FixedSizeDecoder<RegisterSellerInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['unit', getU64Decoder()], ['maxSale', getU64Decoder()]]);
}

export function getRegisterSellerInstructionDataCodec(): FixedSizeCodec<RegisterSellerInstructionDataArgs, RegisterSellerInstructionData> {
    return combineCodec(getRegisterSellerInstructionDataEncoder(), getRegisterSellerInstructionDataDecoder());
}

export type RegisterSellerAsyncInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
sellerState?: TAccountSellerState;
systemProgram?: TAccountSystemProgram;
unit: RegisterSellerInstructionDataArgs["unit"];
maxSale: RegisterSellerInstructionDataArgs["maxSale"];
}

export async function getRegisterSellerInstructionAsync<TAccountSeller extends InstructionSignerInput, TAccountSellerState extends InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: RegisterSellerAsyncInput<TAccountSeller, TAccountSellerState, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): Promise<RegisterSellerInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.sellerState.value) {
accounts.sellerState.value = await findSellerStatePda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value) }, { programAddress });
}
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("systemProgram", accounts.systemProgram)], data: getRegisterSellerInstructionDataEncoder().encode(args as RegisterSellerInstructionDataArgs), programAddress } as RegisterSellerInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>);
}

export type RegisterSellerInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
sellerState: TAccountSellerState;
systemProgram?: TAccountSystemProgram;
unit: RegisterSellerInstructionDataArgs["unit"];
maxSale: RegisterSellerInstructionDataArgs["maxSale"];
}

export function getRegisterSellerInstruction<TAccountSeller extends InstructionSignerInput, TAccountSellerState extends InstructionAccountInput, TAccountSystemProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: RegisterSellerInput<TAccountSeller, TAccountSellerState, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): RegisterSellerInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("systemProgram", accounts.systemProgram)], data: getRegisterSellerInstructionDataEncoder().encode(args as RegisterSellerInstructionDataArgs), programAddress } as RegisterSellerInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountSystemProgram, InstructionAccountInputAddress<TAccountSystemProgram>>>);
}

export type ParsedRegisterSellerInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
seller: TAccountMetas[0];
sellerState: TAccountMetas[1];
systemProgram: TAccountMetas[2];
};
data: RegisterSellerInstructionData; };

export function parseRegisterSellerInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedRegisterSellerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 3 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { seller: getNextAccount(), sellerState: getNextAccount(), systemProgram: getNextAccount() }, data: getRegisterSellerInstructionDataDecoder().decode(instruction.data) };
}