/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const REJECT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([135, 7, 63, 85, 131, 114, 111, 224]);

export function getRejectDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(REJECT_DISCRIMINATOR); }

export type RejectInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSupplier extends string | AccountMeta<string> = string, TAccountAgreement extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSupplier extends string ? ReadonlySignerAccount<TAccountSupplier> & AccountSignerMeta<TAccountSupplier> : TAccountSupplier, TAccountAgreement extends string ? WritableAccount<TAccountAgreement> : TAccountAgreement, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, ...TRemainingAccounts]>;

export type RejectInstructionData = { discriminator: ReadonlyUint8Array;  };

export type RejectInstructionDataArgs = {  };

export function getRejectInstructionDataEncoder(): FixedSizeEncoder<RejectInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), (value) => ({ ...value, discriminator: REJECT_DISCRIMINATOR }));
}

export function getRejectInstructionDataDecoder(): FixedSizeDecoder<RejectInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getRejectInstructionDataCodec(): FixedSizeCodec<RejectInstructionDataArgs, RejectInstructionData> {
    return combineCodec(getRejectInstructionDataEncoder(), getRejectInstructionDataDecoder());
}

export type RejectInput<TAccountSupplier extends InstructionSignerInput = InstructionSignerInput, TAccountAgreement extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  supplier: TAccountSupplier;
agreement: TAccountAgreement;
sellerState: TAccountSellerState;
}

export function getRejectInstruction<TAccountSupplier extends InstructionSignerInput, TAccountAgreement extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: RejectInput<TAccountSupplier, TAccountAgreement, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): RejectInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { supplier: { value: input.supplier ?? null, isSigner: true, isWritable: false }, agreement: { value: input.agreement ?? null, isSigner: false, isWritable: true }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;




return Object.freeze({ accounts: [getAccountMeta("supplier", accounts.supplier), getAccountMeta("agreement", accounts.agreement), getAccountMeta("sellerState", accounts.sellerState)], data: getRejectInstructionDataEncoder().encode({}), programAddress } as RejectInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSupplier, InstructionAccountInputAddress<TAccountSupplier>>, ResolvedInstructionAccountMeta<TAccountAgreement, InstructionAccountInputAddress<TAccountAgreement>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type ParsedRejectInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
supplier: TAccountMetas[0];
agreement: TAccountMetas[1];
sellerState: TAccountMetas[2];
};
data: RejectInstructionData; };

export function parseRejectInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedRejectInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 3 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { supplier: getNextAccount(), agreement: getNextAccount(), sellerState: getNextAccount() }, data: getRejectInstructionDataDecoder().decode(instruction.data) };
}