/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, getAddressFromResolvedInstructionAccount, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { findSellerStatePda } from '../pdas/index.ts';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const SET_LIMITS_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([207, 50, 250, 67, 211, 33, 70, 91]);

export function getSetLimitsDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(SET_LIMITS_DISCRIMINATOR); }

export type SetLimitsInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountSeller extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSeller extends string ? ReadonlySignerAccount<TAccountSeller> & AccountSignerMeta<TAccountSeller> : TAccountSeller, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, ...TRemainingAccounts]>;

export type SetLimitsInstructionData = { discriminator: ReadonlyUint8Array; maxSale: bigint;  };

export type SetLimitsInstructionDataArgs = { maxSale: number | bigint;  };

export function getSetLimitsInstructionDataEncoder(): FixedSizeEncoder<SetLimitsInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['maxSale', getU64Encoder()]]), (value) => ({ ...value, discriminator: SET_LIMITS_DISCRIMINATOR }));
}

export function getSetLimitsInstructionDataDecoder(): FixedSizeDecoder<SetLimitsInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['maxSale', getU64Decoder()]]);
}

export function getSetLimitsInstructionDataCodec(): FixedSizeCodec<SetLimitsInstructionDataArgs, SetLimitsInstructionData> {
    return combineCodec(getSetLimitsInstructionDataEncoder(), getSetLimitsInstructionDataDecoder());
}

export type SetLimitsAsyncInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
sellerState?: TAccountSellerState;
maxSale: SetLimitsInstructionDataArgs["maxSale"];
}

export async function getSetLimitsInstructionAsync<TAccountSeller extends InstructionSignerInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: SetLimitsAsyncInput<TAccountSeller, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): Promise<SetLimitsInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.sellerState.value) {
accounts.sellerState.value = await findSellerStatePda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value) }, { programAddress });
}

return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("sellerState", accounts.sellerState)], data: getSetLimitsInstructionDataEncoder().encode(args as SetLimitsInstructionDataArgs), programAddress } as SetLimitsInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type SetLimitsInput<TAccountSeller extends InstructionSignerInput = InstructionSignerInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput> =  {
  seller: TAccountSeller;
sellerState: TAccountSellerState;
maxSale: SetLimitsInstructionDataArgs["maxSale"];
}

export function getSetLimitsInstruction<TAccountSeller extends InstructionSignerInput, TAccountSellerState extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: SetLimitsInput<TAccountSeller, TAccountSellerState>, config?: { programAddress?: TProgramAddress } ): SetLimitsInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { seller: { value: input.seller ?? null, isSigner: true, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




return Object.freeze({ accounts: [getAccountMeta("seller", accounts.seller), getAccountMeta("sellerState", accounts.sellerState)], data: getSetLimitsInstructionDataEncoder().encode(args as SetLimitsInstructionDataArgs), programAddress } as SetLimitsInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>>);
}

export type ParsedSetLimitsInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
seller: TAccountMetas[0];
sellerState: TAccountMetas[1];
};
data: SetLimitsInstructionData; };

export function parseSetLimitsInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedSetLimitsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 2 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { seller: getNextAccount(), sellerState: getNextAccount() }, data: getSetLimitsInstructionDataDecoder().decode(instruction.data) };
}