/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getArrayDecoder, getArrayEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, getU64Decoder, getU64Encoder, getU8Decoder, getU8Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlySignerAccount, type ReadonlyUint8Array, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, getAddressFromResolvedInstructionAccount, type InstructionAccountInput, type InstructionAccountInputAddress, type InstructionSignerInput, type ResolvedInstructionAccount, type ResolvedInstructionAccountMeta } from '@solana/kit/program-client-core';
import { findSellerStatePda } from '../pdas/index.ts';
import { GIRO_ACORDOS_PROGRAM_ADDRESS } from '../programs/index.ts';

export const SETTLE_SALE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([182, 49, 63, 248, 140, 81, 40, 126]);

export function getSettleSaleDiscriminatorBytes(): ReadonlyUint8Array { return fixEncoderSize(getBytesEncoder(), 8).encode(SETTLE_SALE_DISCRIMINATOR); }

export type SettleSaleInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountPayer extends string | AccountMeta<string> = string, TAccountSeller extends string | AccountMeta<string> = string, TAccountSellerState extends string | AccountMeta<string> = string, TAccountMint extends string | AccountMeta<string> = string, TAccountPayerToken extends string | AccountMeta<string> = string, TAccountSellerToken extends string | AccountMeta<string> = string, TAccountTokenProgram extends string | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountPayer extends string ? ReadonlySignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer> : TAccountPayer, TAccountSeller extends string ? ReadonlyAccount<TAccountSeller> : TAccountSeller, TAccountSellerState extends string ? WritableAccount<TAccountSellerState> : TAccountSellerState, TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint, TAccountPayerToken extends string ? WritableAccount<TAccountPayerToken> : TAccountPayerToken, TAccountSellerToken extends string ? WritableAccount<TAccountSellerToken> : TAccountSellerToken, TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram, ...TRemainingAccounts]>;

export type SettleSaleInstructionData = { discriminator: ReadonlyUint8Array; amount: bigint; agreementsCount: number; fixed: Array<bigint>; percentBps: Array<number>;  };

export type SettleSaleInstructionDataArgs = { amount: number | bigint; agreementsCount: number; fixed: Array<number | bigint>; percentBps: Array<number>;  };

export function getSettleSaleInstructionDataEncoder(): Encoder<SettleSaleInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['amount', getU64Encoder()], ['agreementsCount', getU8Encoder()], ['fixed', getArrayEncoder(getU64Encoder())], ['percentBps', getArrayEncoder(getU16Encoder())]]), (value) => ({ ...value, discriminator: SETTLE_SALE_DISCRIMINATOR }));
}

export function getSettleSaleInstructionDataDecoder(): Decoder<SettleSaleInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['amount', getU64Decoder()], ['agreementsCount', getU8Decoder()], ['fixed', getArrayDecoder(getU64Decoder())], ['percentBps', getArrayDecoder(getU16Decoder())]]);
}

export function getSettleSaleInstructionDataCodec(): Codec<SettleSaleInstructionDataArgs, SettleSaleInstructionData> {
    return combineCodec(getSettleSaleInstructionDataEncoder(), getSettleSaleInstructionDataDecoder());
}

export type SettleSaleAsyncInput<TAccountPayer extends InstructionSignerInput = InstructionSignerInput, TAccountSeller extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountMint extends InstructionAccountInput = InstructionAccountInput, TAccountPayerToken extends InstructionAccountInput = InstructionAccountInput, TAccountSellerToken extends InstructionAccountInput = InstructionAccountInput, TAccountTokenProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  payer: TAccountPayer;
seller: TAccountSeller;
sellerState?: TAccountSellerState;
mint: TAccountMint;
payerToken: TAccountPayerToken;
sellerToken: TAccountSellerToken;
tokenProgram?: TAccountTokenProgram;
amount: SettleSaleInstructionDataArgs["amount"];
agreementsCount: SettleSaleInstructionDataArgs["agreementsCount"];
fixed: SettleSaleInstructionDataArgs["fixed"];
percentBps: SettleSaleInstructionDataArgs["percentBps"];
}

export async function getSettleSaleInstructionAsync<TAccountPayer extends InstructionSignerInput, TAccountSeller extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountMint extends InstructionAccountInput, TAccountPayerToken extends InstructionAccountInput, TAccountSellerToken extends InstructionAccountInput, TAccountTokenProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: SettleSaleAsyncInput<TAccountPayer, TAccountSeller, TAccountSellerState, TAccountMint, TAccountPayerToken, TAccountSellerToken, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): Promise<SettleSaleInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountPayer, InstructionAccountInputAddress<TAccountPayer>>, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountPayerToken, InstructionAccountInputAddress<TAccountPayerToken>>, ResolvedInstructionAccountMeta<TAccountSellerToken, InstructionAccountInputAddress<TAccountSellerToken>>, ResolvedInstructionAccountMeta<TAccountTokenProgram, InstructionAccountInputAddress<TAccountTokenProgram>>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { payer: { value: input.payer ?? null, isSigner: true, isWritable: false }, seller: { value: input.seller ?? null, isSigner: false, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, mint: { value: input.mint ?? null, isSigner: false, isWritable: false }, payerToken: { value: input.payerToken ?? null, isSigner: false, isWritable: true }, sellerToken: { value: input.sellerToken ?? null, isSigner: false, isWritable: true }, tokenProgram: { value: input.tokenProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.sellerState.value) {
accounts.sellerState.value = await findSellerStatePda({ seller: getAddressFromResolvedInstructionAccount("seller", accounts.seller.value) }, { programAddress });
}
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

return Object.freeze({ accounts: [getAccountMeta("payer", accounts.payer), getAccountMeta("seller", accounts.seller), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("mint", accounts.mint), getAccountMeta("payerToken", accounts.payerToken), getAccountMeta("sellerToken", accounts.sellerToken), getAccountMeta("tokenProgram", accounts.tokenProgram)], data: getSettleSaleInstructionDataEncoder().encode(args as SettleSaleInstructionDataArgs), programAddress } as SettleSaleInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountPayer, InstructionAccountInputAddress<TAccountPayer>>, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountPayerToken, InstructionAccountInputAddress<TAccountPayerToken>>, ResolvedInstructionAccountMeta<TAccountSellerToken, InstructionAccountInputAddress<TAccountSellerToken>>, ResolvedInstructionAccountMeta<TAccountTokenProgram, InstructionAccountInputAddress<TAccountTokenProgram>>>);
}

export type SettleSaleInput<TAccountPayer extends InstructionSignerInput = InstructionSignerInput, TAccountSeller extends InstructionAccountInput = InstructionAccountInput, TAccountSellerState extends InstructionAccountInput = InstructionAccountInput, TAccountMint extends InstructionAccountInput = InstructionAccountInput, TAccountPayerToken extends InstructionAccountInput = InstructionAccountInput, TAccountSellerToken extends InstructionAccountInput = InstructionAccountInput, TAccountTokenProgram extends InstructionAccountInput = InstructionAccountInput> =  {
  payer: TAccountPayer;
seller: TAccountSeller;
sellerState: TAccountSellerState;
mint: TAccountMint;
payerToken: TAccountPayerToken;
sellerToken: TAccountSellerToken;
tokenProgram?: TAccountTokenProgram;
amount: SettleSaleInstructionDataArgs["amount"];
agreementsCount: SettleSaleInstructionDataArgs["agreementsCount"];
fixed: SettleSaleInstructionDataArgs["fixed"];
percentBps: SettleSaleInstructionDataArgs["percentBps"];
}

export function getSettleSaleInstruction<TAccountPayer extends InstructionSignerInput, TAccountSeller extends InstructionAccountInput, TAccountSellerState extends InstructionAccountInput, TAccountMint extends InstructionAccountInput, TAccountPayerToken extends InstructionAccountInput, TAccountSellerToken extends InstructionAccountInput, TAccountTokenProgram extends InstructionAccountInput, TProgramAddress extends Address = typeof GIRO_ACORDOS_PROGRAM_ADDRESS>(input: SettleSaleInput<TAccountPayer, TAccountSeller, TAccountSellerState, TAccountMint, TAccountPayerToken, TAccountSellerToken, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): SettleSaleInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountPayer, InstructionAccountInputAddress<TAccountPayer>>, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountPayerToken, InstructionAccountInputAddress<TAccountPayerToken>>, ResolvedInstructionAccountMeta<TAccountSellerToken, InstructionAccountInputAddress<TAccountSellerToken>>, ResolvedInstructionAccountMeta<TAccountTokenProgram, InstructionAccountInputAddress<TAccountTokenProgram>>> {
  // Program address.
const programAddress = config?.programAddress ?? GIRO_ACORDOS_PROGRAM_ADDRESS;

// Account meta helper.
const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

 // Original accounts.
const originalAccounts = { payer: { value: input.payer ?? null, isSigner: true, isWritable: false }, seller: { value: input.seller ?? null, isSigner: false, isWritable: false }, sellerState: { value: input.sellerState ?? null, isSigner: false, isWritable: true }, mint: { value: input.mint ?? null, isSigner: false, isWritable: false }, payerToken: { value: input.payerToken ?? null, isSigner: false, isWritable: true }, sellerToken: { value: input.sellerToken ?? null, isSigner: false, isWritable: true }, tokenProgram: { value: input.tokenProgram ?? null, isSigner: false, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

return Object.freeze({ accounts: [getAccountMeta("payer", accounts.payer), getAccountMeta("seller", accounts.seller), getAccountMeta("sellerState", accounts.sellerState), getAccountMeta("mint", accounts.mint), getAccountMeta("payerToken", accounts.payerToken), getAccountMeta("sellerToken", accounts.sellerToken), getAccountMeta("tokenProgram", accounts.tokenProgram)], data: getSettleSaleInstructionDataEncoder().encode(args as SettleSaleInstructionDataArgs), programAddress } as SettleSaleInstruction<TProgramAddress, ResolvedInstructionAccountMeta<TAccountPayer, InstructionAccountInputAddress<TAccountPayer>>, ResolvedInstructionAccountMeta<TAccountSeller, InstructionAccountInputAddress<TAccountSeller>>, ResolvedInstructionAccountMeta<TAccountSellerState, InstructionAccountInputAddress<TAccountSellerState>>, ResolvedInstructionAccountMeta<TAccountMint, InstructionAccountInputAddress<TAccountMint>>, ResolvedInstructionAccountMeta<TAccountPayerToken, InstructionAccountInputAddress<TAccountPayerToken>>, ResolvedInstructionAccountMeta<TAccountSellerToken, InstructionAccountInputAddress<TAccountSellerToken>>, ResolvedInstructionAccountMeta<TAccountTokenProgram, InstructionAccountInputAddress<TAccountTokenProgram>>>);
}

export type ParsedSettleSaleInstruction<TProgram extends string = typeof GIRO_ACORDOS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
payer: TAccountMetas[0];
seller: TAccountMetas[1];
sellerState: TAccountMetas[2];
mint: TAccountMetas[3];
payerToken: TAccountMetas[4];
sellerToken: TAccountMetas[5];
tokenProgram: TAccountMetas[6];
};
data: SettleSaleInstructionData; };

export function parseSettleSaleInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedSettleSaleInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 7 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { payer: getNextAccount(), seller: getNextAccount(), sellerState: getNextAccount(), mint: getNextAccount(), payerToken: getNextAccount(), sellerToken: getNextAccount(), tokenProgram: getNextAccount() }, data: getSettleSaleInstructionDataDecoder().decode(instruction.data) };
}