import {AreaIcon} from './AreaIcon';
import {defaultPrefs,usePrefs,type UiPrefs} from './uiPrefs';
const sizes:[UiPrefs['textSize'],string,string][]=[['normal','Padrão','Tamanho recomendado para a maioria das telas.'],['large','Grande','Textos e botões cerca de 15% maiores.'],['xlarge','Muito grande','Textos e botões cerca de 30% maiores.']];
export function Accessibility(){
 const [prefs,update]=usePrefs();
 return <section className="panel accessibility-panel" aria-labelledby="accessibility-title"><h2 id="accessibility-title"><AreaIcon name="acessibilidade"/>Acessibilidade</h2><p className="muted">Ajustes de leitura guardados só neste navegador. Você também pode usar o zoom do navegador (Ctrl + / Ctrl −).</p>
 <fieldset className="choice-group"><legend>Tamanho do texto</legend><div className="size-options">{sizes.map(([value,label,hint])=><label key={value} className={`size-option${prefs.textSize===value?' selected':''}`}><input type="radio" name="text-size" value={value} checked={prefs.textSize===value} onChange={()=>update({textSize:value})}/><span className={`size-sample size-${value}`} aria-hidden="true">A</span><span><strong>{label}</strong><small>{hint}</small></span></label>)}</div></fieldset>
 <fieldset className="choice-group"><legend>Leitura</legend><label className="check toggle-row"><input type="checkbox" checked={prefs.contrast==='high'} onChange={e=>update({contrast:e.target.checked?'high':'normal'})}/><span><strong>Alto contraste</strong><small>Textos mais escuros, bordas mais fortes e links sublinhados.</small></span></label><label className="check toggle-row"><input type="checkbox" checked={prefs.motion==='reduce'} onChange={e=>update({motion:e.target.checked?'reduce':'normal'})}/><span><strong>Reduzir animações</strong><small>Remove transições e movimentos da interface.</small></span></label><label className="check toggle-row"><input type="checkbox" checked={!prefs.hideStructure} onChange={e=>update({hideStructure:!e.target.checked})}/><span><strong>Mostrar “Estrutura atualizada” em Receber</strong><small>O mapa das áreas também fica em Mais → Como o GIRO está organizado.</small></span></label></fieldset>
 <button className="secondary" onClick={()=>update({textSize:defaultPrefs.textSize,contrast:defaultPrefs.contrast,motion:defaultPrefs.motion,hideStructure:defaultPrefs.hideStructure})}>Restaurar padrão</button></section>;
}
