import {brDate} from './display';
import {useState} from 'react';
import type {Actor,Commitment} from '../domain/models';
import {money,priorityLabel} from '../domain/finance';
import {parseMoney,parsePercent} from '../domain/validation';
import {AgreementForm} from './AgreementForm';
interface Props {c:Commitment;actor:Actor;busy:boolean;post:(path:string,input:unknown)=>Promise<boolean>;onError:(message:string)=>void}
export function AgreementActions({c,actor,busy,post,onError}:Props){
 const [requesting,setRequesting]=useState(false);const [editing,setEditing]=useState(false);const pending=c.renegotiations?.find(r=>r.status==='pending');
 if(c.demo)return null;
 return <><p className="note">Simulação local: visualizando como {actor==='seller'?'vendedor':'fornecedor'}. Não há autenticação real ou transferência.{c.legacyAcceptance&&' Acordo preservado da Fase 2, sem aceite bilateral histórico.'}</p>{c.status==='draft'&&actor==='seller'&&<><div className="form-actions"><button className="primary" disabled={busy} onClick={()=>post('agreements/submit',{id:c.id,actor})}>Enviar para aceite</button><button className="secondary" onClick={()=>setEditing(!editing)}>Editar rascunho</button></div>{editing&&<AgreementForm initial={c} busy={busy} onClose={()=>setEditing(false)} onError={onError} onSave={input=>post('agreements/edit',{...input as object,id:c.id,actor})}/>}</>}{c.status==='awaiting_acceptance'&&(actor==='supplier'?<div className="form-actions"><button className="primary" disabled={busy} onClick={()=>post('agreements/decision',{id:c.id,actor,decision:'accept'})}>Aceitar compromisso</button><button className="secondary" disabled={busy} onClick={()=>post('agreements/decision',{id:c.id,actor,decision:'refuse'})}>Recusar compromisso</button></div>:<p>Aguardando o fornecedor analisar e aceitar.</p>)}{c.status==='active'&&!pending&&<button className="secondary" onClick={()=>setRequesting(!requesting)}>Solicitar renegociação</button>}{pending&&<section className="note"><h3>Proposta aguardando resposta</h3><p>Separar: {pending.previous.rateBps/100}% → {pending.next.rateBps/100}%<br/>Dívida: {money(pending.previous.original)} → {money(pending.next.original)}<br/>Vencimento: {brDate(pending.previous.due)} → {brDate(pending.next.due)}<br/>Prioridade: {priorityLabel(pending.previous.priority)} → {priorityLabel(pending.next.priority)}</p>{pending.reason&&<p>Motivo: {pending.reason}</p>}{pending.requester!==actor?<div className="form-actions"><button className="primary" disabled={busy} onClick={()=>post('renegotiations/decision',{id:c.id,proposalId:pending.id,actor,decision:'accept'})}>Aceitar renegociação</button><button className="secondary" disabled={busy} onClick={()=>post('renegotiations/decision',{id:c.id,proposalId:pending.id,actor,decision:'refuse'})}>Recusar renegociação</button></div>:<p>A outra parte precisa aceitar ou recusar. O acordo atual continua valendo.</p>}</section>}{requesting&&c.status==='active'&&!pending&&<form onSubmit={async e=>{
 e.preventDefault();const f=new FormData(e.currentTarget);
 try{if(await post('renegotiations/request',{id:c.id,actor,original:parseMoney(String(f.get('original'))),rateBps:parsePercent(String(f.get('percent'))),priority:Number(f.get('priority')),due:f.get('due'),reason:f.get('reason')}))setRequesting(false);}
 catch(error){onError(error instanceof Error?error.message:'Revise a proposta.');}
 }}><h3>Propor novas condições</h3><label>Valor da dívida (R$)<input name="original" defaultValue={c.original/100} inputMode="decimal" required/></label><label>Quanto separar de cada venda? (%)<input name="percent" defaultValue={c.rateBps/100} inputMode="decimal" required/></label><label>Vencimento proposto<input name="due" type="date" defaultValue={c.due} required/></label><label>Prioridade<select name="priority" defaultValue={c.priority}><option value="1">Alta</option><option value="2">Média</option><option value="3">Baixa</option>{c.priority>3&&<option value={c.priority}>Prioridade anterior</option>}</select></label><label>Motivo (opcional)<textarea name="reason" maxLength={500}/></label><button className="primary" disabled={busy}>Enviar proposta local</button><p className="muted">O acordo só muda após a decisão da outra parte. Vendas já registradas mantêm as regras capturadas originalmente.</p></form>}</>;
}
