import {useState} from 'react';
import type {Commitment} from '../domain/models';
import {money} from '../domain/finance';
import {educationalSimulation,educationalDebtRemaining} from '../domain/planning';
import {parseMoney,parsePercent} from '../domain/validation';
interface Props {initial?:Commitment;busy:boolean;onSave:(input:unknown)=>Promise<boolean>;onClose:()=>void;onError:(message:string)=>void}
export function AgreementForm({initial,busy,onSave,onClose,onError}:Props){
 const [supplier,setSupplier]=useState(initial?.supplier??'');const [debt,setDebt]=useState(initial?String(initial.original/100):'');const [hasPaid,setHasPaid]=useState(Boolean(initial?.paid));const [paid,setPaid]=useState(initial?String(initial.paid/100):'');const [percent,setPercent]=useState(String((initial?.rateBps??2000)/100));const [custom,setCustom]=useState(!['10','20','30'].includes(percent));const [saleValue,setSaleValue]=useState('80');
 let rate:number|undefined;let debtRemaining:number|undefined;let simulated:{destination:number;available:number}|undefined;
 try{rate=parsePercent(percent);if(debt.trim())debtRemaining=educationalDebtRemaining(parseMoney(debt),hasPaid?parseMoney(paid):0);simulated=educationalSimulation(parseMoney(saleValue),rate,debtRemaining);}catch{rate=undefined;simulated=undefined;}
 return <form onSubmit={async e=>{
  e.preventDefault();const f=new FormData(e.currentTarget);
  try{const debtAmount=parseMoney(debt);const alreadyPaid=hasPaid?parseMoney(paid):0;const payload={supplier,debtAmount,alreadyPaid,rateBps:parsePercent(percent),priority:Number(f.get('priority')),due:f.get('due'),status:initial?'draft':f.get('saveMode')};if(initial)Object.assign(payload,{original:debtAmount});if(await onSave(payload))onClose();}
  catch(error){onError(error instanceof Error?error.message:'Revise os campos.');}
 }}><label>Fornecedor<input value={supplier} onChange={e=>setSupplier(e.target.value)} maxLength={120} required disabled={Boolean(initial)}/></label><label>Valor da dívida (R$)<input value={debt} onChange={e=>setDebt(e.target.value)} inputMode="decimal" placeholder="600,00" required/></label><label>Já pagou alguma parte?<select value={hasPaid?'yes':'no'} onChange={e=>setHasPaid(e.target.value==='yes')} disabled={Boolean(initial)}><option value="no">Não</option><option value="yes">Sim</option></select></label>{hasPaid&&<label>Quanto já foi pago? (R$)<input value={paid} onChange={e=>setPaid(e.target.value)} inputMode="decimal" required readOnly={Boolean(initial)}/></label>}<fieldset><legend>Quanto separar de cada venda?</legend><div className="form-actions">{['10','20','30'].map(p=><button type="button" key={p} className={!custom&&percent===p?'primary':'secondary'} aria-pressed={!custom&&percent===p} onClick={()=>{setCustom(false);setPercent(p);}}>{p}%</button>)}<button type="button" className={custom?'primary':'secondary'} aria-pressed={custom} onClick={()=>setCustom(true)}>Outro</button></div>{custom&&<label>Porcentagem (%)<input value={percent} onChange={e=>setPercent(e.target.value)} inputMode="decimal" required/></label>}{rate!==undefined&&<div className="note">{[5000,10000,20000].map(amount=><p key={amount}>Venda de {money(amount)} → {money(educationalSimulation(amount,rate!,debtRemaining).destination)} para {supplier||'o fornecedor'}</p>)}</div>}</fieldset><details><summary>Simular uma venda — sem salvar</summary><label>Valor da venda (R$)<input value={saleValue} onChange={e=>setSaleValue(e.target.value)} inputMode="decimal"/></label>{simulated&&<p className="note">{supplier||'O fornecedor'} receberia: <b>{money(simulated.destination)}</b><br/>Restaria para você e outras regras: <b>{money(simulated.available)}</b><br/>Esta prévia não aplica comissão ou outras regras, não cria venda e não altera o banco.</p>}</details><label>Prioridade<select name="priority" defaultValue={initial?.priority??2}><option value="1">Alta</option><option value="2">Média</option><option value="3">Baixa</option>{initial&&initial.priority>3&&<option value={initial.priority}>Prioridade anterior</option>}</select></label><label>Vencimento<input name="due" type="date" defaultValue={initial?.due} required/></label>{!initial&&<label>Salvar como<select name="saveMode" defaultValue="awaiting_acceptance"><option value="awaiting_acceptance">Enviar para aceite local do fornecedor</option><option value="draft">Rascunho</option></select></label>}<p className="note">Ao enviar, você aceita estas condições na simulação. O fornecedor ainda precisa aceitar antes que valores das vendas sejam destinados ao compromisso.</p><div className="form-actions"><button className="primary" disabled={busy}>Salvar compromisso</button><button type="button" className="secondary" onClick={onClose}>Fechar</button></div></form>;
}
