import {useState} from 'react';
import type {AgreementTerms,Commitment,State} from '../domain/models';
import {parseMoney,parsePercent} from '../domain/validation';
import {allocationDisclosure} from '../domain/consent';
import {TermsReview} from './Invitation';
export function ChangeRequest({c,state,busy,post,onClose}:{c:Commitment;state:State;busy:boolean;post:(path:string,input:unknown)=>Promise<boolean>;onClose:()=>void}){
 const [paymentMethod,setPaymentMethod]=useState(c.paymentMethod??'');const [amount,setAmount]=useState(String(c.original/100));const [rate,setRate]=useState(String(c.rateBps/100));const [due,setDue]=useState(c.due);const [priority,setPriority]=useState(c.priority);const [reason,setReason]=useState('');const [review,setReview]=useState<AgreementTerms>();const [error,setError]=useState('');const [ack,setAck]=useState(false);
 return <form className="wizard" onSubmit={async e=>{e.preventDefault();setError('');try{if(!review){const next={original:parseMoney(amount),rateBps:parsePercent(rate),due,priority,paymentMethod:paymentMethod.trim()||undefined};if(next.original<=c.paid||next.original<c.paid+(c.cashPending??0))throw Error('O valor deve manter saldo a pagar e todas as destinações físicas já existentes.');setReview(next);return;}if(await post('invitations/change',{id:c.id,...review,reason,acknowledged:ack}))onClose();else setError('Não foi possível enviar a proposta. Revise as condições; os campos foram mantidos.');}catch(e){setError((e as Error).message);}}}><h3>Pedir mudança</h3>{!review?<><label>Valor da dívida (R$)<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/></label><label>Parte das vendas (%)<input value={rate} onChange={e=>setRate(e.target.value)} inputMode="decimal" required/></label><label>Vencimento proposto<input type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><label>Prioridade<select value={priority} onChange={e=>setPriority(Number(e.target.value))}><option value={1}>Alta</option><option value={2}>Média</option><option value={3}>Baixa</option>{priority>3&&<option value={priority}>Prioridade anterior</option>}</select></label><label>Forma de pagamento proposta<input value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} maxLength={120}/></label><label>Motivo (opcional)<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label></>:<><h3>Atual</h3><TermsReview terms={c}/><h3>Proposto</h3><TermsReview terms={review}/><p className="note">{allocationDisclosure(state,review,c.id).text}</p><label className="check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Entendi as condições propostas e o limite disponível.</label><p>O acordo atual continua valendo até a outra parte aceitar. Vendas anteriores preservam suas regras.</p></>}{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy||(!!review&&!ack)}>{review?`Enviar mudança para ${c.supplier}`:'Revisar proposta'}</button>{review&&<button type="button" className="secondary" onClick={()=>{setReview(undefined);setAck(false);}}>Voltar</button>}<button type="button" className="secondary" onClick={onClose}>Cancelar</button></div></form>;
}
