import {useState} from 'react';
import type {AgreementEvent,AgreementTerms,Renegotiation} from '../domain/models';
import {money} from '../domain/finance';
import {SupplierChangeForm,TermsReview} from './Invitation';
export interface ConsultView {publicId:string;recipient:string;paid:number;remaining:number;currentTerms:AgreementTerms;history:AgreementEvent[];changes:Renegotiation[];canRequestChange:boolean}
export function CommitmentConsult(){
 const [id,setId]=useState(''),[view,setView]=useState<ConsultView>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel"><h2>Consultar compromisso</h2><p>Digite o ID para consultar as condições e pedir uma mudança. A consulta é local e não comprova a identidade de quem solicita.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setView(undefined);try{const r=await fetch('/api/commitments/consult',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id.trim()})}),v=await r.json();if(!r.ok)throw Error(v.error);setView(v);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Digite o ID do compromisso<input value={id} onChange={e=>setId(e.target.value)} required placeholder="COMP-2026-000123"/></label><button className="primary" disabled={busy}>{busy?'Consultando…':'Consultar compromisso'}</button></form>{error&&<p className="error" role="alert">{error}</p>}{view&&<div className="commitment-detail"><p className="eyebrow">{view.publicId}</p><h3>{view.recipient}</h3><TermsReview terms={view.currentTerms}/><p>Pago registrado: {money(view.paid)} · Saldo restante: {money(view.remaining)}</p>{view.canRequestChange?<SupplierChangeForm commitmentId={view.publicId} view={view} onSaved={setView}/>:<p className="note">Não é possível enviar outra mudança enquanto houver uma proposta pendente ou o compromisso não estiver ativo.</p>}<details><summary>Histórico de alterações</summary>{view.changes.length?view.changes.map(r=><article className="history-item" key={r.id}><strong>{({pending:'Pendente',accepted:'Aceita',refused:'Recusada',obsolete:'Cancelada'})[r.status]}</strong><p>{new Date(r.requestedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · {r.requester==='seller'?'Titular':'Outra parte'} · {r.reason}</p>{r.decidedAt&&<p>Decisão: {new Date(r.decidedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>}<h4>Anterior</h4><TermsReview terms={r.previous}/><h4>Proposta</h4><TermsReview terms={r.next}/></article>):<p>Nenhuma alteração registrada.</p>}</details></div>}</section>;
}
