import {useEffect,useRef,useState} from 'react';
import type {AgreementTerms,State} from '../domain/models';
import {money,today} from '../domain/finance';
import {parseMoney,parsePercent,validDate} from '../domain/validation';
import {allocationDisclosure} from '../domain/consent';
import {TermsReview} from './Invitation';
import {ContactForm} from './Contacts';
import {ImportDocument} from './ImportDocument';
interface Props {state:State;busy:boolean;post:(path:string,input:unknown)=>Promise<boolean>;onClose:()=>void}
const titles=['Com quem é o compromisso?','Quanto você precisa pagar?','Até quando?','Quanto das vendas será destinado?','Confira antes de enviar'];
export function CommitmentWizard({state,busy,post,onClose}:Props){
 const [step,setStep]=useState(0),[contactId,setContact]=useState(''),[amount,setAmount]=useState(''),[paid,setPaid]=useState('0'),[due,setDue]=useState(today()),[rate,setRate]=useState('20'),[priority,setPriority]=useState(0),[testAmount,setTest]=useState('100'),[ack,setAck]=useState(false),[error,setError]=useState(''),[selectNew,setSelectNew]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null),knownContacts=useRef(new Set(state.contacts?.map(c=>c.id)));
 useEffect(()=>{heading.current?.focus();},[step]);
 useEffect(()=>{if(selectNew){const added=[...(state.contacts??[])].reverse().find(c=>!knownContacts.current.has(c.id));if(added){setContact(added.id);setSelectNew(false);}}if(selectNew)knownContacts.current=new Set(state.contacts?.map(c=>c.id));},[state.contacts,selectNew]);
 const selectedMember=state.members.find(m=>!m.disabledAt&&'member:'+m.id===contactId);const contact=state.contacts?.find(c=>c.id===contactId)??(selectedMember?{id:contactId,name:selectedMember.name,type:'collaborator' as const}:undefined);let rateBps=0,sample:number|null=null,original=0,alreadyPaid=0;
 try{rateBps=parsePercent(rate);}catch{/* incomplete field */}
 try{original=parseMoney(amount);alreadyPaid=parseMoney(paid);}catch{/* incomplete field */}
 try{sample=Math.min(parseMoney(testAmount),Math.floor(parseMoney(testAmount)*rateBps/10000),Math.max(0,original-alreadyPaid));}catch{/* incomplete field */}
 const terms:AgreementTerms={original,rateBps,priority,due},disclosure=allocationDisclosure(state,terms);
 const next=()=>{setError('');try{if(step===0&&!contact)throw Error('Selecione um fornecedor. Se ele não aparecer, cadastre à esquerda.');if(step===1){const total=parseMoney(amount),settled=parseMoney(paid);if(total<=0||settled>total)throw Error('Informe uma dívida positiva; o já pago não pode superar o total.');}if(step===2&&!validDate(due))throw Error('Informe uma data válida.');if(step===3){if(![1,2,3].includes(priority))throw Error('Escolha a prioridade.');if(parsePercent(rate)<=0)throw Error('Informe uma porcentagem maior que zero.');if(disclosure.conflict)throw Error(disclosure.text);}setStep(step+1);}catch(e){setError((e as Error).message);}};
 const simulation=<section className="panel sale-simulator"><p className="eyebrow">VEJA COMO FICA</p><h2>Simule uma venda</h2><p>Para {contact?.name??'o fornecedor selecionado'}</p><label>Valor da venda para testar (R$)<input value={testAmount} onChange={e=>setTest(e.target.value)} inputMode="decimal"/></label><div className="simulation-result"><span>Para este compromisso ({rateBps/100}%)</span><strong>{sample===null?'Preencha um valor válido':money(sample)}</strong></div><p className="muted">Informe primeiro o valor da dívida. O cálculo é limitado ao que falta pagar.</p><p className="note">Esta simulação não registra venda. Outras regras da equipe e dos acordos também precisam caber na venda; um conflito bloqueia o envio.</p></section>;
 return <div className="commitment-flow">{step===0&&<section className="panel supplier-registration"><p className="eyebrow">PRIMEIRO, CADASTRE SE PRECISAR</p><h2>Adicionar fornecedor</h2><p className="muted">O fornecedor já está cadastrado? Selecione na caixa ao lado.</p><ContactForm defaultType="supplier" post={post} busy={busy} onSaved={()=>setSelectNew(true)}/></section>}<section className="panel wizard"><div className="section-title"><p className="eyebrow">NOVO COMPROMISSO · ETAPA {step+1} DE 5</p><button className="text-button" onClick={onClose}>Fechar</button></div><progress value={step+1} max={5}/><h2 ref={heading} tabIndex={-1}>{titles[step]}</h2><form onSubmit={async e=>{e.preventDefault();if(step<4){next();return;}setError('');try{if(!ack)throw Error('Confirme que entendeu as condições.');if(await post('invitations/send',{contactId,debtAmount:parseMoney(amount),alreadyPaid:parseMoney(paid),due,rateBps:parsePercent(rate),priority,acknowledged:ack}))onClose();else setError('Não foi possível enviar. Seus campos foram mantidos.');}catch(e){setError((e as Error).message);}}}>
 {step===0&&<><label>Fornecedor ou colaborador<select value={contactId} onChange={e=>setContact(e.target.value)}><option value="">Selecione uma pessoa cadastrada</option>{state.contacts?.map(c=><option key={c.id} value={c.id}>{c.name} ({c.type==='collaborator'?'Colaborador':'Fornecedor / contato'})</option>)}{state.members.filter(m=>!m.demo&&!m.disabledAt&&!state.contacts?.some(c=>c.memberId===m.id||c.id===m.contactId)).map(m=><option key={m.id} value={'member:'+m.id}>{m.name} (Colaborador)</option>)}</select></label><p className="note">O nome não aparece? Cadastre o fornecedor primeiro na caixa à esquerda. Ele aparecerá aqui para você continuar.</p><details><summary>Importar documento</summary><ImportDocument busy={busy} post={post}/></details></>}
 {step===1&&<><label>Valor total da dívida (R$)<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/></label><label>Valor já pago (R$, opcional)<input value={paid} onChange={e=>setPaid(e.target.value)} inputMode="decimal"/></label><p className="muted">Já pago é um valor informado por você.</p></>}
 {step===2&&<label>Vencimento<input type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label>}
 {step===3&&<><fieldset><legend>Parte das vendas</legend><div className="form-actions">{[10,15,20,25].map(v=><button type="button" className={rate===String(v)?'primary':'secondary'} key={v} aria-pressed={rate===String(v)} onClick={()=>setRate(String(v))}>{v}%</button>)}</div><label>Outro percentual (%)<input value={rate} onChange={e=>setRate(e.target.value)} inputMode="decimal" required/></label></fieldset><label>Prioridade<select value={priority} onChange={e=>setPriority(Number(e.target.value))}><option value={0}>Escolha a prioridade</option><option value={1}>Alta</option><option value={2}>Média</option><option value={3}>Baixa</option></select></label><p className="muted">Prioridade organiza o atendimento. Não permite reduzir silenciosamente um acordo aceito; regras incompatíveis são bloqueadas.</p></>}
 {step===4&&<><h3>{contact?.name}</h3><TermsReview terms={terms}/><p>Já pago informado: {money(alreadyPaid)} · Falta pagar: {money(original-alreadyPaid)}</p><details><summary>Condições da distribuição</summary><p className={disclosure.conflict?'error':'note'}>{disclosure.text}</p></details><p className="note">Depois do aceite, qualquer alteração exige uma nova proposta para a outra parte.</p><label className="check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Entendi as condições e quero enviar este compromisso.</label></>}
 {error&&<p id="wizard-error" className="error" role="alert">{error}</p>}<div className="form-actions">{step>0&&<button type="button" className="secondary" onClick={()=>{setStep(step-1);setError('');setAck(false);}}>Voltar</button>}{step===4&&<button type="button" className="secondary" disabled={busy} onClick={async()=>{if(await post('invitations/draft',{contactId,debtAmount:parseMoney(amount),alreadyPaid:parseMoney(paid),due,rateBps:parsePercent(rate),priority}))onClose();}}>Salvar rascunho</button>}<button className="primary" disabled={busy||(step===4&&!ack)}>{step<4?'Continuar':`Enviar para ${contact?.name??'a pessoa'} aceitar`}</button></div></form></section>{step>0&&simulation}</div>;
}
