import {useEffect,useRef} from 'react';
import type {Notification,State} from '../domain/models';
import {notificationFeed,notificationTarget} from '../domain/notifications';
import {CheckCircle2,AlertCircle,Clock3,Bell} from 'lucide-react';
import {friendlyMessage} from './display';
type Post=(path:string,input:unknown)=>Promise<boolean>;
const badges:Record<string,string>={ACTION_REQUIRED:'Ação pendente',WARNING:'Atenção',SUCCESS:'Concluído',INFO:'Informação'};
/** Marca, uma a uma, as notificações não lidas usando o endpoint local existente. */
export async function markAllRead(rows:Notification[],post:Post){for(const n of rows.filter(n=>!n.readAt))if(!await post('notifications/read',{id:n.id}))return;}
function NotificationIcon({type}:{type?:string}){const Icon=type==='SUCCESS'?CheckCircle2:type==='WARNING'?AlertCircle:type==='ACTION_REQUIRED'?Clock3:Bell;return <span className={`notification-symbol notification-symbol-${type??'INFO'}`}><Icon size={23} aria-hidden="true"/></span>;}
export function NotificationPanel({state,busy,post,onClose,onOpen}:{state:State;busy:boolean;post:Post;onClose:()=>void;onOpen:(route:string,id?:string)=>void}){
 const box=useRef<HTMLElement>(null);useEffect(()=>{box.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};const outside=(e:PointerEvent)=>{if(box.current&&!box.current.contains(e.target as Node)&&!(e.target as Element).closest('.notification-button'))onClose();};document.addEventListener('keydown',key);document.addEventListener('pointerdown',outside);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('pointerdown',outside);};},[onClose]);
 const rows=notificationFeed(state),unread=rows.filter(n=>!n.readAt).length;
 return <section ref={box} tabIndex={-1} className="notification-dropdown" aria-labelledby="notification-title"><div className="section-title"><h2 id="notification-title">Notificações <span className="sr-only">{unread} não lidas. Pressione Esc para fechar.</span></h2><button className="text-button" onClick={()=>{onOpen('mais/notificacoes');onClose();}}>Ver todas</button></div>{unread>0&&<button className="text-button mark-all" disabled={busy} onClick={()=>markAllRead(rows,post)}>Marcar todas como lidas ({unread})</button>}<ul className="notification-list">{rows.map(n=>{const type=n.type??'INFO';return <li key={n.id} className={n.readAt?'notification read':'notification unread'}><NotificationIcon type={type}/><button className="notification-open" onClick={()=>{const target=notificationTarget(state,n);onOpen(target.route,target.id);onClose();}}><strong>{!n.readAt&&<span className="sr-only">Não lida: </span>}{friendlyMessage(state,n)}</strong></button><span className="notification-meta"><span className={`notification-badge badge-${type}`}>{badges[type]??badges.INFO}</span><small>{new Date(n.createdAt).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></span>{!n.readAt&&<button className="text-button notification-read" disabled={busy} onClick={()=>post('notifications/read',{id:n.id})}>Marcar como lida</button>}</li>;})}{!rows.length&&<li className="notification-empty">Nenhuma notificação.</li>}</ul></section>;
}
