import {brDate} from './display';
import {AreaIcon} from './AreaIcon';
import {memberSummary} from '../domain/team';
import type {State} from '../domain/models';
import {money,summary} from '../domain/finance';
import {financialLabels,financialStatus,commitmentId,commitmentType,matches,planStatus} from '../domain/records';
import {usePageSearch} from './PageSearch';
export function OrganizeSummary({state}:{state:State}){
 const query=usePageSearch(),total=summary(state),items=[...state.commitments.filter(c=>!c.demo&&!['draft','awaiting_acceptance','cancelled','pending'].includes(c.status)).map(c=>({id:commitmentId(c),name:c.supplier,kind:commitmentType(state,c)==='collaborator'?'Compromisso com colaborador':commitmentType(state,c)==='other'?'Outro compromisso':'Compromisso com fornecedor',original:c.original,paid:c.paid,reserved:c.cashPending??0,remaining:c.original-c.paid,status:financialStatus(c.original,c.paid,c.due),due:c.due})),...state.plans.filter(p=>!p.demo&&!p.archivedAt).map(p=>({id:p.id,name:p.name,kind:p.kind==='account'?'Conta':'Meta',original:p.target??p.amount,paid:p.kind==='account'?p.accountPaid??0:0,reserved:p.amount,remaining:Math.max(0,(p.target??p.amount)-(p.kind==='account'?p.accountPaid??0:p.amount)),status:planStatus(p),due:p.targetDate??''})),...state.members.filter(m=>!m.demo).map(m=>{const s=memberSummary(state,m.id);return {id:m.id,name:m.name,kind:'Remuneração de colaborador',original:s.generated,paid:s.paid,reserved:s.receivable,remaining:s.receivable,status:financialStatus(s.generated,s.paid),due:''};}).filter(m=>m.original>0)];
 const sum=(rows:typeof items,key:'remaining'|'paid'|'reserved'|'original')=>rows.reduce((a,i)=>a+i[key],0);const pending=items.filter(i=>i.remaining>0),completed=items.filter(i=>i.remaining===0);
 return <section className="panel"><h2><AreaIcon name="resumo"/>Resumo consolidado</h2><p className="muted">Consulta automática. Reservas e pagamentos aparecem separados; as operações ficam nas abas anteriores.</p><div className="summary-grid">{[['Livre para usar',total.free],['Reservas pessoais',total.planned],['Obrigações e metas pendentes',sum(pending,'remaining')],['Valores atrasados',sum(items.filter(i=>i.status==='overdue'),'remaining')],['Pagamentos registrados',sum(items,'paid')],['Objetivos e obrigações concluídos',sum(completed,'original')]].map(([label,value])=><div key={label}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</div>{[['Pendentes',pending],['Concluídos',completed]].map(([title,group])=><section key={String(title)} className="summary-section"><h2>{String(title)}</h2>{['Compromisso com fornecedor','Compromisso com colaborador','Conta','Meta','Remuneração de colaborador','Outro compromisso'].filter(kind=>(group as typeof items).some(i=>i.kind===kind&&matches(query,i.name,i.id,i.kind,financialLabels[i.status],i.due))).map(kind=><div key={kind}><h3>{kind}s</h3>{(group as typeof items).filter(i=>i.kind===kind&&matches(query,i.name,i.id,i.kind,financialLabels[i.status],i.due)).map(i=><article className="summary-row" key={i.id}><div><strong>{i.name}</strong><small>{i.id} · {brDate(i.due)}</small></div><span>Pago {money(i.paid)} · Reservado {money(i.reserved)} · Restante {money(i.remaining)}</span><span className={`status-badge status-${i.status}`}>{i.kind==='Meta'&&i.status==='partial'?'Em progresso':financialLabels[i.status]}</span></article>)}</div>)}</section>)}<h3>Remuneração de colaboradores</h3><p>Diárias geradas: {money(total.dailyCost)} · Entregas em dinheiro registradas: {money((state.dailyWages??[]).reduce((a,w)=>a+w.paid,0))} · Comissões geradas: {money(total.commission)}.</p><p className="note">Reserva integral de uma conta encerra a necessidade de reservar mais, mas não prova pagamento. Uma conta só consta como quitada quando o total pago chega ao valor original.</p></section>;
}
