import {SaleParticipation} from './SaleParticipation';
import {useEffect,useRef,useState} from 'react';
import {CheckCircle2} from 'lucide-react';
import type {State} from '../domain/models';
import {invitationQR} from '../domain/qr';
import {isActive,money} from '../domain/finance';
import {parseMoney} from '../domain/validation';
import {SaleReceipt} from './SalesHistory';
import {useChainStatus} from './ChainSeal';
import {connect,discoverWallets,signAndSend} from './wallet';
/** Solana Pay (só com o validador local ligado): a carteira lê o QR, assina e paga com token BRL-T de TESTE. */
/** Solana Pay (rede ligada): QR para a carteira do celular OU pagamento direto pela Phantom deste navegador. */
function SolanaPay({token,onPaid}:{token:string;onPaid:(v:CheckoutView)=>void}){
 const status=useChainStatus();const chain=`solana:${status?.cluster==='mainnet'?'mainnet':status?.cluster??'devnet'}`;
 const url=`solana:${encodeURIComponent(`${location.origin}/api/solana-pay/${token}`)}`;
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [msg,setMsg]=useState('');
 useEffect(()=>{const check=async()=>{try{const r=await fetch(`/api/solana-pay/${token}/verificar`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const v=await r.json();if(r.ok&&v.paid)onPaid(v);}catch{/* tenta de novo */}};const t=setInterval(check,4000);return()=>clearInterval(t);},[token,onPaid]);
 const payHere=async()=>{setBusy(true);setError('');setMsg('');try{
  const w=discoverWallets()[0];if(!w)throw Error('Nenhuma carteira encontrada neste navegador. Instale a Phantom (modo Devnet) e recarregue.');
  const a=await connect(w);setMsg('Montando a cobrança…');
  const r=await fetch(`/api/solana-pay/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account:a.address})});const v=await r.json();if(!r.ok)throw Error(v.error);
  setMsg('Aprove o pagamento na Phantom…');await signAndSend(w,a,v.transaction,chain);setMsg('Pago! Confirmando na rede…');
  for(let i=0;i<20;i++){const c=await fetch(`/api/solana-pay/${token}/verificar`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const cv=await c.json();if(c.ok&&cv.paid){onPaid(cv);return;}await new Promise(ok=>setTimeout(ok,1500));}
  setMsg('Pagamento enviado. A rede ainda está confirmando; esta tela atualiza sozinha.');
 }catch(e){setError((e as Error).message);setMsg('');}finally{setBusy(false);}};
 return <section className="note solana-pay"><h3>Pagar com carteira Solana</h3>
  <button className="primary big-action" disabled={busy} onClick={payHere}>{busy?'Aguarde…':'Pagar agora com a Phantom deste navegador'}</button>
  {msg&&<p role="status">{msg}</p>}{error&&<p className="error" role="alert">{error}</p>}
  <p className="muted">Ou leia o QR com a Phantom do celular:</p><QR url={url}/>
  <p className="muted">{status?.cluster==='mainnet'?'Rede Solana — dinheiro REAL.':'Rede de TESTE (Devnet), token sem valor real.'} O valor vai direto para cada carteira: fornecedoras, comissão e o negócio.</p><a className="secondary" href={url}>Abrir na carteira</a></section>;
}
function QR({url}:{url:string}){const matrix=invitationQR(url);return <svg className="payment-qr" viewBox="0 0 45 45" role="img" aria-label="QR da cobrança local"><rect width="45" height="45" fill="white"/>{matrix.flatMap((row,y)=>row.map((on,x)=>on?<rect key={`${x}-${y}`} x={x+4} y={y+4} width="1" height="1" fill="#003e30"/>:null))}</svg>;}
const storageKey='giro-current-charge-request';
function rememberRequest(id:string){try{if(typeof sessionStorage!=='undefined')sessionStorage.setItem(storageKey,id);}catch{/* storage may be unavailable */}return id;}
function currentRequest(){try{if(typeof sessionStorage!=='undefined'){const id=sessionStorage.getItem(storageKey);if(id&&/^[a-f0-9-]{36}$/.test(id))return id;}}catch{/* storage may be unavailable */}return rememberRequest(crypto.randomUUID());}
export function ReceiveQR({state,busy,post,onError,onNavigate}:{state:State;busy:boolean;post:(path:string,input:unknown)=>Promise<boolean>;onError:(s:string)=>void;onNavigate?:(route:string)=>void}){const chainStatus=useChainStatus();const chainOn=!!chainStatus?.enabled&&chainStatus.cluster!=='simulado'&&chainStatus.cluster!=='disabled';
 const [amount,setAmount]=useState(''),[hasParticipation,setParticipation]=useState(false),[selected,setSelected]=useState<string[]>([]);let cents=0;try{cents=parseMoney(amount);}catch{}
 const [requestId,setRequest]=useState(currentRequest),started=useRef<string|null>(null);useEffect(()=>{if(started.current!==requestId){started.current=requestId;void post('payments/create',{requestId}).then(ok=>{if(!ok)started.current=null;});}},[requestId]);
 const p=state.paymentRequests?.find(p=>p.requestId===requestId),sale=state.sales.find(s=>s.id===p?.saleId),url=p?`${location.origin}/pagar/${p.token}`:'',agreements=sale?sale.commitmentRules?.length??0:state.commitments.filter(c=>!c.demo&&isActive(c)).length;
 const home=()=>onNavigate?onNavigate('inicio'):location.hash='inicio';
 if(sale?.paidAt)return <section className="panel qr-confirmed"><div className="confirmation-banner" role="status"><CheckCircle2 aria-hidden="true"/><div><h2>Pagamento simulado confirmado</h2><p>A divisão desta venda já foi aplicada. Você pode voltar à página inicial.</p></div></div><div className="form-actions"><button className="primary" onClick={home}>Voltar à página inicial</button><button className="secondary" disabled={busy} onClick={()=>{setAmount('');setSelected([]);setParticipation(false);setRequest(rememberRequest(crypto.randomUUID()));}}>Receber outra venda</button></div><SaleReceipt state={state} sale={sale}/></section>;
 return <section className="panel receive-qr"><h2>Receber venda</h2><p className="muted">Cobrança local · pagamento digital simulado</p>{p?<>{sale&&!sale.paidAt&&chainOn?<SolanaPay token={p.token} onPaid={()=>{}}/>:<QR url={url}/>}<h3>{sale?money(sale.amount):'Defina o valor da venda'}</h3>{!sale&&<form onSubmit={async e=>{e.preventDefault();try{if(hasParticipation&&!selected.length)throw Error('Selecione o colaborador desta venda.');await post('payments/amount',{id:p.id,amount:parseMoney(amount),participantIds:hasParticipation?selected:[]});}catch(e){onError((e as Error).message);}}}><label>Valor (R$)<input name="amount" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required placeholder="Ex.: 40,00"/></label><SaleParticipation state={state} amount={cents} enabled={hasParticipation} onEnabled={setParticipation} selected={selected} onSelected={setSelected}/><button className="primary" disabled={busy}>Definir valor</button></form>}<p role="status">{sale?'Aguardando confirmação na página da cobrança.':'QR pronto. O pagamento aguarda o valor.'}</p><p className="note">{agreements?`${agreements} compromisso(s) serão considerados na divisão desta cobrança.`:'Nenhum compromisso ativo com saldo nesta cobrança. Acordos concluídos não recebem novas parcelas.'}{sale?' As regras foram capturadas quando você definiu o valor. Novos acordos valem para próximas cobranças.':' As regras são capturadas ao definir o valor.'}</p><a className="secondary" href={url} target="_blank" rel="noreferrer">Abrir cobrança neste computador</a><p className="muted">O QR abre uma simulação neste computador. Não transfere dinheiro real.</p></>:<><p>Preparando QR…</p><button disabled={busy} onClick={()=>post('payments/create',{requestId})}>Tentar novamente</button></>}</section>;
}
interface CheckoutView {amount:number|null;paid:boolean;confirmedAt?:string;receiptId?:string;chain?:{signature:string;testToken:true}}
export function CheckoutConfirmation({view}:{view:CheckoutView}){return <div className="checkout-success" role="status"><CheckCircle2 size={56} aria-hidden="true"/><h2>Pagamento simulado confirmado!</h2>{view.amount!==null&&<strong className="receipt-amount">{money(view.amount)}</strong>}<p>A confirmação foi registrada. Você pode voltar à página inicial.</p>{view.confirmedAt&&<p className="muted">{new Date(view.confirmedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>}<a className="primary" href="/#inicio">Voltar à página inicial</a><p className="muted">{view.chain?<>Pago com token de TESTE (BRL-T) na rede local deste computador. Registro: <code>{view.chain.signature.slice(0,22)}…</code></>:'Esta operação foi simulada localmente, sem transferência real.'}</p></div>;}
export function LocalCheckout({token}:{token:string}){const chain=useChainStatus();const [view,setView]=useState<CheckoutView>(),[error,setError]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{let alive=true;const refresh=async()=>{try{const r=await fetch('/api/payments/'+token),v=await r.json();if(!r.ok)throw Error(v.error);if(alive){setView(v);setError('');}}catch(e){if(alive)setError((e as Error).message);}};void refresh();const timer=setInterval(refresh,5000);return()=>{alive=false;clearInterval(timer);};},[token]);return <main className="checkout"><section className="panel"><img className="logo" src="/logo_giro.png" alt="GIRO"/><h1>Cobrança local</h1>{error&&<p className="error" role="alert">{error}</p>}{view?.paid?<CheckoutConfirmation view={view}/>:view?.amount?<><h2>{money(view.amount)}</h2>{chain?.enabled&&chain.cluster==='localnet'&&<SolanaPay token={token} onPaid={setView}/>}<label className="check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>{chain?.enabled?'Entendo que este pagamento usa a carteira de TESTE do GIRO e token BRL-T sem valor real.':'Entendo que esta confirmação é simulada e não transfere dinheiro.'}</label><button className="primary" disabled={!ack||busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/payments/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,acknowledged:ack})}),v=await r.json();if(!r.ok)throw Error(v.error);setView(v);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{chain?.enabled?'Pagar com a carteira de teste':'Confirmar pagamento simulado'}</button></>:<p>Aguardando o estabelecimento definir o valor…</p>}</section></main>;}
