import {SaleParticipation} from './SaleParticipation';
import {activeCash} from '../domain/cash';
import type {State,Sale} from '../domain/models';
import {useState} from 'react';
import {allocation,money,today} from '../domain/finance';
import {parseMoney} from '../domain/validation';
interface Props {mode?:'now'|'later'|'cash';state:State;busy:boolean;post:(path:string,input:unknown)=>Promise<boolean>;onError:(message:string)=>void;onSaved:()=>void}
const readDocument=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Não foi possível ler o documento.'));reader.readAsDataURL(file);});
export function SalesForm({state,busy,post,onError,onSaved,mode}:Props){
 const members=state.members.filter(m=>!m.disabledAt&&!m.demo),specific=members.filter(m=>m.participationMode==='specific'),automatic=members.filter(m=>m.active&&m.participationMode!=='specific');
 const [soldDate,setSoldDate]=useState(today()),[hasParticipation,setParticipation]=useState(false),[selected,setSelected]=useState<string[]>([]),[amount,setAmount]=useState(''),[attach,setAttach]=useState(false);
 let cents=0;try{cents=parseMoney(amount);}catch{}
 return <section className="panel"><h2>{mode==='now'?'Receber agora':mode==='cash'?'Registrar venda em dinheiro':'Registrar venda'}</h2><p className="muted">Registre a operação e a participação nesta venda.</p>{mode==='cash'&&!activeCash(state)&&<p className="note">Abra o caixa em dinheiro antes de registrar uma venda recebida em espécie. <a href="#receber/caixa">Abrir caixa</a></p>}<form onSubmit={async e=>{
  e.preventDefault();const form=e.currentTarget,f=new FormData(form);
  try{let supportingDocument:Sale['supportingDocument'];if(attach){const file=f.get('document');if(!(file instanceof File)||!file.size)throw Error('Selecione o documento complementar.');if(file.size>2*1024*1024||!['application/pdf','image/png','image/jpeg','text/plain'].includes(file.type))throw Error('Escolha PDF, PNG, JPEG ou TXT de até 2 MB.');supportingDocument={name:file.name,type:file.type,size:file.size,content:await readDocument(file),operation:String(f.get('operation')),parties:String(f.get('parties')),conditions:String(f.get('conditions')),commitmentId:String(f.get('commitmentId')||'')||undefined};}
   if(hasParticipation&&!selected.length)throw Error('Selecione ao menos um colaborador para esta venda.');
   const success=await post(mode==='cash'?'sales/cash':'sales',{participantIds:hasParticipation?selected:[],amount:parseMoney(amount),soldAt:f.get('soldAt'),soldTime:f.get('soldTime')||undefined,paidAt:mode==='later'?null:f.get('paidAt')||null,method:mode==='now'?'digital':mode==='cash'?'cash':f.get('method'),supportingDocument});if(success){form.reset();setAmount('');setSelected([]);setParticipation(false);setSoldDate(today());onSaved();}
  }catch(error){onError(error instanceof Error?error.message:'Revise os dados da venda.');}
 }}><label>Valor total (R$)<input name="amount" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" inputMode="decimal" required/></label><label>Meio de pagamento<select name="method" defaultValue={mode==='now'?'digital':'cash'} disabled={mode==='now'||mode==='cash'}><option value="cash">Venda em dinheiro</option><option value="digital">Pagamento digital simulado (sem transferência)</option></select></label><label>Data da venda<input name="soldAt" type="date" value={soldDate} onChange={e=>setSoldDate(e.target.value)} required/></label><label>Horário da venda (Brasília)<input name="soldTime" type="time" step="1" required={soldDate!==today()}/><small>Para venda antiga, usamos os turnos registrados naquele horário. Sem horário hoje, usamos o turno atual.</small></label>{mode!=='later'&&<label>Data do pagamento<input name="paidAt" type="date" defaultValue={today()} required={!!mode}/></label>}
 <SaleParticipation state={state} amount={cents} enabled={hasParticipation} onEnabled={setParticipation} selected={selected} onSelected={setSelected}/>
 <details><summary>Documento complementar da operação (opcional)</summary><p>Anexe o acordo ou comprovante que fundamenta a participação do trabalhador. Deve identificar operação, partes, valor total, percentual ou valor do colaborador, data, condições e ID do compromisso quando houver. Valor, data e colaborador são obrigatórios no formulário quando há participação; o arquivo não substitui esses dados.</p><label className="check"><input type="checkbox" checked={attach} onChange={e=>setAttach(e.target.checked)}/>Anexar documento local</label>{attach&&<><label>Identificação da operação<input name="operation" required maxLength={1000}/></label><label>Nomes das partes<input name="parties" required maxLength={1000}/></label><label>Condições acordadas<textarea name="conditions" required maxLength={1000}/></label><label>ID do compromisso (se houver)<input name="commitmentId" maxLength={160}/></label><label>Acordo ou comprovante — PDF, PNG, JPEG ou TXT, até 2 MB<input name="document" type="file" accept="application/pdf,image/png,image/jpeg,text/plain" required/></label><p className="muted">Arquivo guardado no banco local. Não há extração automática do conteúdo.</p></>}</details>
 <p className="note">Comissões e compromissos usam o bruto, respeitando o saldo restante e a capacidade da venda. Digital é simulado; dinheiro destinado ainda exige entrega confirmada.</p><button className="primary" disabled={busy||(mode==='cash'&&!activeCash(state))}>{busy?'Salvando…':'Registrar venda'}</button></form></section>;
}
