import {usePageSearch} from './PageSearch';
import {matches,searchDate,commitmentId} from '../domain/records';
import type {Sale,State} from '../domain/models';
import {money,movementLabel,saleDistribution,today,visibleSales} from '../domain/finance';
import {ReferenceIcon} from './ReferenceIcon';
interface Props {filter?:'paid'|'pending';selectedId?:string;onNavigate?:(route:string)=>void;state:State;busy:boolean;post:(path:string,input:unknown)=>Promise<boolean>}
const dateLabel=(date:string)=>date.split('-').reverse().join('/');
export function RecentActivity({state}:{state:State}){const query=usePageSearch();const sales=[...visibleSales(state)].filter(s=>matches(query,s.id,s.participant,s.rules,searchDate(s.soldAt),searchDate(s.paidAt),s.paidAt?'recebida':'pendente',money(s.amount))).sort((a,b)=>(b.settledAt??b.recordedAt??b.soldAt).localeCompare(a.settledAt??a.recordedAt??a.soldAt)).slice(0,3);return <div className="recent-activities">{!sales.length&&<p className="muted">Nenhuma venda registrada ainda.</p>}{sales.map(s=><article className="recent-activity" key={s.id}><ReferenceIcon name={s.paidAt?'income':'agreement'}/><div className="activity-copy"><strong>{s.paidAt?'Venda recebida':'Pagamento pendente'}</strong><small>{s.demo?'Exemplo fictício · ':''}{dateLabel(s.paidAt??s.soldAt)} · {s.method==='cash'?'Dinheiro':'Digital simulado'}</small></div><b className={s.paidAt?'green':'pending-value'}>{s.paidAt?'+':''}{money(s.amount)}</b></article>)}</div>;}
export function SaleReceipt({sale:s,busy=false,post,printable=false,state}:{state?:State;sale:Sale;busy?:boolean;post?:Props['post'];printable?:boolean}){const entries=saleDistribution(s);return <article className={`sale-receipt ${printable?'printable-receipt':''}`}><div className="receipt-heading"><div><p className="eyebrow">{s.paidAt?'REGISTRO DE RECEBIMENTO':'VENDA A RECEBER'}</p><h3>Venda #{s.id.slice(0,8)}</h3><span className="pill">{s.paidAt?s.method==='cash'?'Recebido em dinheiro':'Digital simulado confirmado':'Aguardando pagamento'}</span></div><strong className="receipt-amount">{money(s.amount)}</strong></div><dl className="receipt-fields"><div><dt>Data da venda</dt><dd>{dateLabel(s.soldAt)}</dd></div><div><dt>Data do recebimento</dt><dd>{s.paidAt?dateLabel(s.paidAt):'Ainda não recebido'}</dd></div><div><dt>Meio de pagamento</dt><dd>{s.method==='cash'?'Dinheiro físico':'Digital simulado'}</dd></div><div><dt>Participantes</dt><dd>{s.participant??'Sem colaborador nesta venda'}</dd></div></dl>{s.demo&&<p className="note">Exemplo fictício, fora dos registros reais.</p>}{s.legacy&&<p className="muted">Registro legado preservado sem aplicar novos acordos retroativamente.</p>}
 {s.paidAt&&<section className="receipt-distribution"><h4>Como o valor foi dividido</h4>{entries.map((entry,i)=><div className="receipt-destination" key={i}><div><strong>{entry.kind==='seller'?'Livre para o titular':entry.recipient}</strong><p>{entry.kind==='seller'?'Restante após as regras desta venda':entry.rateBps!==null?`${entry.rateBps/100}% do bruto`:entry.compensation==='fixed_sale'?'Valor fixo por venda':'Regra registrada'}</p>{entry.kind!=='seller'&&<p>{movementLabel(entry.mode)}</p>}{entry.kind==='commitment'&&<p>{(entry.commitmentPublicId??state?.commitments.find(c=>c.id===entry.recipientId))&&<>{entry.commitmentPublicId??commitmentId(state!.commitments.find(c=>c.id===entry.recipientId)!)} · </>}Restante após esta venda: {money(entry.remainingAfter??0)}</p>}</div><b>{money(entry.amount)}</b></div>)}{!entries.some(e=>e.kind==='commitment')&&<p className="muted">Nenhum compromisso com saldo elegível foi capturado para esta venda.</p>}<p className="receipt-footnote">{s.method==='cash'?'A divisão calcula os valores a separar. A entrega ao fornecedor ou funcionário é confirmada em seu pagamento.':'A divisão e a baixa dos acordos foram aplicadas automaticamente na simulação local. Nenhuma transferência real foi realizada.'}</p></section>}
 <details className="receipt-rules no-print"><summary>Regras aplicadas nesta venda</summary><ul>{s.rules.map((rule,i)=><li key={i}>{rule}</li>)}</ul></details>{!s.paidAt&&!s.demo&&post&&<form className="no-print" onSubmit={async e=>{e.preventDefault();await post('receive',{id:s.id,paidAt:new FormData(e.currentTarget).get('paidAt')});}}><label>Data do recebimento<input name="paidAt" type="date" min={s.soldAt} max={s.method==='cash'?today():undefined} defaultValue={today()} required/></label><button className="primary" disabled={busy}>Confirmar recebimento e dividir o valor</button><p className="muted">Usaremos os participantes e os acordos capturados nesta venda.</p></form>}{s.supportingDocument&&<details className="no-print"><summary>Documento complementar da operação</summary><p>{s.supportingDocument.operation} · {s.supportingDocument.parties}</p><p>{s.supportingDocument.conditions}</p><a className="secondary supporting-file" href={s.supportingDocument.content} download={s.supportingDocument.name}>Baixar documento local: {s.supportingDocument.name}</a></details>}<p className="receipt-reference">Registro local: {s.id}</p></article>;}
export function SalesHistory({state,busy,post,filter,selectedId,onNavigate}:Props){const query=usePageSearch();const sales=state.sales.filter(s=>matches(query,s.id,s.participant,s.rules,s.paidAt?'recebida':'pendente',s.method==='cash'?'dinheiro':'digital',searchDate(s.soldAt),searchDate(s.paidAt),money(s.amount))&&!s.demo&&(!filter||(filter==='paid'?!!s.paidAt:!s.paidAt))),demo=state.sales.filter(s=>s.demo),selected=selectedId?state.sales.find(s=>s.id===selectedId):undefined;const go=(route:string)=>onNavigate?onNavigate(route):location.hash=route;
 if(selectedId)return <section className="panel receipt-page"><div className="form-actions no-print"><button className="secondary" onClick={()=>go(filter==='paid'?'receber/pagamentos':'receber/vendas')}>← Voltar à lista</button>{selected&&<button className="primary" onClick={()=>window.print()}>Imprimir / salvar PDF</button>}</div>{selected?<SaleReceipt state={state} sale={selected} busy={busy} post={post} printable/>:<p>Venda não encontrada.</p>}</section>;
 return <section className="panel sales-history"><h2>{filter==='paid'?'Pagamentos recebidos':filter==='pending'?'Vendas a receber':'Histórico de vendas'}</h2><p className="muted">Abra uma venda para consultar ou imprimir seu registro completo.</p>{sales.length?sales.map(s=><article className="sale-list-card" key={s.id}><div className="section-title"><div><h3>{money(s.amount)}</h3><p>{dateLabel(s.soldAt)} · {s.method==='cash'?'Dinheiro':'Digital simulado'}</p></div><span className="pill">{s.paidAt?'Recebida':'Pendente'}</span></div><p>{s.participant??'Sem colaborador'}</p><button className="secondary" onClick={()=>go(`receber/${filter==='paid'?'pagamentos':filter==='pending'?'pendentes':'vendas'}/${s.id}`)}>{s.paidAt?'Abrir registro do recebimento':'Abrir venda / receber'}</button></article>):<p className="muted">Nenhuma venda nesta lista.</p>}{demo.length>0&&<details className="demo-archive"><summary>Exemplos fictícios preservados</summary>{demo.map(s=><SaleReceipt state={state} key={s.id} sale={s}/>)}</details>}</section>;
}
