/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertIsInstructionWithAccounts, containsBytes, extendClient, fixEncoderSize, getBytesEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT, SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, SolanaError, type Address, type ClientWithPayer, type ClientWithRpc, type ClientWithTransactionPlanning, type ClientWithTransactionSending, type ExtendedClient, type GetAccountInfoApi, type GetMultipleAccountsApi, type Instruction, type InstructionWithData, type ReadonlyUint8Array } from '@solana/kit';
import { addSelfFetchFunctions, addSelfPlanAndSendFunctions, type SelfFetchFunctions, type SelfPlanAndSendFunctions } from '@solana/kit/program-client-core';
import { getAgreementCodec, getOffchainPaymentCodec, getSellerStateCodec, type Agreement, type AgreementArgs, type OffchainPayment, type OffchainPaymentArgs, type SellerState, type SellerStateArgs } from '../accounts/index.ts';
import { getAcceptInstruction, getCancelProposalInstructionAsync, getConfirmOffchainPaymentInstruction, getDecideChangeInstruction, getDisputeOffchainPaymentInstruction, getProposeChangeInstruction, getProposeInstructionAsync, getRecordOffchainPaymentInstructionAsync, getRegisterSellerInstructionAsync, getRejectInstruction, getSetLimitsInstructionAsync, getSettleSaleInstructionAsync, parseAcceptInstruction, parseCancelProposalInstruction, parseConfirmOffchainPaymentInstruction, parseDecideChangeInstruction, parseDisputeOffchainPaymentInstruction, parseProposeChangeInstruction, parseProposeInstruction, parseRecordOffchainPaymentInstruction, parseRegisterSellerInstruction, parseRejectInstruction, parseSetLimitsInstruction, parseSettleSaleInstruction, type AcceptInput, type CancelProposalAsyncInput, type ConfirmOffchainPaymentInput, type DecideChangeInput, type DisputeOffchainPaymentInput, type ParsedAcceptInstruction, type ParsedCancelProposalInstruction, type ParsedConfirmOffchainPaymentInstruction, type ParsedDecideChangeInstruction, type ParsedDisputeOffchainPaymentInstruction, type ParsedProposeChangeInstruction, type ParsedProposeInstruction, type ParsedRecordOffchainPaymentInstruction, type ParsedRegisterSellerInstruction, type ParsedRejectInstruction, type ParsedSetLimitsInstruction, type ParsedSettleSaleInstruction, type ProposeAsyncInput, type ProposeChangeInput, type RecordOffchainPaymentAsyncInput, type RegisterSellerAsyncInput, type RejectInput, type SetLimitsAsyncInput, type SettleSaleAsyncInput } from '../instructions/index.ts';
import { findAgreementPda, findPaymentPda, findSellerStatePda } from '../pdas/index.ts';

export const GIRO_ACORDOS_PROGRAM_ADDRESS = 'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV' as Address<'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV'>;

export const GiroAcordosAccount = { 0: 'Agreement', 1: 'OffchainPayment', 2: 'SellerState', Agreement: 0, OffchainPayment: 1, SellerState: 2 } as const;

export type GiroAcordosAccount = (typeof GiroAcordosAccount)[Exclude<keyof typeof GiroAcordosAccount, number>];

export function identifyGiroAcordosAccount(account: { data: ReadonlyUint8Array } | ReadonlyUint8Array): GiroAcordosAccount {
    const data = 'data' in account ? account.data : account;
    if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([83, 212, 5, 110, 225, 249, 197, 84])), 0)) { return GiroAcordosAccount.Agreement; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([73, 126, 52, 187, 102, 57, 86, 23])), 0)) { return GiroAcordosAccount.OffchainPayment; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([250, 183, 151, 30, 213, 8, 45, 179])), 0)) { return GiroAcordosAccount.SellerState; }
    throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT, { accountData: data, programName: "giroAcordos" });
}

export const GiroAcordosEvent = { 0: 'AgreementAccepted', 1: 'AgreementCompleted', 2: 'AgreementProposed', 3: 'AgreementRejected', 4: 'ChangeDecided', 5: 'ChangeProposed', 6: 'OffchainPaymentConfirmed', 7: 'OffchainPaymentDisputed', 8: 'OffchainPaymentRecorded', 9: 'ProposalCancelled', 10: 'SaleSettled', AgreementAccepted: 0, AgreementCompleted: 1, AgreementProposed: 2, AgreementRejected: 3, ChangeDecided: 4, ChangeProposed: 5, OffchainPaymentConfirmed: 6, OffchainPaymentDisputed: 7, OffchainPaymentRecorded: 8, ProposalCancelled: 9, SaleSettled: 10 } as const;

export type GiroAcordosEvent = (typeof GiroAcordosEvent)[Exclude<keyof typeof GiroAcordosEvent, number>];

export function identifyGiroAcordosEvent(event: { data: ReadonlyUint8Array } | ReadonlyUint8Array): GiroAcordosEvent {
    const data = 'data' in event ? event.data : event;
    if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([179, 13, 67, 103, 171, 224, 35, 5])), 0)) { return GiroAcordosEvent.AgreementAccepted; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([213, 199, 79, 149, 251, 172, 90, 22])), 0)) { return GiroAcordosEvent.AgreementCompleted; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([223, 233, 107, 85, 28, 89, 104, 9])), 0)) { return GiroAcordosEvent.AgreementProposed; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([97, 58, 96, 83, 135, 37, 214, 211])), 0)) { return GiroAcordosEvent.AgreementRejected; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([9, 94, 117, 75, 139, 230, 208, 242])), 0)) { return GiroAcordosEvent.ChangeDecided; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([170, 10, 10, 8, 244, 196, 146, 151])), 0)) { return GiroAcordosEvent.ChangeProposed; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([21, 16, 232, 14, 18, 169, 58, 95])), 0)) { return GiroAcordosEvent.OffchainPaymentConfirmed; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([202, 199, 99, 146, 4, 117, 93, 187])), 0)) { return GiroAcordosEvent.OffchainPaymentDisputed; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([11, 18, 64, 2, 185, 100, 109, 189])), 0)) { return GiroAcordosEvent.OffchainPaymentRecorded; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([253, 59, 104, 46, 129, 78, 9, 14])), 0)) { return GiroAcordosEvent.ProposalCancelled; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([49, 60, 149, 181, 10, 243, 135, 56])), 0)) { return GiroAcordosEvent.SaleSettled; }
    throw new Error('The provided event could not be identified as a giroAcordos event.');
}

export const GiroAcordosInstruction = { 0: 'Accept', 1: 'CancelProposal', 2: 'ConfirmOffchainPayment', 3: 'DecideChange', 4: 'DisputeOffchainPayment', 5: 'Propose', 6: 'ProposeChange', 7: 'RecordOffchainPayment', 8: 'RegisterSeller', 9: 'Reject', 10: 'SetLimits', 11: 'SettleSale', Accept: 0, CancelProposal: 1, ConfirmOffchainPayment: 2, DecideChange: 3, DisputeOffchainPayment: 4, Propose: 5, ProposeChange: 6, RecordOffchainPayment: 7, RegisterSeller: 8, Reject: 9, SetLimits: 10, SettleSale: 11 } as const;

export type GiroAcordosInstruction = (typeof GiroAcordosInstruction)[Exclude<keyof typeof GiroAcordosInstruction, number>];

export function identifyGiroAcordosInstruction(instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array): GiroAcordosInstruction {
    const data = 'data' in instruction ? instruction.data : instruction;
    if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([65, 150, 70, 216, 133, 6, 107, 4])), 0)) { return GiroAcordosInstruction.Accept; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([106, 74, 128, 146, 19, 65, 39, 23])), 0)) { return GiroAcordosInstruction.CancelProposal; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([178, 191, 45, 64, 203, 153, 45, 92])), 0)) { return GiroAcordosInstruction.ConfirmOffchainPayment; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([207, 31, 49, 246, 157, 164, 88, 95])), 0)) { return GiroAcordosInstruction.DecideChange; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([191, 176, 2, 7, 135, 5, 138, 147])), 0)) { return GiroAcordosInstruction.DisputeOffchainPayment; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([93, 253, 82, 168, 118, 33, 102, 90])), 0)) { return GiroAcordosInstruction.Propose; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([167, 211, 18, 222, 93, 215, 74, 159])), 0)) { return GiroAcordosInstruction.ProposeChange; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([151, 174, 235, 117, 235, 215, 96, 213])), 0)) { return GiroAcordosInstruction.RecordOffchainPayment; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([9, 50, 144, 162, 206, 176, 154, 111])), 0)) { return GiroAcordosInstruction.RegisterSeller; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([135, 7, 63, 85, 131, 114, 111, 224])), 0)) { return GiroAcordosInstruction.Reject; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([207, 50, 250, 67, 211, 33, 70, 91])), 0)) { return GiroAcordosInstruction.SetLimits; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([182, 49, 63, 248, 140, 81, 40, 126])), 0)) { return GiroAcordosInstruction.SettleSale; }
    throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, { instructionData: data, programName: "giroAcordos" });
}

export type ParsedGiroAcordosInstruction<TProgram extends string = 'CVAQPvyjepuDP9j5df22ipp9E7XWVxej1T26rb4NvEMV'> =
| { instructionType: typeof GiroAcordosInstruction.Accept } & ParsedAcceptInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.CancelProposal } & ParsedCancelProposalInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.ConfirmOffchainPayment } & ParsedConfirmOffchainPaymentInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.DecideChange } & ParsedDecideChangeInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.DisputeOffchainPayment } & ParsedDisputeOffchainPaymentInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.Propose } & ParsedProposeInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.ProposeChange } & ParsedProposeChangeInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.RecordOffchainPayment } & ParsedRecordOffchainPaymentInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.RegisterSeller } & ParsedRegisterSellerInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.Reject } & ParsedRejectInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.SetLimits } & ParsedSetLimitsInstruction<TProgram>
| { instructionType: typeof GiroAcordosInstruction.SettleSale } & ParsedSettleSaleInstruction<TProgram>


        export function parseGiroAcordosInstruction<TProgram extends string>(
            instruction: Instruction<TProgram> 
                & InstructionWithData<ReadonlyUint8Array>
        ): ParsedGiroAcordosInstruction<TProgram> {
            const instructionType = identifyGiroAcordosInstruction(instruction);
            switch (instructionType) {
                case GiroAcordosInstruction.Accept: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.Accept, ...parseAcceptInstruction(instruction) }; }
case GiroAcordosInstruction.CancelProposal: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.CancelProposal, ...parseCancelProposalInstruction(instruction) }; }
case GiroAcordosInstruction.ConfirmOffchainPayment: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.ConfirmOffchainPayment, ...parseConfirmOffchainPaymentInstruction(instruction) }; }
case GiroAcordosInstruction.DecideChange: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.DecideChange, ...parseDecideChangeInstruction(instruction) }; }
case GiroAcordosInstruction.DisputeOffchainPayment: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.DisputeOffchainPayment, ...parseDisputeOffchainPaymentInstruction(instruction) }; }
case GiroAcordosInstruction.Propose: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.Propose, ...parseProposeInstruction(instruction) }; }
case GiroAcordosInstruction.ProposeChange: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.ProposeChange, ...parseProposeChangeInstruction(instruction) }; }
case GiroAcordosInstruction.RecordOffchainPayment: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.RecordOffchainPayment, ...parseRecordOffchainPaymentInstruction(instruction) }; }
case GiroAcordosInstruction.RegisterSeller: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.RegisterSeller, ...parseRegisterSellerInstruction(instruction) }; }
case GiroAcordosInstruction.Reject: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.Reject, ...parseRejectInstruction(instruction) }; }
case GiroAcordosInstruction.SetLimits: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.SetLimits, ...parseSetLimitsInstruction(instruction) }; }
case GiroAcordosInstruction.SettleSale: { assertIsInstructionWithAccounts(instruction);
return { instructionType: GiroAcordosInstruction.SettleSale, ...parseSettleSaleInstruction(instruction) }; }
                default: throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, { instructionType: instructionType as string, programName: "giroAcordos" });
            }
        }

export type GiroAcordosPlugin = { accounts: GiroAcordosPluginAccounts; instructions: GiroAcordosPluginInstructions; pdas: GiroAcordosPluginPdas; identifyAccount: typeof identifyGiroAcordosAccount; identifyInstruction: typeof identifyGiroAcordosInstruction; parseInstruction: typeof parseGiroAcordosInstruction; }

export type GiroAcordosPluginAccounts = { agreement: ReturnType<typeof getAgreementCodec> & SelfFetchFunctions<AgreementArgs, Agreement>; offchainPayment: ReturnType<typeof getOffchainPaymentCodec> & SelfFetchFunctions<OffchainPaymentArgs, OffchainPayment>; sellerState: ReturnType<typeof getSellerStateCodec> & SelfFetchFunctions<SellerStateArgs, SellerState>; }

export type GiroAcordosPluginInstructions = { accept: (input: AcceptInput) => ReturnType<typeof getAcceptInstruction> & SelfPlanAndSendFunctions; cancelProposal: (input: CancelProposalAsyncInput) => ReturnType<typeof getCancelProposalInstructionAsync> & SelfPlanAndSendFunctions; confirmOffchainPayment: (input: ConfirmOffchainPaymentInput) => ReturnType<typeof getConfirmOffchainPaymentInstruction> & SelfPlanAndSendFunctions; decideChange: (input: DecideChangeInput) => ReturnType<typeof getDecideChangeInstruction> & SelfPlanAndSendFunctions; disputeOffchainPayment: (input: DisputeOffchainPaymentInput) => ReturnType<typeof getDisputeOffchainPaymentInstruction> & SelfPlanAndSendFunctions; propose: (input: ProposeAsyncInput) => ReturnType<typeof getProposeInstructionAsync> & SelfPlanAndSendFunctions; proposeChange: (input: ProposeChangeInput) => ReturnType<typeof getProposeChangeInstruction> & SelfPlanAndSendFunctions; recordOffchainPayment: (input: RecordOffchainPaymentAsyncInput) => ReturnType<typeof getRecordOffchainPaymentInstructionAsync> & SelfPlanAndSendFunctions; registerSeller: (input: RegisterSellerAsyncInput) => ReturnType<typeof getRegisterSellerInstructionAsync> & SelfPlanAndSendFunctions; reject: (input: RejectInput) => ReturnType<typeof getRejectInstruction> & SelfPlanAndSendFunctions; setLimits: (input: SetLimitsAsyncInput) => ReturnType<typeof getSetLimitsInstructionAsync> & SelfPlanAndSendFunctions; settleSale: (input: MakeOptional<SettleSaleAsyncInput, "payer">) => ReturnType<typeof getSettleSaleInstructionAsync> & SelfPlanAndSendFunctions; }

export type GiroAcordosPluginPdas = { sellerState: typeof findSellerStatePda; agreement: typeof findAgreementPda; payment: typeof findPaymentPda; }

export type GiroAcordosPluginRequirements = ClientWithRpc<GetAccountInfoApi & GetMultipleAccountsApi> & ClientWithPayer & ClientWithTransactionPlanning & ClientWithTransactionSending

export function giroAcordosProgram() {
    return <T extends GiroAcordosPluginRequirements>(client: T): ExtendedClient<T, { giroAcordos: GiroAcordosPlugin }> => {
        return extendClient(client, { giroAcordos: { accounts: { agreement: addSelfFetchFunctions(client, getAgreementCodec()), offchainPayment: addSelfFetchFunctions(client, getOffchainPaymentCodec()), sellerState: addSelfFetchFunctions(client, getSellerStateCodec()) }, instructions: { accept: input => addSelfPlanAndSendFunctions(client, getAcceptInstruction(input)), cancelProposal: input => addSelfPlanAndSendFunctions(client, getCancelProposalInstructionAsync(input)), confirmOffchainPayment: input => addSelfPlanAndSendFunctions(client, getConfirmOffchainPaymentInstruction(input)), decideChange: input => addSelfPlanAndSendFunctions(client, getDecideChangeInstruction(input)), disputeOffchainPayment: input => addSelfPlanAndSendFunctions(client, getDisputeOffchainPaymentInstruction(input)), propose: input => addSelfPlanAndSendFunctions(client, getProposeInstructionAsync(input)), proposeChange: input => addSelfPlanAndSendFunctions(client, getProposeChangeInstruction(input)), recordOffchainPayment: input => addSelfPlanAndSendFunctions(client, getRecordOffchainPaymentInstructionAsync(input)), registerSeller: input => addSelfPlanAndSendFunctions(client, getRegisterSellerInstructionAsync(input)), reject: input => addSelfPlanAndSendFunctions(client, getRejectInstruction(input)), setLimits: input => addSelfPlanAndSendFunctions(client, getSetLimitsInstructionAsync(input)), settleSale: input => addSelfPlanAndSendFunctions(client, getSettleSaleInstructionAsync({ ...input, payer: input.payer ?? client.payer })) }, pdas: { sellerState: findSellerStatePda, agreement: findAgreementPda, payment: findPaymentPda }, identifyAccount: identifyGiroAcordosAccount, identifyInstruction: identifyGiroAcordosInstruction, parseInstruction: parseGiroAcordosInstruction } as GiroAcordosPlugin });
    };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;